### ISSUE TITLE
Afegir m3u Mediaset

### ISSUE THREAD

**Issue by javirg** [LaQuay/TDTChannels#1]
Aquí et deixo el stream de Cuatro.

http://mset-prod-1.live-delivery.ooyala.com/out/u/3vkkbgnvsm2r5/104951/1wNHRhYjE61kGMsySKOTnzPZzYO38rtd/cn/34a2f95c460e44c086b5f883f3de6e74_4.m3u8

**Comment by javirg** [comment]
Aquí el de Telecinco.

http://mset-prod-1.live-delivery.ooyala.com/out/u/3vkkbgnvsm2r5/104951/RsZXlnNTE6re1fFuFEI0UrdA2Uj7pNGM/cn/5d62490854b545598f64eaa84709400b_4.m3u8

**Comment by LaQuay** [comment]
Hola @javirg,
Gràcies, saps si són oficials? Veig que ooyala és la plataforma que utilitza Mediaset.

Així doncs, els afegeixo. Gràcies de nou.

**Comment by javirg** [comment]
Sí, els vaig treure fa temps de la web de Mitele.

No sé cada quant de temps es van regenerant els enllaços, però a mi em porten funcionant més de tres mesos sense problemes.

**Comment by LaQuay** [comment]
Perfecte, gràcies.
Tanco 👍
