### ISSUE TITLE
Mega ya no funciona ...

### ISSUE THREAD

**Issue by gentauro** [LaQuay/TDTChannels#10]
Me parece que han cambiado el enlace de Mega y LaSexta. Puedes confirmar?

**Comment by LaQuay** [comment]
Hola @gentauro. Ayer justamente estuve mirando qué pasaba. Parece ser que Atresmedia anda toqueteando el tema de sus _streams_. A ver si hoy puedo mirar que andan haciendo y recuperar los enlaces.
Si alguien tiene más información que la comente a ver 👍

**Comment by LaQuay** [comment]
Solucionado!
