### ISSUE TITLE
Canal no funciona: Canal EXTREMADURA 

### ISSUE THREAD

**Issue by ph100564** [LaQuay/TDTChannels#1004]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by LaQuay** [comment]
Hola, acabo de probar y funciona.
