### ISSUE TITLE
Canal no funciona: Antena 3

### ISSUE THREAD

**Issue by joiseg** [LaQuay/TDTChannels#1009]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by LaQuay** [comment]
Ya vuelve a estar funcionando.
https://github.com/LaQuay/TDTChannels/commit/8929242686391afb81ba9c544c31f27ce0ac57b9

**Comment by joiseg** [comment]
Muchas gracias
