### ISSUE TITLE
Canal no funciona: Canal Sur 1

### ISSUE THREAD

**Issue by oscar682** [LaQuay/TDTChannels#1017]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by LaQuay** [comment]
Han dejado de emitir online.
