### ISSUE TITLE
Canal no funciona: ACS Network

### ISSUE THREAD

**Issue by GerardoHD** [LaQuay/TDTChannels#1027]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
https://acsnetwork.tv/
<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://cloudflare.streamgato.us:3283/live/acsnetworklive.m3u8

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
ACS Network está "de vacaciones" y no está transmitiendo por el momento. En la web no indica cuando reanudarán emisiones.

**Comment by LaQuay** [comment]
https://github.com/LaQuay/TDTChannels/pull/1175
