### ISSUE TITLE
Canal  A3S no funciona

### ISSUE THREAD

**Issue by jshq1971** [LaQuay/TDTChannels#1046]
Buenos días,A3S no funciona bajo ninguna forma.Gracia

**Comment by LaQuay** [comment]
Hola. Dónde no funciona? A mi me está funcionando sin problema en Android. El único lugar donde funciona: http://tdtchannels.com/status

**Comment by jshq1971** [comment]
Hola,en Perú

**Comment by LaQuay** [comment]
Como indica en el enlace http://tdtchannels.com/status, posible geolocalización a España.
