### ISSUE TITLE
Canal no funciona: Telecinco

### ISSUE THREAD

**Issue by danielebogo** [LaQuay/TDTChannels#1053]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
https://www.tdtchannels.com/lists/tv.m3u8

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://linear01-i.akamaihd.net/hls/live/837810/telecinco/01.m3u8

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by jerocobo** [comment]
No funcionan ninguno de los canales de mediaset con las URLs que hay en las listas.

**Comment by LaQuay** [comment]
Buenas, correcto, han cesado emision M3U8. Por ahora se pueden ver mediante nuestra APP Android.

**Comment by danielebogo** [comment]
@LaQuay cual es la url que usa la app Android? Porqué no actualizar la playlist m3u y m3u8?
