### ISSUE TITLE
Canal no funciona: Canales de mediaset y atreseries

### ISSUE THREAD

**Issue by prtz1** [LaQuay/TDTChannels#1059]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by LaQuay** [comment]
El estado de los canales está en https://github.com/LaQuay/TDTChannels/blob/master/info_television.md
Si encuentras algún dato incorrecto, coméntalo.
Gracias.

**Comment by prtz1** [comment]
EXACTAMENTE, los canales de mediaset en m3u8 están rotos
