### ISSUE TITLE
EPG adn40

### ISSUE THREAD

**Issue by GerardoHD** [LaQuay/TDTChannels#1081]
adn40 publica su epg como .json en la URL: 
https://tv-azteca-brightspot.s3-us-west-1.amazonaws.com/program_schedule/ADN40FeedEPG.json

**Comment by LaQuay** [comment]
Hola @GerardoHD! Menciono a @HelmerLuzo a ver que se puede hacer.

**Comment by LaQuay** [comment]
Se añade en https://github.com/LaQuay/TDTChannels/commit/becc5832dcad6ad5c07ffc3f32369b47f44e1c29, gracias!
