### ISSUE TITLE
Versión Android: Posibilidad de enviar a Chromecast

### ISSUE THREAD

**Issue by malversan** [LaQuay/TDTChannels#1095]
Ante todo gracias por tu labor. Realmente hace usted honor al concepto de software libre, y no puedo sino felicitarle por ello.

A menudo utilizo la app Android para ver las noticias mientras voy al trabajo. Pero hace poco hubo reparaciones en mi edificio que afectaron la antena comunitaria de televisión, y durante unos días la app fue mi acceso a la TDT.

Entonces descubrí que a pesar de disponer de un Chromecast no podía enviar la imagen directamente desde la app al televisor, sino que tenía que acceder a la opción de Google Home para proyectar en el Chromecast toda la pantalla del móvil. Algo bastante engorroso de hacer cada vez que se quiere ver la televisión.

¿Sería posible o costoso incorporar a la app Android el típico botón que permite enviar la imagen a un Chromecast, al estilo de otras aplicaciones como Youtube o Mobdro?

Obviamente no es algo prioritario, pues poca gente va a necesitar proyectar canales de televisión precisamente en un televisor, ya que éste cuenta con su propio sintonizador de canales. Pero es una mejora que podría servir para ver la TDT en pantalla grande en situaciones en las que la señal digital de la TDT no llega con calidad o en lugares donde no pueden verse todos los canales que provee la extensa lista de TDTChannels (en el extranjero, por ejemplo).

Muchas gracias anticipadas por su atención.

**Comment by adrianpaniagualeon** [comment]
Buenos dias,
En la version v2.3.0 que fue publicada el dia 25 / 12 / 2020 se añadió la compatibilidad con CHROMECAST para emisiones de TV.

Puedes descargarla desde el siguiente enlace: https://www.tdtchannels.com/android

**Comment by LaQuay** [comment]
Gracias @adrianpaniagualeon!

Cierro!

**Comment by malversan** [comment]
No esperaba ver esta prestación tan rápidamente implementada. Cada vez me agrada más este software.

Muchísimas gracias.
