### ISSUE TITLE
Canal no funciona: Los canales atresmedia no funcionan 

### ISSUE THREAD

**Issue by alex13450** [LaQuay/TDTChannels#1097]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by ml-pa** [comment]
Cierto, ninguno de ellos, desde hace tres o cuatro días mínimo.

**Comment by LaQuay** [comment]
Hola, desde ayer. En un rato actualizamos lista para eliminarlos. Los podéis seguir utilizando con la APP.

**Comment by davidnm** [comment]
Alguien sabe por qué hacen eso? En verano se apagaron todos los de a3 media y mediaset. Pero luego volvieron como en septiembre y ahora otra vez todos apagados...
Lo hacen por algo??

**Comment by corrido** [comment]
Pues dieron a entender, tanto Mediaset como Atresmedia, que para ver sus contenidos en streaming había que pagar los paquetes que ofrecen. No sé por qué Atresmedia reculó (si es que lo hizo) y ahora vuelven a capar los contenidos

A ver si los liberan, porque a mí viviendo en el extranjero me hacen polvo

**Comment by davidnm** [comment]
Yo vivo en el extranjero también y eso con kodi iba genial, pero si no uso la app TDT Channels, lo malo que no va bien en android TV y desde el móvil no se puede compartir en TV, luego también está mobdro que si que puedes compartir, pero se corta más la emisión.... va peor...

**Comment by LaQuay** [comment]
Desde aquí no sabemos los motivos. Por favor, cuando habléis no citeis aplicaciones ilegales, @davidnm. Gracias!

**Comment by davidnm** [comment]
ah disculpa, he borrado el comentario.

**Comment by cuentawarra** [comment]
Desde la aplicacion los de mediaset funcionan pero los de atresmedia no.

Tambien me gustaria saber por que algunos canales van en la app y no funciona desde las listas o web , que limitación tecnica hay?
