### ISSUE TITLE
Canal no funciona: radio marca

### ISSUE THREAD

**Issue by chato99** [LaQuay/TDTChannels#1179]
Hola compañeros, no funciona radio marca. un saludo gran trabajo

**Comment by chato99** [comment]
a dia de hoy funciona con este link: 

https://15903.live.streamtheworld.com/RADIOMARCA_NACIONAL.mp3

**Comment by adrianpaniagualeon** [comment]
https://t.me/tdtchannels_avisos/535

Ya han actualizado el enlace
