### ISSUE TITLE
Canales M3U8

### ISSUE THREAD

**Issue by paurg15** [LaQuay/TDTChannels#13]
¡Hola!
Ahora he estado revisando el archivo .m3u8 y he visto que faltan algunos canales:
La 2, los nuevos enlaces de los canales de Atresmedia, que cambie el nombre de Antena 3 Eventos a Atresplayer Exclusivo, la segunda opción de Cuatro y TeleCinco, TDP, TDP HD, GOL TV, Real Madrid TV, Betis TV, Sevilla TV, La 1 Catalunya y los internacionales.

También te querría preguntar por lo de la app que dijiste que querías desarrollar para ver todos los canales. ¡Por lo demás todo correcto y muy buen trabajo!

**Comment by LaQuay** [comment]
@paurg15 Hola!
El .m3u8 se genera manualmente, de momento no he podido automatizarlo, voy justo de tiempo. Este fin de semana estoy revisando los enlaces y una vez termine, actualizaré el .m3u8.

Además, Mediaset ha bloqueado los .m3u8 así que ando buscando alguna solución 😢 

Sobre la aplicación, sigue todo igual, falta de tiempo 😞

**Comment by paurg15** [comment]
Vale! Ningún problema, bastante haces con esto! De momento seguiré utilizando la app de Atresplayer (aunque tiene muchísimos bugs) y el actual archivo .m3u8
