### ISSUE TITLE
Canal no funciona: Azteca 7

### ISSUE THREAD

**Issue by sguinetti** [LaQuay/TDTChannels#1316]
Saludos. La URL de Azteca 7 redirige a un nuevo enlace que, sin embargo, generá un error 403:

> Failed reading https://aztkhlslive5-i.akamaihd.net:443/hls/live/1019873/4ztk7bacf4uoy8/20210211T055959/master_03/00005/master_03_00361.ts: HTTP/1.1 403 Forbidden

Adicionalmente, la antigua web ya redirige a la nueva web: https://www.tvazteca.com/azteca7. De todas formas, dice que no está disponible fuera de su cobertura y, en su lugar, solo se reproducen los vídeos de un programa de comedia.

**Comment by LaQuay** [comment]
Gracias por el aviso, borramos!
