### ISSUE TITLE
Actualizar canal TV Rioja

### ISSUE THREAD

**Issue by BELENSAINZ** [LaQuay/TDTChannels#1330]
Hola, TV Rioja a actualizado su sitio web, les mando las url nuevas del SITIO WEB y la programación para que lo actualizen

URL DIRECTO: https://players.brightcove.net/86746484001/rJ0nzIuK_default/index.html?videoId=6136786877001 (YA NO EMITEN DESDE UNA WEB ESTATICA, como antes lo hacían desde http://www.tvr.es/directo/)

Programación: https://proyectos.larioja.com/tvr/dimeprogramacion/dimeprogramacion.php

**Comment by LaQuay** [comment]
Hola Belén, hablas en representación de TV Rioja? O eres una usuaria? Gracias!

**Comment by BELENSAINZ** [comment]
SI, soy una usuaría y se lo envié para que lo actualizén el canal en TDTCHANNELS. Un saludo
