### ISSUE TITLE
Actualización de radios

### ISSUE THREAD

**Issue by rccavalcanti** [LaQuay/TDTChannels#134]
Hola,

Os dejo una actualización para radios que no funcionan.

### Nacionales
Radio Nacional - http://hlsliveamdgl0-lh.akamaihd.net/i/rnerne_1@586398/master.m3u8
Radio Clásica - http://hlsliveamdgl0-lh.akamaihd.net/i/rnerc_1@586399/master.m3u8
Radio 3 - http://hlsliveamdgl0-lh.akamaihd.net/i/rnerne3_1@793568/master.m3u8
Ràdio 4 - http://hlsliveamdgl0-lh.akamaihd.net/i/rnerne4_1@793569/master.m3u8
Radio 5 - http://hlsliveamdgl0-lh.akamaihd.net/i/rnerne5_1@793570/master.m3u8
Radio Exterior - http://hlsliveamdgl0-lh.akamaihd.net/i/rneree_1@793572/master.m3u8
Rock FM - https://rockfm-cope.flumotion.com/playlist.m3u8

### Autonómicas
(Los enlaces en la lista no son de estas radios sino de CanalSur Radio.)

Canal Fiesta Radio - http://195.55.74.204/rtva/canalfiestaradio_master.mp3
Flamenco Radio - http://195.55.74.203/rtva/canalflamenco.mp3

**Comment by LaQuay** [comment]
Muchas gracias! Con PR me facilitáis la tarea jeje
