### ISSUE TITLE
Canal no funciona: Telebilbao

### ISSUE THREAD

**Issue by Euskalgaming** [LaQuay/TDTChannels#1354]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
https://www.telebilbao.es/directo/
<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://cloudbilbao.todostreaming.es/live/telebilbao-livestream.m3u8

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
No reproducia el enlace a no ser que fuese por medio del navegtador al no informar en el del user-agent requerido en el m3u.
Aporto nuevo enlace creado por mi corregido que hace que funcione en gestores con vlc etc...
https://raw.githubusercontent.com/Euskalgaming/Tele/main/TeleBilbao.m3u

**Comment by Euskalgaming** [comment]
Si puedes actualizar para siguientes versiones.... Un saludo.

**Comment by Nomenteros** [comment]
Gracias por el Aporte Euskalgaming, en cuanto Marc pueda, actualizaremos el user-agent, adaptándolo a la lista m3u - m3u8.Ya hemos comentado el caso y requiere una pequeña modificación.
Saludos

**Comment by LaQuay** [comment]
Arreglado, gracias por el aviso!
