### ISSUE TITLE
Nivelador de volumen

### ISSUE THREAD

**Issue by sanchezcaro** [LaQuay/TDTChannels#1364]
Hola

Propongo añadir una opción para nivelar el volumen. Suelo ver Cuatro y el volumen sube sobre todo en los anuncios, aunque se agradecería que el nivelador también pudiera funcionar en cualquier momento que suba el volumen, escenas de acción por ejemplo. Tengo un bebé y a veces me lo despierta.

Gracias

**Comment by venoty00** [comment]
Activa el volumen automático de tu tv

**Comment by sanchezcaro** [comment]
No tengo televisión. TDTchannels es una aplicación para Android, y uso el proyector integrado en mi móvil.
No he encontrado ninguna app en Android que baje el volumen automáticamente cuando éste sube demasiado.

**Comment by LaQuay** [comment]
Hola, descartamos debido a la complejidad de la propuesta y que, como bien se indica, no depende de nosotros. Gracias!
