### ISSUE TITLE
https://cdn-02.fibracat.cat/fibracattv/index.m3u8 has an issue with https

### ISSUE THREAD

**Issue by elefant66** [LaQuay/TDTChannels#1391]
https://cdn-02.fibracat.cat/fibracattv/index.m3u8 ya no va en mi tele:(
http://cdn-02.fibracat.cat/fibracattv/index.m3u8 va en mit tele:)

**Comment by LaQuay** [comment]
Gracias @elefant66, tomamos nota

**Comment by LaQuay** [comment]
https://github.com/LaQuay/TDTChannels/pull/1406
