### ISSUE TITLE
Incidencias (2) canales: Grupo Cuatro/Telecinco y A3/La Sexta

### ISSUE THREAD

**Issue by aikemepika** [LaQuay/TDTChannels#1392]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
Hola. Cuatro, Telecinco y el resto de canales del grupo dan trompicones en la emisión, reiniciándose cada vez en los últimos segundos de cada segmento. Del grupo de canales de A3 y la Sexta, la sintonización tarda más de lo habitual y se va interrumpiendo la emisión al poco tiempo, volviéndose a reanudar y volviéndose a detener, a diferencia de los canales de TVE, que se sintonizan al momento y sin interrupciones de las correspondientes emisiones.
Gracias por la asistencia.

**Comment by gpascualg** [comment]
Confirmo la issue. Como detalle, parece que sean los canales que funcionan con MPD. Todos los canales con un stream m3u8 típico funcionan correctamente.
