### ISSUE TITLE
FDF no carga

### ISSUE THREAD

**Issue by Raquebi** [LaQuay/TDTChannels#1397]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by adrianpaniagualeon** [comment]
FDF, al igual que el resto de canales de Mediaset, solo está disponible en la app de Android y a través de su web oficial (https://www.mitele.es/directo/fdf/) . Además, ciertos canales cuentan con geobloqueo por lo que no se pueden ver desde fuera de España o utilizando una VPN con IP española. 

Espero haberte ayudado.

**Comment by LaQuay** [comment]
Si no hay más información cerraré en 3 días.

**Comment by Raquebi** [comment]
Muchas gracias por la información.
