### ISSUE TITLE
Telemadrid no funciona: y un nuevo link para Telemadrid

### ISSUE THREAD

**Issue by stef85271** [LaQuay/TDTChannels#1400]
Hi guys,

It's been a few days Telemadrid M3U8 link isn't working anymore.
I have been wandering around the official Telemadrid player and it turns out there is a M3U8 link you can extract from it, which seems to work. In fact, you can extract both the HD link and the SD link :

Telemadrid HD link (M3U8) :
https://telemadridhls2-live-hls.secure2.footprint.net/egress/chandler/telemadrid/telemadrid_1/bitrate_1.m3u8

Telemadrid SD link (M3U8) :
https://telemadridhls2-live-hls.secure2.footprint.net/egress/chandler/telemadrid/telemadrid_1/bitrate_2.m3u8

Hope this helps.

**Comment by adrianpaniagualeon** [comment]
Hello Marc has updated the channel a few hours ago. (https://t.me/tdtchannels_avisos/556)

Thanks for contributing 🙂
