### ISSUE TITLE
Canal no funciona: 7 TV Andalucía

### ISSUE THREAD

**Issue by heroku-miraheze** [LaQuay/TDTChannels#1474]
https://7tvandalucia.es/

Cogidos los enlaces nuevos desde todas sus páginas.

7 TV Andalucía, cambió sus enlaces, y ahora es posible verlo en público, sin necesidad de tener la aplicación abierta.

**Comment by SrIzan10** [comment]
Enlace es:
`[https://d1g97lrq10u9vw.cloudfront.net/out/v1/974cf9bdf63442ab8e3a64f12557bfb5/index.m3u8](url)`.

**Comment by SrIzan10** [comment]
![image](https://user-images.githubusercontent.com/66965250/116806840-04aa9480-ab30-11eb-81e4-f7365e4629fd.png)
Hay otro que es `index_1.m3u8` pero reproduce lo mismo.

**Comment by LaQuay** [comment]
Estamos pendientes, revisando. Gracias!

**Comment by LaQuay** [comment]
Añadidos hace unos días, gracias!

**Comment by SrIzan10** [comment]
Gracias a tí!
