### ISSUE TITLE
Añadir canal STV Rioja (tiene flash player)

### ISSUE THREAD

**Issue by jonsaenz21** [LaQuay/TDTChannels#1481]
Hola, les envio un canal que he encontrado en internet que se llama "**STV Rioja**" que es de **La Rioja** para que lo incluyan en TDTCHANNELS, (tiene flash player)
URL WEB DIRECTO: https://www.stvrioja.com/stvonline.html
Muchas gracias

**Comment by SrIzan10** [comment]
Utiliza el formato `mms://`. No creo que funcione, pero bueno.

**Comment by SrIzan10** [comment]
Y además, como Flash Player está fuera de soporte (https://www.adobe.com/es/products/flashplayer/end-of-life.html), pues será más difícil implementarlo.

**Comment by jonsaenz21** [comment]
Pero lo intentareis implementarlo?? 
Un saludo😄

**Comment by SrIzan10** [comment]
> Pero lo intentareis implementarlo??
> Un saludo😄

@LaQuay es el que sabe qué hacer.
(Ah, y lo siento por la mención)

**Comment by LaQuay** [comment]
Hola, no se puede debido a que el flash player de por si es otro tema diferente.
"El 31 de diciembre de 2020, Adobe finalizó el soporte técnico del programa, poniéndole fin a 24 años de existencia. "
