### ISSUE TITLE
DESAPARICION UNOS CANALES REGIONALES DE LA 1 COMO LA 1 ANDALUCIA LA 1 C VALENCIANA, LA 1 MADRID... 

### ISSUE THREAD

**Issue by RUGBYMAN13** [LaQuay/TDTChannels#1488]
Hola,

Hace unas semanas habían aparecido unos canales regionales de la 1, como la 1 Andalucia, La 1 C. Valenciana, la 1 C. Madrid,...
Desde hace poco tiempo desaparecieron estos de nuevo, sólo quedan los de Catalunya, de Canarias y de Aragon...
Seria posible tenerlos de nuevo? Muchas gracias!

**Comment by SrIzan10** [comment]
@LaQuay

**Comment by adrianpaniagualeon** [comment]
Buenas tardes, 
Marc lo explico hace unos dias en el grupo de Telegram (https://t.me/tdtchannels/98602).  Desde Github puedes seguir viendo los enlaces en el commit de playzzz  (https://github.com/LaQuay/TDTChannels/commit/2dbb6982220aa5579fba80713ad548520d674500)
