### ISSUE TITLE
Lasexta does not work

### ISSUE THREAD

**Issue by freseco** [LaQuay/TDTChannels#149]

**Comment by playzzz** [comment]
That may be because there are two links, the first is global, it is for everyone in the world, and the second is GEO, geolocated, and depending on whether Atresmedia has worldwide rights or only for Spain.

**Comment by LaQuay** [comment]
Hi! Yes, it is working. +1 to @playzzz explanation.

![image](https://user-images.githubusercontent.com/6410250/56637170-449a2f80-666b-11e9-8098-fc15485dbba5.png)
