### ISSUE TITLE
BeMadCanal no funciona: NOMBRE

### ISSUE THREAD

**Issue by chuchi1987** [LaQuay/TDTChannels#1492]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by LaQuay** [comment]
Funcionando. Revisa tdtchannels.com/status.
