### ISSUE TITLE
Enlace canales españoles iptv

### ISSUE THREAD

**Issue by chamberitiger** [LaQuay/TDTChannels#1509]
Qué enlace me recomiendan para ver canales de televisión españoles iptv con Android auto. Gracias.

**Comment by adrianpaniagualeon** [comment]
Buenas tardes,

En la web de TDTChannels tienes los enlaces a las listas: https://www.tdtchannels.com/listas. También tienes disponible la app para Android (https://www.tdtchannels.com/android).

**Comment by chamberitiger** [comment]
Gracias 🙂

**Comment by chamberitiger** [comment]
Y sirve para ver en el coche 🚗?
