### ISSUE TITLE
Propuesta

### ISSUE THREAD

**Issue by Hiruzulo** [LaQuay/TDTChannels#1518]
¿Es posible añadir el canal ETB 3 a la lista? Muchas gracias

**Comment by LaQuay** [comment]
Hola, no emite por Internet, así que no es posible.

**Comment by Hiruzulo** [comment]
Hola,
Si, yo tengo AgileTV y lo puedo ver (no tengo ningun paquete contratado solo veo los canales libres). Lo que queria era quitarme AgileTV y poner una android TVbox libre.
Gracias
Saludos
Mikel

    En lunes, 24 de mayo de 2021 23:41:46 CEST, Marc Vila ***@***.***> escribió:  
 
 


Hola, no emite por Internet, así que no es posible.

**Comment by LaQuay** [comment]
Hola de nuevo, si no emiten de forma oficial y en su propia página web, no podemos añadirlo. Si tienes el enlace dónde se emite este canal, envíanoslo y lo revisamos. En caso contrario, no se puede. Gracias.
