### ISSUE TITLE
Canal no funciona: Bit FM Pamplona

### ISSUE THREAD

**Issue by jonsaenz21** [LaQuay/TDTChannels#1535]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
https://www.bitfm.es/bitfm/
<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://www.bitfm.es/bitfm/

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
Lleva semanas sin funcionar, la emisora ha echado el cierre ahora en fm y por internet.
MÁS INFORMACIÓN:  http://guiadelaradio.com/la-crisis-por-el-covid-19-obliga-al-cierre-de-bit-fm-de-pamplona

**Comment by adrianpaniagualeon** [comment]
Es un problema de la emisora. Hasta que no vuelvan a emitir, no se puede hacer nada

**Comment by LaQuay** [comment]
Gracias por el aviso, la borramos!
