### ISSUE TITLE
Canal no funciona: Telecinco

### ISSUE THREAD

**Issue by Manuelmorenodj** [LaQuay/TDTChannels#1547]
Hola buenas noches.
Llevo varias semanas intentando acceder a Telecinco y es imposible, no llega a cargar nunca.
Un saludo y gracias.
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by LaQuay** [comment]
Hola, la emisión no depende de nosotros. Puedes revisar https://t.me/tdtchannels/98264 para ver si encuentras solución. Gracias!
