### ISSUE TITLE
Más canales

### ISSUE THREAD

**Issue by playzzz** [LaQuay/TDTChannels#16]
Hoy un compañero mío me ha pasado este archivo m3u que tiene muchísimos canales, de pago (#0, M+, etc) u otros que no tienes como FDF, Energy, etc.
¡Aquí te dejo el link al archivo!
https://www.iptv4sat.com/download-attachment/itD7Nl1yxIQAgMz5tGOyF4tnx4pHZAydtoSGGeY9P34,

**Comment by paurg15** [comment]
Vale, no problem!
