### ISSUE TITLE
Añadir Radio:LOS40 Coruña

### ISSUE THREAD

**Issue by Gabriel44200** [LaQuay/TDTChannels#1616]
Su enlace es el siguiente: http://radiocoruna.lcinternet.com:9300/stream
La fuente del enlace es su twitter: https://twitter.com/40coruna
Su logo es este: https://graph.facebook.com/40PrincipalesCoruna/picture?width=200&height=200

**Comment by LaQuay** [comment]
Hola, hay un mecanismo de petición de canales, por favor, haced uso:
tdtchannels.com/peticion

Gracias!
