### ISSUE TITLE
NORTEvision

### ISSUE THREAD

**Issue by kanetaker** [LaQuay/TDTChannels#164]
Hola hace un tiempo me puse en contacto contigo para que añadieses a tu lista de canales, el canal nortevision de gran canaria, veo que tambien has añadido no solo el formato m3u8, o m3u, sino el bouquet para la lista de canales de los enigmas 2, te dejo la direccion y el formato del archivo para que lo conviertas para el bouquet del enigma2, y tambien para el formato m3u, te puedo pasar el archivo por correo si quieres para que lo puedas visualizar, si me dejas algun correo claro. Contenido del archivo m3u, m3u8. Un saludo

#EXTM3U 
#EXTVLCOPT--http-reconnect=true
#EXTINF:-1,NORTEvision UHD
#EXTVLCOPT:program=33
http://amaru.dyndns.org:8001/1:0:1:21:1:22D4:EEEE0000:0:0:0:

**Comment by LaQuay** [comment]
Hola @kanetaker,
No añadí la versión que enviaste por que no logré encontrar la fuente de datos, es decir, la página web oficial. Tu la tienes? De esta forma lo añadiría.

Gracias!

**Comment by kanetaker** [comment]
No hay pagina web de la tv, lo unico que podrias hacer es meter los datos
previa conversion al bouquet para los decos enigmas2

**Comment by LaQuay** [comment]
Lo siento, pero no encuentro referencias de la web oficial, ni referencia alguna para encontrar dicho enlace. Así que cierro la issue hasta que se sepa de donde sale el enlace. Gracias!
