### ISSUE TITLE
Lista unificada de TV y Radio

### ISSUE THREAD

**Issue by malomehi** [LaQuay/TDTChannels#169]
Seria posible tener una lista unificada con los canales de TV y Radio?
De esa forma seria posible usarla con `IPTV Simple Client` en Kodi que solo permite una lista, no permite multiples listas.
En el addon uso la url que apunta a la lista de TV con lo que siempre esta actualizada, pero si quisiera tener TV y Radio tendria que manualmente descargar ambas y unirlas en un solo archivo cada vez que se actualizan.

Gracias.

**Comment by LaQuay** [comment]
Hola,
Puedo mirar de dar la posibilidad de generar la lista unida. Pero no me acaba de gustar la idea por que unirlas no es nada en sí, ni TV ni RADIO. Si no, una mezcla de ambas... Le doy una vuelta.

**Comment by malomehi** [comment]
Gracias por echarle un ojo.
Yo uso este addon en kodi: https://kodi.wiki/view/Add-on:IPTV_Simple_Client
Segun la documentacion usando el flag `radio` se puede distinguir un canal como canal de radio y entiendo que kodi mostraria los canales por separado en la seccion TV y la seccion Radio respectivamente. Si me da tiempo puedo probarlo manana mezclando algunos canales en una lista unica y ver como los muestra y te cuento.

**Comment by LaQuay** [comment]
@malomehi OK! Comenta si con el tag radio funciona. Podríamos probarlo.

**Comment by malomehi** [comment]
@LaQuay He hecho algunas pruebas y he conseguido que funcione separando los canales de TV y radio.
Los canales de radio necesitan incluir el flag `radio="true"` y ademas deben incluir un `group-title` siempre que no exista ya en los canales de TV. Esta es la lista de pruebas que me ha funcionado:
```
#EXTM3U @LaQuay https://github.com/LaQuay/TDTChannels
#EXTM3U url-tvg="https://raw.githubusercontent.com/HelmerLuzo/TDTChannels_EPG/master/TDTChannels_EPG.xml"
#EXTINF:-1 tvg-id="La1.TDTChannelsEPG" tvg-logo="https://pbs.twimg.com/profile_images/899385012801470464/akSvNCqE_400x400.jpg" group-title="Generalistas",La 1 HD
http://hlsliveamdgl1-lh.akamaihd.net/i/hlsdvrlive_1@584096/master.m3u8
#EXTINF:-1 tvg-id="Antena3.TDTChannelsEPG" tvg-logo="http://graph.facebook.com/antena3/picture?width=320&height=320" group-title="Generalistas",Antena 3 HD
https://livestartover.atresmedia.com/geoantena3/master.m3u8
#EXTINF:-1 tvg-logo="http://graph.facebook.com/radionacionalrne/picture?width=320&height=320" group-title="Otro" radio="true",Radio Nacional
http://hlsliveamdgl0-lh.akamaihd.net/i/rnerne_1@586398/master.m3u8
#EXTINF:-1 tvg-logo="http://graph.facebook.com/radio3/picture?width=320&height=320" group-title="Otro" radio="true",Radio 3
http://hlsliveamdgl0-lh.akamaihd.net/i/rnerne3_1@793568/master.m3u8
#EXTINF:-1 tvg-logo="https://pbs.twimg.com/profile_images/1107968053491453952/k4W17qFC_400x400.png" group-title="Otro" radio="true",Radio 5
http://hlsliveamdgl0-lh.akamaihd.net/i/rnerne5_1@793570/master.m3u8
```
Si el `group-title` de uno de los canales de radio fuese `Generalistas` no funcionaria porque ya existe para canales de television entonces ese canal te lo mete como canal de television en vez de radio.

**Comment by malomehi** [comment]
Ademas:
```
group-title
    Group name for user defined collection of channels.
    If missing from the M3U file, the addon will use the group name from the previous channel.
```
Es decir, si no incluimos el `group-title` en un canal se le asigna el del ultimo canal anterior que lo tuviese, sin distinguir entre TV y radio. Por lo que es absolutamente necesario en una lista unificada o si no mezclaria canales de TV y radio de manera incorrecta.

**Comment by LaQuay** [comment]
Gracias @malomehi. En unos días añadiré pues el flag de radio para las radios 👍

**Comment by tito765** [comment]
Hola! Como se descargan las listas. Estoy muy perdida. Gracias

**Comment by wimiti** [comment]
Hola:
Yo también uso _IPTV Simple Client_ en _Kodi_ y, lo que suelo hacer para que me aparezcan los canales de TV y rádio es, bajar los ficheros `.m3u8` de ambos y juntarlos (a pinón) en un `all_channels.m3u8` (primero TVs y luego Radios) que dejo caer en el directorio de trabajo de Kodi. Desde la configuración del add-on lo referencio como fichero local y accedo a ellos teniendo en cuenta que, por ejemplo en los generalistas, aparecen con número bajo las TVs y con número alto (tres dígitos noemalmente) las Radios.
Al leer este issue he añadido lo de `radio="true"` como indicas @malomehi  manteniendo el `group-title` como esté, en los canales de Radio sobre el fichero de todos los canales que genero y desde el add-on no veo diferencia.
Espero que mi comentario sirva de algo y si creéis que puedo hacer alguna prueba más indicádmelo y lo comentamos.
Saludos.

**Comment by OrAhuManu** [comment]
> Gracias @malomehi. En unos días añadiré pues el flag de radio para las radios 👍

¿Al final que pasó?

**Comment by David-cp** [comment]
Si el problema esque el group-title no puede ser el mismo para tv y radio, a lo mejor la solucion es que los grupos se nombren formato "Generalista_Radio"

**Comment by malomehi** [comment]
Yo desde hace un tiempo la unifico yo mismo con un cron job en cada reinicio.
Hago algo asi:
```
test -e channels.m3u8 && mv channels.m3u8 channels.m3u8.bak
wget http://www.tdtchannels.com/lists/channels.m3u8
wget http://www.tdtchannels.com/lists/radio_channels.m3u8
sed -i -r 's/group-title="([^"]*)"/group-title="\1 Radio"/g' radio_channels.m3u8
sed -i 's/,/ radio="true",/g' radio_channels.m3u8
cat radio_channels.m3u8 >> channels.m3u8
rm radio_channels.m3u8
```

Evidentemente cada cual tendra que poner las rutas correctas, etc. Pero en esencia es una solucion valida.

**Comment by LaQuay** [comment]
Buenas, al final lo descarté. El tema del `group-title` me genera mucho trabajo a realizar para tener como único objetivo la unificación de las listas.

Con únicamente el flag de radio se ganaría algo? Eso si que podría hacerlo.

**Comment by LaQuay** [comment]
Hola! Ya está! Ya tenéis las listas unificadas. A disfrutarlas!
https://github.com/LaQuay/TDTChannels/blob/master/README.md#listas-de-reproducci%C3%B3n
