### ISSUE TITLE
App

### ISSUE THREAD

**Issue by playzzz** [LaQuay/TDTChannels#17]
Hola!

Hoy no tenía nada a hacer y he aprovechado para hacer este boceto para una app con tus enlaces IPTV. Tiene un diseño inspirado en el Material Theming que presentó recientemente Google. Lo puedes aquí: https://drive.google.com/folderview?id=11CQC3TciiZgtT2xIAolNqArJT7lGegtf

**Comment by LaQuay** [comment]
@paurg15 Gracias! Está bastante chulo 👍 
Por cierto, la barra inferior también está en Material Theming? 
Ando mirando por que diría que Google no era partidario de esos menús flotantes en apps no?

**Comment by paurg15** [comment]
Siii, solo que los menús flotantes tienen que estar incluidos en la barra inferior. Aquí hay un montón de ejemplos:
https://www.androidauthority.com/material-theming-863737/
https://www.fastcodesign.com/90171179/exclusive-meet-material-theming-googles-ambitious-design-tool

**Comment by paurg15** [comment]
@LaQuay Añadí más contenido a la carpeta de Google Drive, solo me faltaría hacer la plantilla de algunos canales más, hacer un diseño diferente que tengo pensado y ya estaría todo.
PD: Seguirás usando Github después de lo de Microsoft?

**Comment by LaQuay** [comment]
Voy siguiendo lo que haces, está muy bien! 
Pero tengo 0 tiempo para hacer una app ahora mismo :(

Sigo en Github, si 👍

**Comment by paurg15** [comment]
Gracias por el seguimiento!

No problem! De momento voy tirando con las apps oficiales (y su publi que parece no acabar nunca) y por el trabajo aún tengo que solucionar detalles como proporciones o logos pixelados...

**Comment by LaQuay** [comment]
@paurg15 Hola! Estoy sin tiempo por trabajos y otros proyectos en general, así que de momento no estoy desarrollando la aplicación, pero es algo que quiero mirar de hacer a corto plazo.

**Comment by LaQuay** [comment]
👏 
Gracias por el dato de Antena3 Champions, ahora lo saco 👍
