### ISSUE TITLE
Allowing other apps to reduce TDTChannels volume

### ISSUE THREAD

**Issue by victorjagu** [LaQuay/TDTChannels#1763]
Hello there,

First of all, thank you so much for developing this awesome app. I really appreciate it.

On the other hand, I use this app a lot, but when I use it in the radio mode when I'm doing my workout, the app that I use can't reduce the volume of TDTChannels, so I can hear the instructions properly.

Is there a way to implement that feature or perhaps it's a bug in the workout app that I used? (It works well with my music player but who knows).

Thank you and best regards
Victor

**Comment by LaQuay** [comment]
Hi Victor,
Yes, as you mention, this thing you are reporting is a bug. I have already seen that some weeks ago. I have this thing noted down in my agenda. I will try to fix it.

Cheers

**Comment by victorjagu** [comment]
Hi Marc,
Thank you so much. If I can help with some checks or something, let me know.
Cheers,
Victor
En 10 de octubre de 2021 12:02:55 Marc Vila ***@***.***> 
escribió:

**Comment by LaQuay** [comment]
Hi @victorjagu , you can find this feature available in our last release for the Android app https://www.tdtchannels.com/android
