### ISSUE TITLE
Mirrors de Cuatro y Telecinco

### ISSUE THREAD

**Issue by saidma** [LaQuay/TDTChannels#18]
https://livehlsdai-i.akamaihd.net/hls/live/571643/cuatro/bitrate_1.m3u8

https://livehlsdai-i.akamaihd.net/hls/live/571640/telecinco/bitrate_1.m3u8

BEMAD, Boin, Energy y Divinity 
https://mdslivehlsb-i.akamaihd.net/hls/live/623615/bemad/bitrate_4.m3u8

https://mdslivehlsb-i.akamaihd.net/hls/live/623616/boing/bitrate_4.m3u8

https://mdslivehlsb-i.akamaihd.net/hls/live/623617/energy/bitrate_4.m3u8

https://mdslivehls-i.akamaihd.net/hls/live/571648/divinity/bitrate_1.m3u8

Las url caducan cada cierto tiempo

**Comment by LaQuay** [comment]
Hola!
Es el problema, caducan cada poco tiempo, tendríamos que ver si tardan mucho en caducar o si tardan semanas... Si es el primer caso, casi que no vale la pena poner el m3u8...
Gracias!

**Comment by danifr** [comment]
Hola,

tenía el mismo problema pero he encontrado un blog que postea de forma regular un archivo con los enlaces a directos actualizado. Lo estoy usando ahora mismo para ver CuatroHD y funciona de PM.

**Comment by danifr** [comment]
Hola, me temo que no eran legales :( en la lista de canales había varios de pago y el de CuatroHD dejó de funcionar a las 24h. Sigo buscando alguna solución mejor.
Gracias!!!
