### ISSUE TITLE
Añadir Cetelmon TV

### ISSUE THREAD

**Issue by telefrancisco** [LaQuay/TDTChannels#1826]
Su web es: https://www.cetelmon.tv/

Se trata de un Canal de tipo Religioso (si bien es original de Alicante, la programación es de tipo religioso por completo, según se puede ver en: https://www.cetelmon.tv/index.php/programas/parrilla-de-programacion/itemlist/date/2021/10/21?catid=13).

En su web disponen de un enlace para ver el canal (http://player.cetelmon.tv/index.html) en el cual se hace referencia a esta URL:
http://player.cetelmon.tv/protecteddfd43c2f3a8b41f3f28582bf8993aca6/992_low.m3u8

si bien también funciona cambiando el "low" por "high", lo que quizás sea más apropiado para incluir aquí.
http://player.cetelmon.tv/protecteddfd43c2f3a8b41f3f28582bf8993aca6/992_high.m3u8

O quizás se pueda contactar con ellos por si tienen algún enlace mejor: https://www.cetelmon.tv/index.php/cetelmon-tv

**Comment by LaQuay** [comment]
Añadida, gracias!
