### ISSUE TITLE
Neox, Nova, Mega and Atreseries are down

### ISSUE THREAD

**Issue by malvinas2** [LaQuay/TDTChannels#183]
Hello, 

Neox, Nova, Mega and Atreseries are down, geo as well as normal version. 

(aparte de eso es un proyecto estupendo!)

**Comment by LaQuay** [comment]
Hola!
I see that you are trying to access from Germany? Reproducing them via our website (marcvila.me/tdt) or via VLC or... ?

Thanks

**Comment by malvinas2** [comment]
Hello, 
via VLC, but just right after 'clicking' on the corresponding m3u8-link I get an 404-error, while the other links are opened by VLC. (streamlink obviously neither works because of the missing m3u8-file). 

Y si, lo estoy accediendo desde Alemania. Primero he usado un VPN, pero tus links sin ser 'geo-bloquedao' andan super-bien.

**Comment by playzzz** [comment]
Si vives fuera de España solo puedes utilizar los enlaces que NO son GEO, por lo cual si emiten por ese enlace bien, tienen los derechos para emitir globalmente lo que estén emitiendo (series, películas, etc...).

Pero lo normal e estos canales que son temáticos y su programación se basa en series y películas casi solo emiten por el enlace GEO, y solo para España porque los derechos de imagen son más baratos si solo son para un país que para cientos (globalmente).

**Comment by malvinas2** [comment]
Ustedes han verificado si funcionan dichos canales? Porque ni siquiera se encuentra el m3u8, el fichero simplemente no existe. 
Al fin de Junio he installado un VPN (Hidemyass) como prueba gratuita de 7 días y andaba muy bien - pude ver todos los canales de Espania, la Argentina y el Perú. Tambien fue possible ver los canales Neox, Nova, Mega and Atreseries usando el link de su pagina web official y streamlink. Pero los links mencionado aqui nunca han funcionado. Sin o con geoblocking, sin o con VPN...

**Comment by playzzz** [comment]
Los canales funcionan perfectamente y están incluidos en el m3u8, desde España funcionan y estar tienen que estar en el m3u8, vamos eso es inpeninable 😂

**Comment by malvinas2** [comment]
Finally I bought an account for a VPN and the geoblocked links of Neox, Nova, Mega and Atreseries are working now, but just with Streamlink. It is not possible to open them directly via VLC. 
In opposite to the other channel links these four are using hlsvariant, where the stream describes a list of different qualities (variants) for the same stream, not a single hls which is used when the stream is a direct link to one of those variants. 
(would have been nice to have direct links, because of the faster switch time when you change between channels)

**Comment by playzzz** [comment]
It is very difficult to add the direct links of each finish because we would have to multiply each channel by 4, one for each variant.
