### ISSUE TITLE
En radio no funciona ninguna de la tres de Aragón radio

### ISSUE THREAD

**Issue by rmonitor** [LaQuay/TDTChannels#186]

**Comment by playzzz** [comment]
Ya se ha enviado una Pull Request arreglándolo, en cuanto se actualice la lista ya tendrás disponibles las emisoras.

**Comment by Diego586894** [comment]
playzzz, alguien me puede conseguir el m3u8 de Navarra Tv

**Comment by playzzz** [comment]
No, su m3u8 depende de la iP de cada dispositivo en el que se reproduzca.
