### ISSUE TITLE
Pause button at Radio channels doesn't work.

### ISSUE THREAD

**Issue by luisvalino** [LaQuay/TDTChannels#1861]
Hi, pause button at radio fm channels doesn't work.

**Comment by luisvalino** [comment]
El botón de pausa en las diferentes emisoras de radio que tengo no funciona. Trato de hacer pausa en una retransmisión de radio y no funciona, antes este botón si funcionaba pero ahora no.

**Comment by LaQuay** [comment]
Se solucionó. Si te sigue ocurriendo, escríbe de nuevo. Gracias
