### ISSUE TITLE
Canales no funcionan: la sexta y goltv

### ISSUE THREAD

**Issue by ruber81** [LaQuay/TDTChannels#1879]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
Antes funcionaban y han dejado funcionar (fuente no disponible)

**Comment by LaQuay** [comment]
Hola, siguen funcionando.

**Comment by ruber81** [comment]
Aún no...
