### ISSUE TITLE
Canal Trece no funciona

### ISSUE THREAD

**Issue by stef85271** [LaQuay/TDTChannels#1896]
Me parece que la Trece ya no funciona. E encontrado la nueva url para el stream de la Trece. Es esta 👍 

https://live-edge-lon-1.cdn.enetres.net/091DB7AFBD77442B9BA2F141DCC182F5021/liveld/index.m3u8

**Comment by LaQuay** [comment]
Hola, este enlace apunta al mismo sitio que el que tenemos aquí, funcionando desde Agosto 2020. Saludos!
