### ISSUE TITLE
Emisoras de radio

### ISSUE THREAD

**Issue by BeeTV** [LaQuay/TDTChannels#19]
Como no me permite añadir un archivo m3u, voy subiendo en modo texto:

#EXTM3U
#EXTINF:0 radio="true", RAC1
http://streaming3.radiocat.net
#EXTINF:0 radio="true", RAC105
http://streaming105.radiocat.net
#EXTINF:0 radio="true", LOS40
http://19983.live.streamtheworld.com/LOS40_SC
#EXTINF:0 radio="true", KISS FM
http://kissfm.kissfmradio.cires21.com/kissfm.mp3
#EXTINF:0 radio=true, LOCA FM
http://audio-online.net:2300/live

**Comment by LaQuay** [comment]
Gracias!
Estoy pensando si hacer otro repositorio solo para ràdios, siguiendo el estilo de este. O mantener este mismo con otro apartado...

Me lo planteo! 👍

**Comment by usuarionuevor** [comment]
Si puedes hacerlo en otro apartado dentro de este mismo repositorio… de lujo!

dejo algunas de electronica:

pioneer radio
http://listen.pioneerdjradio.com:8550/stream

beach grooves
http://stream.beachgrooves.com:8000/stream

ibiza global radio
http://ibizaglobalradio.streaming-pro.com:8024/stream

radio planeta
http://5.79.66.113:8004/stream

maxima fm
https://19393.live.streamtheworld.com/MAXIMAFMAAC.aac

**Comment by LaQuay** [comment]
@BeeTV @usuarionuevor Añadidas, gracias!

**Comment by usuarionuevor** [comment]
Un pequeño detalle, **Beach Grooves** está en la categoría **Internacional** pero es una emisora Española, concretamente de Marbella, la confusion creo que viene porque a veces ponen anuncios en inglés para los guiris de por allí.

**Comment by LaQuay** [comment]
@usuarionuevor Corregido, gracias!
