### ISSUE TITLE
Teledeporte access denied

### ISSUE THREAD

**Issue by UV93** [LaQuay/TDTChannels#190]
Hello,

When trying to open any teledeporte link I got the message 'Access denied' or forbidden. 
Is it because it is GEO blocked (at least it does not say so in the table) or because it is down?
Trying to access from UK.

Thanks.

**Comment by LaQuay** [comment]
Hi!
It is working by now. Can you try again?

Maybe it is GEO as you say... Let's confirm it.
Thanks!

**Comment by UV93** [comment]
Hi,

Thanks for your reply. 

Still getting access denied .
"You don't have permission to access "http://hlsliveamdgl1-lh.akamaihd.net/i/hlsdvrlive_1@39732/master.m3u8" on this server.
Reference #18.a7f6ffb0.1563378103.36d65b1d "
So probably it is GEO.

Cheers

**Comment by LaQuay** [comment]
Added as GEO, thanks!
