### ISSUE TITLE
Betis tv HD?

### ISSUE THREAD

**Issue by raul937** [LaQuay/TDTChannels#195]
Hola, que ha pasado con Betis Tv? Antes, si no me equivoco, se veía en hd y ahora en sd. Volverá a verse como antes?
Un saludo

**Comment by playzzz** [comment]
La resolución del canal depende del club, llevan meses cambiando la resolución de HD->SD y SD->HD porque sí.

Así que será más efectivo que te pongas en contacto con el club para saber la razón de los cambios de resolución.
