### ISSUE TITLE
CodeRadio - Sugerencia

### ISSUE THREAD

**Issue by jEsuSdA** [LaQuay/TDTChannels#196]
Sugiero incluir CodeRadio, una radio online con música de fondo para programar (o cualquier otra tarea que requiera concentración frente a la pantalla y música que ayude y no moleste)

https://coderadio.freecodecamp.org/

Link directo al flujo MP3
https://coderadio-admin.freecodecamp.org/radio/8010/low.mp3

cheers!!! ;)

**Comment by CGarces** [comment]
@jEsuSdA Anímate y manda un pull request.
Solo tienes que modificar el fichero https://github.com/LaQuay/TDTChannels/blob/master/RADIO.md
Coje como ejemplo melodia FM.

Al ser un cambio sencillo, puedes hacerlo incluso via web.

**Comment by jEsuSdA** [comment]
@CGarces hecho! (creo que lo he hecho bien, ya me cuentas) ;)

**Comment by LaQuay** [comment]
@CGarces @jEsuSdA Gracias a ambos!
