### ISSUE TITLE
INTERCOMARCAL TV

### ISSUE THREAD

**Issue by Diego586894** [LaQuay/TDTChannels#198]
Porque el Canal INTERCOMARCAL TV no se puede ver?? Alguien me lo puede explicar o Solucionarlo??

**Comment by LaQuay** [comment]
> Porque el Canal INTERCOMARCAL TV no se puede ver?? Alguien me lo puede explicar o Solucionarlo??

Diego, se te ha contestado esta duda varias veces. La última vez ayer noche.
https://github.com/LaQuay/TDTChannels/issues/193
