### ISSUE TITLE
CNN

### ISSUE THREAD

**Issue by mierdaredonda** [LaQuay/TDTChannels#199]
No funciona CNN en español

**Comment by malvinas2** [comment]
Lo que pasa es que los de CNN son unos boludos, solo emiten su senial en Venezuela, nada mas. 
Usando un VPN el siguiente link funciona: 
[https://cnn-lh.akamaihd.net/i/cnne_1@194775/master.m3u8](https://cnn-lh.akamaihd.net/i/cnne_1@194775/master.m3u8)

(un milagro que todavia existen servidores en Caracas, Venezuela ...  ?!?!

**Comment by malvinas2** [comment]
https://turnerlive.akamaized.net/hls/live/2006634/cnne_atl/master.m3u8

**Comment by malvinas2** [comment]
Ahora estan usando el YouTube, pero aun se necesita un VPN: 
[https://www.youtube.com/channel/UC_lEiu6917IJz03TnntWUaQ](https://www.youtube.com/channel/UC_lEiu6917IJz03TnntWUaQ)
