### ISSUE TITLE
Canal Cuatro señal intermitente

### ISSUE THREAD

**Issue by Pikaxtron** [LaQuay/TDTChannels#1992]
Buenas el canal de cuatro pierde la señal cada unos pocos segundos (20+-) se pone la pantalla en negro y después vuelve, alguna solución?

**Comment by LaQuay** [comment]
Hola, nosotros no emitimos. Igualmente, supongo que estás refiriendote a la app, si es así, prueba en ajustes a deshabilitar el refresco automático.
