### ISSUE TITLE
Dividir pantalla no funciona

### ISSUE THREAD

**Issue by javierlqp** [LaQuay/TDTChannels#1997]
En Android 11, oneplus nord n10 5G, al dividir pantalla, el lado de TDTChannels se escucha pero la imagen se queda en la pantalla de "cargando".

**Comment by LaQuay** [comment]
Hola @javierlqp , puedes confirmar si te sigue ocurriendo? Gracias

**Comment by javierlqp** [comment]
Buenos días Marc,

Ya no me ocurre, funciona estupendamente. Muchas gracias, saludos.
