### ISSUE TITLE
Link FDF

### ISSUE THREAD

**Issue by Artuotpz** [LaQuay/TDTChannels#2]
Era solo para saber si el link de FDF no funciona o hago algo mal ya que sigo los pasos de SoftZone y no consigue abrirlo en VLC

**Comment by LaQuay** [comment]
Los canales de Mediaset suelen cambiar bastante rápido de URL. Ya lo he corregido, debería irte :)

**Comment by Artuotpz** [comment]
Correcto, muchas gracias por la rapidez, una pregunta más es muy difícil de conseguir estos links?
Lo digo por conseguir yo el de FDF para no estar preguntándolo todo el rato, sino, tampoco pasa nada.
Gracias de antemano

**Comment by LaQuay** [comment]
De nada! Pues mirando la web y sacando los enlaces a mano...

Cuando no te vaya, comentalo por aquí y lo soluciono, como hoy 👍
