### ISSUE TITLE
Mundial, Mediaset y mitele

### ISSUE THREAD

**Issue by paurg15** [LaQuay/TDTChannels#20]
Podrías aprovechar el mundial e intentar sacar el m3u8 de este streaming [https://www.mitele.es/directo/futbol-mitele](url) para ver en el mundial en un solo sitio y no tener que cambiar nunca de canal.

Gracias de antemano y felicidades por este trabajo que estás haciendo!!

**Comment by Gerilp02** [comment]
https://mdslivehlsb-i.akamaihd.net/hls/live/623620/live02/master.m3u8?hdnea=st=1529619220~exp=1529619228~acl=/hls/live/623620/live02/*~hmac=0c8433f545cecf7bd80f8a776b99a945c6f8bde43a3412e49c2062b413ba35e0

**Comment by axopoulos** [comment]
Cuatro y  Tele5 conectan, pero se ve negro. Esto sucede desde el partido Nigeria Islandia de hoy y no ha vuelto.
Salu2

**Comment by LaQuay** [comment]
Parece ser que cada 2 días o así van cambiando de m3u8... Así difícil será mantener algo funcionando :(

**Comment by axopoulos** [comment]
bueno, te agradezco el gran trabajo de todas formas!!

**Comment by adamo331** [comment]
han agregado algunas restricciones a las transmisiones (cuatro) y (telecinco) puedo obtener la línea m3u8 pero ya no me puedo conectar en VLC ni en ninguna otra plataforma

cualquiera aquí puede proporcionar más información

**Comment by LaQuay** [comment]
@adamo331 Estamos todos igual, parece que le han puesto una capa por encima que te obliga a entrar por navegador...
