### ISSUE TITLE
DELUXE MUSIC

### ISSUE THREAD

**Issue by mierdaredonda** [LaQuay/TDTChannels#200]
Deluxe music no funciona.
A ver si se pudiera ordenar de alguna manera los canales. Que se queden abajo los que no funcionan o que la lista se ordene automáticamente por canales que más usamos.

**Comment by malvinas2** [comment]
Hoy el enlace funciona. Probablemente el servidor estuvo desconectado. 
Hay que usar streamlink para abrir el enlace.

**Comment by LaQuay** [comment]
@mierdaredonda Es un canal que no emite siempre, solo ciertos momentos del tiempo.
