### ISSUE TITLE
Gol TV

### ISSUE THREAD

**Issue by corderop** [LaQuay/TDTChannels#202]
Buscando canales que suelo ver, me he percatado de que no está Gol TV. Actualmente estoy usando el enlace http://91.121.64.179/tdt_project/output/channels.m3u8. No se si será por algún tema de derechos o algo por el estilo.

**Comment by josemixemi** [comment]
No creo que sea por derechos, ya que es en abierto y se supone que siendo en abierto los derechos estan pagados. Yo uso la app dela AppleTV TDT España y tambien estoy interesado en ver Gol, si alguien sabe algo...

**Comment by LaQuay** [comment]
Ahora ya sí. https://github.com/LaQuay/TDTChannels/commit/cc1f883d13b07209ff62590a940b1fd6bdfa7383
