### ISSUE TITLE
NORTEvision gran canaria ya tiene web

### ISSUE THREAD

**Issue by kanetaker** [LaQuay/TDTChannels#203]
Hola buenos dias decirte de que nortevision ya tiene web en donde transmite la señal en directo por si te interesa es http://nortevision.es  saludos.

**Comment by HelmerLuzo** [comment]
http://ad.mysisli.com/live/aljoamy/tracks-v1a1/mono.m3u8

**Comment by LaQuay** [comment]
Añadido, gracias!
https://github.com/LaQuay/TDTChannels/commit/1acf2dbc17e746350e81828ea5a64676b6378b98
