### ISSUE TITLE
Gol Television no se ve

### ISSUE THREAD

**Issue by josemixemi** [LaQuay/TDTChannels#204]
Accedo a la lista de canales a través de una app que compré para el Apple TV. se ven todos los nacionales, o casi todos, pero GOL siempre pone, "no disponible inténtelo más tarde"... Si alguien sabe por qué pasa esto y me ayuda a solucionarlo.... Gracias.

**Comment by LaQuay** [comment]
Gol TV por el momento no está en la lista.

Duplicado de: https://github.com/LaQuay/TDTChannels/issues/202
