### ISSUE TITLE
Canal no funciona: Varios

### ISSUE THREAD

**Issue by namelivia** [LaQuay/TDTChannels#2052]
He escrito un script para testear los canales de la lista, si el repositorio sigue mantenido e interesa podría integrar algunos scripts para hacer alguna de estas cosas automáticamente.

Ahora mismo estos son los que están dando error y el tipo de error.

| URL | Error |
| --- | --- |
| https://live.gooru.live/negocios/live.m3u8 | HTTP Error 404: Not Found |
| https://cartv.streaming.aranova.es/hls/live/adeportes_deporte1.m3u8 | HTTP Error 404: Not Found |
| https://cartv.streaming.aranova.es/hls/live/adeportes_deporte2.m3u8 | HTTP Error 404: Not Found |
| https://cartv.streaming.aranova.es/hls/live/adeportes_deporte3.m3u8 | HTTP Error 404: Not Found |
| https://rfef-live3.flumotion.com/playlist.m3u8 | HTTP Error 404: Not Found |
| https://hlsliveamdgl1-lh.akamaihd.net/i/hlslive_1@125699/master.m3u8 | HTTP Error 400: Bad Request |
| https://hlsliveamdgl1-lh.akamaihd.net/i/hlslive_1@125702/master.m3u8 | HTTP Error 400: Bad Request |
| https://hlsliveamdgl1-lh.akamaihd.net/i/hlslive_1@125698/master.m3u8 | HTTP Error 400: Bad Request |
| https://hlsliveamdgl1-lh.akamaihd.net/i/hlslive_1@143656/master.m3u8 | HTTP Error 400: Bad Request |
| https://hlsliveamdgl1-lh.akamaihd.net/i/hlslive_1@125703/master.m3u8 | HTTP Error 400: Bad Request |
| https://livestartover.atresmedia.com/eventos15/master.m3u8 | HTTP Error 401: Unauthorized |
| https://livestartover.atresmedia.com/eventos26/master.m3u8 | HTTP Error 401: Unauthorized |
| https://livestartover.atresmedia.com/eventos37/master.m3u8 | HTTP Error 401: Unauthorized |
| https://cdnswitch-mediahub.overon.es/stream/stream.m3u8 | <urlopen error [Errno 110] Connection timed out> |
| https://cdnswitch-mediahub.overon.es/stream/stream.m3u8 | <urlopen error [Errno 110] Connection timed out> |
| https://hls-directo02-cope-stream.flumotion.com/cope/directo02/playlist.m3u8 | HTTP Error 404: Not Found |
| https://limited2.todostreaming.es/live/m95-livestream.m3u8 | HTTP Error 404: Not Found |
| https://cdn01.yowi.tv/503L6OKTE2/master.m3u8 | HTTP Error 404: Not Found |
| https://5fa5de1a545ae.streamlock.net/TVCENTRO/TVCENTRO/master.m3u8 | HTTP Error 404: Not Found |
| https://cloud.streamingconnect.tv:455/mezquita/mezquita.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://5940924978228.streamlock.net/8431/8431/playlist.m3u8 | HTTP Error 404: Not Found |
| https://www.tdtchannels.com/stream/saltv.m3u8 | HTTP Error 404:  |
| https://5924d3ad0efcf.streamlock.net/cordoba/cordobalive/playlist.m3u8 | HTTP Error 404: Not Found |
| https://ondacadiztv.es:30443/octv/24h/playlist.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://ztnr.rtve.es/ztnr/5190066.m3u8 | HTTP Error 403: Unauthorized |
| https://ztnr.rtve.es/ztnr/5468585.m3u8 | HTTP Error 403: Unauthorized |
| https://5940924978228.streamlock.net/Directo3/Directo3/playlist.m3u8 | HTTP Error 404: Not Found |
| https://tvdatta.com:3785/live/biosferatvlive.m3u8 | HTTP Error 404: Not Found |
| https://limited12.todostreaming.es/live/ptvcantabria-livestream.m3u8 | HTTP Error 404: Not Found |
| https://cloud.streamingconnect.tv:455/guadatv/guadatv.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://cloud.streamingconnect.tv:455/manzanares/manzanares.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://cloud.streamingconnect.tv:455/teletoledo/teletoledo.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://cloud.streamingconnect.tv:455/tvbenavente/tvbenavente.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://16escalones-live2.flumotion.com/chunks.m3u8 | HTTP Error 404: Not Found |
| https://ztnr.rtve.es/ztnr/4952053.m3u8 | HTTP Error 403: Unauthorized |
| https://liveingesta118.cdnmedia.tv/canaltetvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/canaltetvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/canalreustvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/canalreustvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/9tvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/9tvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/empordatvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/empordatvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/badalonatvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/badalonatvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/canalterrassatvlive/smil:canalterrassatv.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/canalterrassatvlive/smil:canalterrassatv.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/canal21ebrelive/smil:canal21.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/canal21ebrelive/smil:canal21.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/lleidatvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/lleidatvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/costabravatvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/costabravatvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/vsnxallive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/vsnxallive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/olottvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/olottvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/blautvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/blautvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/taronjacentrallive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/taronjacentrallive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/tvhospitaletlive/smil:tvhospitalet.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/tvhospitaletlive/smil:tvhospitalet.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/berguedatvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/berguedatvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/tvvendrelllive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/tvvendrelllive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/taronjaanoialive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/taronjaanoialive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/votvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/votvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/m1tvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/m1tvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/rtvvilafrancalive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/rtvvilafrancalive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/cardedeutvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/cardedeutvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/vallesvisiotvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/tvripolleslive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/tvripolleslive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/etvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/etvlive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/tvsabadelllive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/tvsabadelllive/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/tvstestevelive/smil:tele.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/tvstestevelive/smil:tele.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://secure.todostreaming.es/live/anguloce-livestream.m3u8 | HTTP Error 404: Not Found |
| https://live.yowi.tv/1314e346aedca6930f48/master.m3u8 | HTTP Error 404: Not Found |
| https://cloud.streamingconnect.tv:455/tbmadrid/tbmadrid.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://broadcasting.parlamentodenavarra.es/live/canal1/master.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://broadcasting.parlamentodenavarra.es/live/canal2/master.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://str.intercomarcal.com/hls/tvixa.m3u8 | <urlopen error [Errno 113] No route to host> |
| https://str.intercomarcal.com/hls/tvixa1.m3u8 | <urlopen error [Errno 113] No route to host> |
| https://str.intercomarcal.com/hls/tvixa3.m3u8 | <urlopen error [Errno 113] No route to host> |
| https://streaming002.gestec-video.com/hls/canal24.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://streaming01.gestec-video.com/hls/artequatreAlacanti.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://streaming01.gestec-video.com/hls/artequatreTVA.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://cloud.streamingconnect.tv:455/12tv/gcmin.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://emision.arpamedia.es:4343/hls/emisionsanvicente.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://streaming.tvt-datos.es:8080/hls/tvb/live.m3u8 | hostname 'streaming.tvt-datos.es' doesn't match either of '*.tvt.es', 'tvt.es' |
| https://cdn01.yowi.tv/5RO3JQE6LN/master.m3u8 | HTTP Error 404: Not Found |
| https://stream.maestrat.tv/hls/stream.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://streaming-audio-1.magentalabs.es:19360/eltorotv/eltorotv.m3u8 | HTTP Error 404: Not Found |
| https://emision.arpamedia.es:4343/hls/emisionalicante.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://streamserver3.seneca.tv/cval_live/cdn_enc_3/master.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://cerestv.ddns.net/hls/caceres.m3u8 | <urlopen error [Errno 110] Connection timed out> |
| https://events4-crtvg.flumotion.com/playlist.m3u8 | <urlopen error [Errno -2] Name or service not known> |
| https://events5-crtvg.flumotion.com/playlist.m3u8 | <urlopen error [Errno -2] Name or service not known> |
| https://directo.tvferrol.es/tv.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://cloud.streamingconnect.tv:455/televigo/televigo.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://cloudbilbao.todostreaming.es/live/telebilbao-livestream.m3u8 | HTTP Error 404: Not Found |
| https://cloud.streamingconnect.tv:455/asturiastv/asturiastv.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://5924d3ad0efcf.streamlock.net/elcomerciodos/elcomerciodoslive/playlist.m3u8 | HTTP Error 404: Not Found |
| https://ott.mapeka.es:64000/live/_definst_/telearchena/playlist.m3u8?bid=mapeka&sid=1&ref=bb22a7fda046cceead5da8d964caf620 | <urlopen error [Errno 113] No route to host> |
| https://cloud.streamingconnect.tv:455/populartvrm/populartvrm.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://bfmtvalive1-a.akamaihd.net/316e573c8855429887f65feb189fb5a7/eu-central-1/876450610001/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://live.cdn.ln24.be/out/v1/b191621c8b9a436cad37bb36a82d2e1c/index.m3u8 | HTTP Error 404: Not Found |
| https://live.rte.ie/live/a/channel3/news.isml/playlist.m3u8 | HTTP Error 404: Not Found |
| https://tv-trthaber.live.trt.com.tr/master.m3u8 | <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:852)> |
| https://cdn1-7p.teleuptv.net/c4d0569e-cfdc-4608-b9b4-01802c17f447/index.m3u8 | HTTP Error 404: Not Found |
| https://weather-lh.akamaihd.net/i/twc_1@92006/master.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv//teleantioquialive/smil:dvrlive.smil/playlist_DVR.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta118.cdnmedia.tv/canaltro2live/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://liveingesta119.cdnmedia.tv/canaltro2live/smil:live.smil/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://cu.onliv3.com/livevd1/user2.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://cdnhd.iblups.com/hls/ptv2.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://cdnh8.iblups.com/hls/R9WtilpKKB.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://cdnh8.iblups.com/hls/RMuwrdk7M9.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://cdnh8.iblups.com/hls/OVJNKV4pSr.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://cloud.streamingconnect.tv:455/televen/televenweb.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://5ef74a4cbddfc.streamlock.net/CanalAntigua/myStream/plalist.m3u8 | hostname '5ef74a4cbddfc.streamlock.net' doesn't match 'streaming.canal32hn.com' |
| https://api.new.livestream.com/accounts/1359588/events/4428723/live.m3u8 | HTTP Error 404: Not Found |
| https://api.new.livestream.com/accounts/28126860/events/8825282/live.m3u8 | HTTP Error 404: Not Found |
| https://stream-wipr.online/hls/wipr/index.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://cdn-cdn-iguacu.ciclano.io:1443/cdn-iguacu/cdn-iguacu/master.m3u8 | HTTP Error 404: Not Found |
| https://amdlive-ch01-ctnd-com.akamaized.net/arirang_1ch/smil:arirang_1ch.smil/playlist.m3u8 | HTTP Error 503: Service Unavailable |
| https://jk3lz82elw79-hls-live.5centscdn.com/Geo/eae835e83c0494a376229f254f7d3392.sdp/Geo/Stream1/playlist_dvr.m3u8 | HTTP Error 404: Not Found |
| https://5ab29cc78f681.streamlock.net/expressdigital1/livestream/master.m3u8 | HTTP Error 404: Not Found |
| https://www.untvweb.com/live-stream/untvweb.m3u8 | HTTP Error 404: Not Found |
| https://live4.tdm.com.mo/ch2/_definst_/ch2.live/playlist.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://live4.tdm.com.mo/ch1/_definst_/ch1.live/playlist.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://live4.tdm.com.mo/ch3/_definst_/ch3.live/playlist.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://cloud.streamingconnect.tv:455/rasdtv/rasdtv.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://tastemade.samsung.wurl.com/manifest/playlist.m3u8 | HTTP Error 502: Bad Gateway |
| https://59ec5453559f0.streamlock.net/miamitv/smil:miamitvWEB/chunklist_w214662580_b2592000.m3u8 | HTTP Error 404: Not Found |
| https://59ec5453559f0.streamlock.net/miamitv/smil:miamitvROKU/chunklist_w1195980091_b2592000.m3u8 | HTTP Error 404: Not Found |
| https://stream-us-east-1.getpublica.com/playlist.m3u8?network_id=553 | HTTP Error 400: Bad Request |
| https://tv.siete.us:19360/bestcablesports/bestcablesports/index.m3u8 | hostname 'tv.siete.us' doesn't match 'ca.inka.net.pe' |
| https://live.yowi.tv/f8c87cd531ccd9f6b6ba/master.m3u8 | HTTP Error 404: Not Found |
| https://live2-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(ew)/index.m3u8 | HTTP Error 451: Unavailable For Legal Reasons |
| https://live3-radio-mediaset-it.akamaized.net/content/hls_h0_clr_vos/live/channel(er)/index.m3u8 | HTTP Error 451: Unavailable For Legal Reasons |
| https://live3-radio-mediaset-it.akamaized.net/content/hls_h0_clr_vos/live/channel(bb)/index.m3u8 | HTTP Error 451: Unavailable For Legal Reasons |
| https://5ce9406b73c33.streamlock.net/ONFM/livestream/master.m3u8 | HTTP Error 404: Not Found |
| https://nstream17.gotv.at:1443/live/_definst_/gotvlive_576p/chunklist.m3u8 | <urlopen error [Errno 113] No route to host> |
| https://vcndstv.teleosmedia.com/stream/dstv/dstv/playlist.m3u8 | <urlopen error [Errno 111] Connection refused> |
| https://muzzik-live.morescreens.com/mts-a6/chunklist.m3u8 | HTTP Error 404: Not Found |
| https://cu.onliv3.com/livevd/user1.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://live-edge01.telecentro.net.ar/live/smil:musictop.smil/playlist.m3u8 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> |
| https://5e4e2e0bb2914.streamlock.net/live/ngrp:tbnlive_srt_new.stream_all/playlist_DVR.m3u8 | <urlopen error [Errno 111] Connection refused> |
| https://bcliveuniv-lh.akamaihd.net/i/iptv1_1@194050/master.m3u8 | HTTP Error 400: Bad Request |
| https://11554-1.b.cdn13.com/LiveHTTPOrigin/live/playlist.m3u8 | HTTP Error 403: Forbidden |
| https://api.new.livestream.com/accounts/23202872/events/7200883/live.m3u8 | HTTP Error 404: Not Found |

**Comment by LaQuay** [comment]
Gracias! Le doy un vistazo.

**Comment by LaQuay** [comment]
Se aplicaron en su momento los cambios pertinentes. Gracias!
