### ISSUE TITLE
Fallan algunos canales

### ISSUE THREAD

**Issue by acpt88** [LaQuay/TDTChannels#209]
He probado la lista en varios clientes y lugares distintos y hay algunos canales que no funcionan (sobre todo los de Atresmedia), la aplicación para Android tiene el mismo problema. El visor web en cambio funciona a la perfección.

**Comment by acpt88** [comment]
> Aca todos los seis canales (geobloqueados) de Atresmedia funcion perfectamente, incluso andan simultaneamente (pues, por lo menos por 2 minutos, despues termine mi experimento).
> 
> En realidad me parece extranio que todos eses avisos de errores proceden de usuarios los que justo se han registrado en el Github....

Pues sí, resulta que para hacer comentarios hay que registrarse en GitHub.
Respecto al asunto de que no funcionen algunos canales no sé si será cosa del ISP que bloquee de alguna manera el visionado, aun así en la web funciona perfectamente pero no si utilizo la lista en VLC por ejemplo.

**Comment by aldago** [comment]
Reemplazad en el fichero que bajáis https://livestartover.atresmedia.com/ por https://livestartover-i.akamaized.net/, parece un problema del servidor...  en a3media:

Error 503 backend read error
backend read error
Guru Mediation:
Varnish cache server

**Comment by HelmerLuzo** [comment]
Acabo de lanzar PR para arreglar los enlaces de A3media.

**Comment by malvinas2** [comment]
Ahh, ustedes intentan abrir los enclaces en una manera directa. Eso no funciona ;-) 
Para abrir los ficheros m3u8 necesitan installar [Streamlink](https://github.com/streamlink/streamlink) y despues en el prompt de comandos / línea de comandos ("MS-DOS command line" en Windows) usan el siguiente comando (en ese caso para la cadena La Sexta): 
`streamlink https://livestartover.atresmedia.com/geolasexta/master.m3u8 best`

**Comment by acpt88** [comment]
> Reemplazad en el fichero que bajáis https://livestartover.atresmedia.com/ por https://livestartover-i.akamaized.net/, parece un problema del servidor... en a3media:
> 
> Error 503 backend read error
> backend read error
> Guru Mediation:
> Varnish cache server

En efecto así vuelve a funcionar, gracias por la información.

**Comment by LaQuay** [comment]
Solucionado en https://github.com/LaQuay/TDTChannels/pull/211
