### ISSUE TITLE
La 1 HD

### ISSUE THREAD

**Issue by paurg15** [LaQuay/TDTChannels#21]
He encontrado la web de RTVE oficial donde está La 1 HD [http://www.rtve.es/alacarta/videos/programa/tve_la1hd-live/1689467/](url) , este es el m3u8 [http://rtvev4-live.hss.adaptive.level3.net/egress/ahandler/rtvegl7/thd_lv3_aosv4_gl7/thd_lv3_aosv4_gl7.isml/thd_lv3_aosv4_gl7-audio=128000-video=1500000.m3u8](url)

**Comment by LaQuay** [comment]
@paurg15 Gracias! Pero, ya no funciona, verdad?

**Comment by paurg15** [comment]
Funciona cuando le da la gana, a veces va y otras no y cuando no funciona en la web pone: No disponemos de los derechos de imagen de los contenidos. Pero lo mismo están dando el Telediario...

**Comment by LaQuay** [comment]
@paurg15 Correcto, habrá que ver que pasa :+1:
