### ISSUE TITLE
La sexta sigue sin funcionar

### ISSUE THREAD

**Issue by Gonchitaro** [LaQuay/TDTChannels#212]
Se ha reparado Antena 3 y otros, pero parece que Lasexta sigue sin funcionar correctamente. Sigue apareciendo 
_"Su entrada no puede abrirse:
VLC es incapaz de abrir el MRL «https://livestartover.atresmedia.com/geolasexta/master.m3u8». Vea el registro para más detalles.
Su entrada no puede abrirse:
VLC es incapaz de abrir el MRL «https://livestartover.atresmedia.com/lasexta/master.m3u8». Vea el registro para más detalles."_

Creo que el enlace correcto sería https://livestartover-i.akamaized.net/lasexta/master.m3u8

**Comment by LaQuay** [comment]
Ahora debería estar solucionado.
