### ISSUE TITLE
No funciona la radio

### ISSUE THREAD

**Issue by Boitle** [LaQuay/TDTChannels#216]
Acabo de instalar TDTChannels y no aparece ninguna emisora de radio
¿alguna pista de que puede haber pasado?
Muchas gracias

**Comment by LaQuay** [comment]
Hola, si que funciona... No sé me ocurre que puede pasar. Si pudieras dar más datos

**Comment by Boitle** [comment]
He instalado la app en una tableta de samsung y no aparece ningun canal de radio

**Comment by LaQuay** [comment]
No se vé nada en el apartado de Radios pero si en el de TV, dices?
