### ISSUE TITLE
Canal no funciona: Secret Story 24 Hrs

### ISSUE THREAD

**Issue by zafirat** [LaQuay/TDTChannels#2163]
Desde hace dos días no funciona 

<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by LaQuay** [comment]
Cambiaron algo para las ultimas emisiones. Ya han cesado emisión.
