### ISSUE TITLE
Mega, Neox, nova off

### ISSUE THREAD

**Issue by adamo331** [LaQuay/TDTChannels#218]
Guys 

do you have same issue for No Geoblocked link (Nova, Mega, Neox) no opens in VLC.

 Neox HD | https://livestartover-i.akamaized.net/neox/master.m3u8
| Nova HD | https://livestartover-i.akamaized.net/nova/master.m3u8
| Mega HD | https://livestartover-i.akamaized.net/mega/master.m3u8

Telecinco and la sexta, cuatro new link working fine in VLC

**Comment by LaQuay** [comment]
Hi, I don't understand the problem here. Those channels have also a GEO channel.

**Comment by adamo331** [comment]
Hi
Yes Geo channel working if you are in spain but those link  NoGeo not working, may be someone need to pull the correcet one for NoGeo

**Comment by LaQuay** [comment]
I can't understand where is the problem here. They are working fine, both versions, GEO and not GEO. From Spain. If they don't work outside Spain try them through the official website, because there won't work too.
