### ISSUE TITLE
Revertir cambios 

### ISSUE THREAD

**Issue by free2air-info** [LaQuay/TDTChannels#219]
Hola,

Un montón de cadenas han desaparecido aunque su HLS sigue estando operativo.

Los cambios de este commit deberían revertirse en su mayoría: https://github.com/LaQuay/TDTChannels/commit/408b6c64e583cf24e5ebd260edc854ed759987db

Que una URL no funcione en un determinado momento no significa que el canal haya desaparecido por completo. Este cambio ha sido un desastre.

**Comment by LaQuay** [comment]
Hola, a qué emisoras te refieres?

**Comment by free2air-info** [comment]
Por ejemplo, Televisió de Cardedeu, Televisió de Olot, Penedès TV,... es un suma y sigue...

Han desaparecido canales que en una lista que tengo de hace un mes se sigues viendo perfectamente.

**Comment by LaQuay** [comment]
En su momento, cuando acepté la PR, no funcionaban. He probado ahora, y siguen sin funcionar. Ni en VLC, ni via browser. Estás probando las mismas URLs? Por ejemplo la de Olot?

**Comment by free2air-info** [comment]
Olot y Cardedeu, ambas funcionan sin problema. He probado con DVBViewer y en Chrome. Ambas sin problema ahora mismo.

**Comment by free2air-info** [comment]
El9tv perfectamente, valles oriental igual,... Podría probarlas todas en tener un rato. La lástima es que he machacado la lista y ahora es imposible volver atrás...

**Comment by free2air-info** [comment]
Te confirmo que todas las de la URL http://liveingesta118.cdnmedia.tv/ funcionan bien.

**Comment by free2air-info** [comment]
Gracias! Si quieres que haga alguna prueba de algún canal, dímelo.
