### ISSUE TITLE
A3media

### ISSUE THREAD

**Issue by Raka74** [LaQuay/TDTChannels#22]
Hola LaQuay
Hace algunos días los canales de a3media no funcionan, sí le doy al link de m3u me sale una falla de que el url no es correcto. Sabes como puedo repararlo o hacer que funcione?
De antemano, gracias.

por ejemplo:

The requested URL "http://%5bNo%20Host%5d/novampp/master.m3u8", is invalid.
Reference #9.b5525d68.1530272431.1aaafd73

**Comment by LaQuay** [comment]
@Raka74 Solucionado, gracias por el aviso 👍
