### ISSUE TITLE
Canales

### ISSUE THREAD

**Issue by bix02** [LaQuay/TDTChannels#220]
Porfa agrega el canal GH 24 horas el normal gratuito, entiendo que el otro no puedas pero porfa sube el normal

**Comment by LaQuay** [comment]
Cuál es la URL?

**Comment by ajpl70** [comment]
https://livehlsdai-i.akamaihd.net/hls/live/670612/granhermano01/bitrate_3.m3u8

Señal 1 ( gratuita )

Tengo también la otra Señal ( aunque es la señal de pago, no sé hasta qué punto es legal poder publicarla )

**Comment by LaQuay** [comment]
> https://livehlsdai-i.akamaihd.net/hls/live/670612/granhermano01/bitrate_3.m3u8
> 
> Señal 1 ( gratuita )
> 
> Tengo también la otra Señal ( aunque es la señal de pago, no sé hasta qué punto es legal poder publicarla )

Añadido, gracias!

05cef892ec698a8b68e47c13e5b95bcde853f012
