### ISSUE TITLE
Añadir LinuxClick FM

### ISSUE THREAD

**Issue by AngelJRomero21** [LaQuay/TDTChannels#2223]
LinuxClick Fm es una emisora de radio informatica que transmite 24/7 y habla sobre GNU/LInux y software Libre.

URL PARA RETRANSMITIR O ESCUCHAR EN TU REPRODUCTOR FAVORITO:

[http://bit.ly/linuxclickfm](https://bit.ly/linuxclickfm)

Canal de Telegram

[t.me/linuxenesp](https://t.me/linuxenesp)

**Comment by LaQuay** [comment]
Hola, eres el propietario?
