### ISSUE TITLE
Streams HLS E2

### ISSUE THREAD

**Issue by norhap** [LaQuay/TDTChannels#226]
streams HLS en el sistema E2 estan provocando en este sistema GSOD, el cambio de servicemp3 soluciona este problema.

**Comment by malversan** [comment]
Dejando de lado la nula información que das, parece evidente que eso no guarda ninguna relación con este proyecto, que no es un software sino una simple lista de URLs.

Si tu sistema operativo tiene problemas con algún tipo de streams, reporta el fallo a su fabricante.

**Comment by norhap** [comment]
sabes que es el servicemp3?

**Comment by norhap** [comment]
he dado toda la información, pero lo primero es saber si sabes que es, por lo que entiendo que no lo sabes, el servicio mp3 está dentro del servicereference, de todas y cada unas de las lineas streams de URLs para el sistema E2, por lo tanto están dentro de este proyecto y de sus URLs.
El problema se genera en los receptores con arquitectura Chipset HiSilicon, no así en los antiguos mips32el, en principio las líneas están bien como están, de siempre han funcionado así, pero desde que este tipo de Chipset (HiSi) de huawei se está propagando cada vez más por los receptores sobre todo en los 4k, pues se está generando un crash importante cuando se intenta visualizar canales con este tipo de streams (HLS).
Este servicio se puede cambiar, dado que E2 puede disponer de unas librerías adicionales para poder usar un segundo reproductor, llamado exteplayer3, la solución de cambio de servicio no soluciona del todo, simplemente cuando se inicia no se llega a visualizar el stream, pero al menos no provoca broken total ya que dispara un crash el sistema.

**Comment by norhap** [comment]
El problema es que los fabricantes se dedican más a vender que actualizar sus drivers, ahora mismo cuando escribimos no hacen absolutamente nada al respecto, pero está reportado.
La idea es poder tener tal vez, dos opciones de lista E2, una normal de descarga como la que está ahora y otra para este tipo de Chipset, estás URLs funcionarian también en los mips32el es totalmente compatible, pero quitariamos un crash del sistema que la verdad, es bastante molesto.

**Comment by malversan** [comment]
Sinceramente no sé qué demonios estás haciendo aquí, cuando tú mismo dices que tu problema radica en el hardware. Por lo visto sólo has venido a crear ruido abriendo un reporte de un fallo que no pinta nada en este repositorio.

Este proyecto es una lista de datos, NO ES UN SOFTWARE NI MANEJA HARDWARE ALGUNO. Más claro no se te puede decir.

Nada de lo que explicas tiene interés ni aplicación en este proyecto. Todo el inútil rollazo que has escrito es sólo aplicable al software Enigma2, así que lo propio es que vayas al repositorio de ese software y les cuentes tu vida allí. Vacilar aquí sobre si sabemos o no de qué hablas es un chiste, cuando resulta obvio que quien no se entera de dónde está eres tú.

P.D.: Respecto a la información que NO das, cuando vayas a reportar al lugar adecuado te recomiendo que para empezar les indiques de qué hardware/software/driver/SO y versión estás hablando. Especialmente si hablas de fallos catastróficos como xSOD. Nadie va a saber de qué hablas SI NO LO DICES TÚ DE ENTRADA, y desde luego eso no significa que los tontos sean los demás.

**Comment by norhap** [comment]
Hombre, yo entiendo que estés frustrado por que no tienes ni la más remota idea, te lo voy a resumir rápido no con tocho, si escupes para arriba pasa lo que pasa, no lo digo yo, lo hiciste tú, ¿te ha dolido que sepan todos que te has metido sin saber ni de que hablabas? , no sabes ni como vas a salir ahora de tú primer comentario, solo con un tocho como el que has puesto, en cuatro lineas te lo he aclarado.

**Comment by malversan** [comment]
¿A ti te pasa algo en las entendederas? Lee la parte en mayúsculas, anda. Son sólo ocho palabras, creo que hasta tú llegas a eso.

Todo tu rollo es irrelevante, aquí no pinta nada. Y que pretendas presumir de estar meando fuera de tiesto es patético.

Tu tontería me recuerda a un burro que vi hace unos días, que se divierte abriendo reportes sobre fallos inexistentes. Parece que por aquí hay mucha gente rara que no entiende para qué sirve Github.

**Comment by malversan** [comment]
Joer, ¡si eres tú! ¿En serio me estás persiguiendo por todo Github para contaminar con tus lloros todos los repositorios donde yo haya comentado algo? ¿Tan falto de cariño andas, niño?

@LaQuay, puedes eliminar este reporte sin miramientos. Este troll se divierte jorobando repositorios a base de crear reportes falsos sobre fallos inexistentes. Ya era bastante evidente leyendo sus tonterías, pero es que además le he visto hacerlo más veces.

**Comment by norhap** [comment]
¿Alguien que sepa?

**Comment by spaJR** [comment]
Joder vaya tela con el issue, y más cuando norhap tiene razón. Cuando alguien no sabe de lo que se habla no entiendo para se mete en discusiones inútiles. Si hay una lista para enigma2 y da fallos en ese sistema, lo normal es que mire de arreglarse, y no que todo un sistema enigma2 se cambie para esa lista. Como tengo claro que nadie sabemos de que va el tema menos malversan, aquí queda dicho, y que cada uno tome sus decisiones, pero entrar en descalificaciones y faltas de respeto me parece lamentable.

**Comment by malversan** [comment]
No hay ninguna lista ”para Enigma2”, lo que hay son listas en formatos estándar.

Pero nada, oye, si ahora vais a venir de uno en uno todos los ”sabios” que andáis llorando en el repositorio de Enigma2 porque no os arreglan vuestros problemas con el hardware, por favor EXPLICADNOS A TODOS CÓMO OS LOS VAN ARREGLAR AQUÍ, donde no hay ningún software ni hardware que tratar.

No tenéis ni puñetera idea de qué habláis, ni siquiera sabéis dónde estáis, y por lo visto encima os creéis que los tontos son los demás.

**Comment by spaJR** [comment]
Ya te digo que no me voy a poner a tu altura con faltas de respeto y gilipolleces varias, si quieres entender las cosas bien, y sino también. Aquí corto y cierro y que te vaya bonito con tu excelente carácter. Si algún día te dignas a bajar del cielo y equipararte a los terrestres como nosotros para hablar de temas técnicos, aquí estaremos esperándote, pero mientras vivas en tu mundo de fantasía, no podemos hacer nada.

**Comment by malversan** [comment]
Yo mismo te he conminado a que hables de temas técnicos, porque no veo que lo hayas hecho en ningún momento. Lo único que has hecho es venir a hacerle la ola a un troll reconocido sin saber de qué hablas ni dónde estás.

Que te vaya bonito.

**Comment by norhap** [comment]
El problema es que solo llegaste hasta el 4096.

**Comment by malversan** [comment]
Si crees que escribiendo chorradas sin sentido va a parecer que los tontos son los demás, vuelve a pensar.

Estamos esperando todos que expliques técnicamente cómo una enumeración de URLs te va a arreglar los problemas que tiene tu software con el hardware, monín. Diviértenos y te llevas un cacahuete.

**Comment by norhap** [comment]
¿Alguien que sepa?

**Comment by malversan** [comment]
En los repositorios de Enigma2 y de servicemp3 seguro que encuentras ”alguien que sepa”. Pero por algún motivo no has abierto ningún reporte allí, prefieres hacer el ridículo molestando donde no te pueden arreglar tus problemas.

**Comment by norhap** [comment]
¿Alguien que aporte algo?

**Comment by LaQuay** [comment]
Hola a todos,
Estoy intentando entender el hilo, pero no lo consigo. 
No dispongo de Enigma2 y mucho menos soy un experto. El proyecto tiene ahora mismo como métodos estándares el formato `web`, el `markdown`, el `json`, el `m3u8` y el `m3u`. Con dichos estándares tenemos un gran abanico de posibilidades para que los usuarios disfruten de este proyecto Open Source. El formato `enigma2` se introdujo gracias a dos usuarios del mismo, que casi hicieron todo el trabajo y yo, solo tuve que adaptar el código que generaba el fichero para `enigma2`.

Hasta ahora, la misma gente que utiliza `enigma2` está contenta por que les funciona perfectamente. Así que no llego a entender la problemática.

Recuerdo, que quién lo tenga claro, puede realizar una 'pull request' o una 'issue', como aquí, con el fin de mostrarme la forma de solucionarlo. Pero por favor, no me avasalléis el correo electrónico personal, ni este repositorio ni sus repositorios hermanos por que bloquearé a los que lo hagan. Con una única vez que se escriba aquí, yo lo leo. Gracias.

@norhap Puedes escribir en inglés si lo prefieres. Me cuesta mucho entender el español que escribes, supongo será traducido.

@malversan Puedes escribirme por email o Telegram? Quiero comentarte una cosa.

Gracias.

**Comment by norhap** [comment]
Ejemplo de un stream con protocolo HLS, que está dentro del formato E2 de su lista, Canal Cuatro HD:
4097:0:1:17:0:0:0:0:0:0:https%3a//livehlsdai-i.akamaihd.net/**hls**/live/571643/cuatro/bitrate_4.m3u8:Cuatro HD

Si se fija en dicha linea, este stream tiene un servicio de referencia, lo que en enigma2 llamamos le service reference 4097:0:1:17:0:0:0:0:0:0, en dicha referencia la parte que le sigue al 4097 es para usarlo en enigma2 para logos y EPG, hasta aqui todo bien y ningún problema, pero tenemos un número que es el 4097, este servicio es el que usa Enigma2 en su reproductor por defecto, osea por defecto este servicio mp3 es el que traduce el stream en audio y video en el sistema E2 en las listas IPTV, seguimos hasta aquí no tenemos problemas y de hecho no hay que modificar nada en la lista de este formato E2.

¿Que problema hay entonces? 

Los fabricantes de receptores están introduciendo cada vez más el Chipset Hisilicon, que son los que traen este problema, el resto de arquitecturas usadas en otros receptores no hay problema alguno, de ahí que usted diga lo de que la gente está contenta y no hay problema, pero si se tiene este tipo de receptores de entre ellos yo, este tipo de streams provocan un crash en el sistema severo, el log como característica significativa nos dice SIGNAL FATAL y solo lo provocan los streams con este tipo de protocolo de comunicación (HLS) es decir cualquier stream de su lista que no estén dentro de este protocolo incluso en los Chipset HiSi no provocan dicho crash, se deben dar dos circunstancias, que sea este tipo de stream y que se tenga un receptor con este tipo de CPU.

¿Que propongo?

Pues no modificar absolutamente nada respecto a la lista que se tiene ahora mismo aqui, no es ni muchísimo menos mi intención, pero si propongo adaptar una nueva lista, esta lista seria usada solo con el reproductor **serviceapp**, este reproductor está disponible en todos los feeds de los servidores de imagénes E2, OpenPLI, OE-A etc, osea se pueden disponer de el todos los usuarios.

¿Que hace este reproductor alternativo en Enigma2?

Pues de entre otras ventajas usa otro servicio al que hay por defecto (4097), usariamos el servicio **5002**.

Lo que conseguimos es que simplemente no visionariamos el stream pero al menos **no provocamos un crash en el sistema como el que ocurre ahora**, todo esto siempre y cuando los desarrolladores de drivers de los fabricantes no hagan nada al respecto como es el caso ahora y donde yo personalmente ya les reporté el asunto pero oidos sordos.

La propuesta es sencilla, hacer una segunda lista enigma2, pues por ejemplo llamarla enigma2-serviceapp, donde este tipo de lista solo puede ser vivisionada con el segundo reproductor por defecto y donde no provocariamos este tipo de crash en los receptores con el Chipset que arriba cito, donde lo único a cambiar en todas y cada una de las lineas streams seria el 4097 por el 5002.

**Comment by malversan** [comment]
Y digo yo, ¿no sería mejor arreglar tu problema allí donde radica, y proponer un parche a los desarrolladores de Enigma2 para que os permitiesen configurar un flag que indique a vuestro software que fuerce el uso del servicio 5002 (allí donde conste que debería usarse el 4097) para streams HLS?

Desde luego sería mucho más fácil. Te ahorrarías ir por todo el planeta pidiendo a todos los publicadores de listas de streams que creen una lista específica para ti y los cuatro gatos que tenéis este problema. Y para postre lo que propones no es para que podáis utilizar los streams, sólo es para evitar que os pete Enigma2.

Insisto en que esto no es un problema que tengan las listas, es un problema que tiene Enigma2 con determinado hardware. No entiendo el afán de cambiar el mundo exterior por no arreglar realmente el problema.

P.D.: Ha sido agradable constatar que cuando te lo propones puedes escribir como una persona. Que alguien haya llegado a interpretar que no sabías español ha sido para partirse de risa.

**Comment by norhap** [comment]
Aplicado .gitignore.

**Comment by malversan** [comment]
Pues te deseo buena suerte, si cuando alguien te propone una solución DEFINITIVA para tu problema lo único que se te ocurre es responder con un chiste malo (o quizá sea simplemente que no tienes ni idea de qué es el .gitignore, vaya usted a saber).

De entrada hubiera estado bien que toda esa explicación la hubieras aportado al principio, en tu primer mensaje, en lugar de pasarte días berreando porque nadie sabía de qué hablabas. El interesado en aportar toda la información necesaria eres tú, no te la tienen que pedir ni ir sacándotela. Como ya te comenté, esto no es un forillo.

**Comment by norhap** [comment]
@LaQuay cuando usted tenga lugar seguimos el desarrollo de su comentario.

**Comment by LaQuay** [comment]
Hola @norhap 
Ahora he entendido el problema y la posible solución. Sin embargo, el problema radica en Enigma2 y no en nuestra lista.

Como bien has comentado, si se soluciona cambiando el 4097 por 5002, por el momento va a tocarte hacer manualmente el cambio. Ya que el error es de Enigma 2 pero en cierto modo, "provocado" por tu entorno. Es decir, no es algo generalizado. Gracias.

Un saludo.

**Comment by norhap** [comment]
Te entiendo, lo que ocurre es que esto puede mirarse de dos formas, la primera la expuesta como issue, lo cual entiendo que si es un problema de CPU a nivel drivers y no de lista lo llego a entender, ahora bien, fijese que usted dijo arriba que los estándares ofrecen un abánico importante de posibilidades, a partir de aqui miremos lo que propongo no como una solución a un problema, sino como posibilidad de dar en su GIT otra lista con posibilidad de reproducirla con un segundo reproductor y no como está ahora que solo hay un única forma.

Si digo esto es por una sencilla razón, cada vez los usuarios usan más el serviceapp, este plugin abarca cualquier contenido multimedia no solo streams, hay muchos que tienen problemas con receptores 4k ( ARM) que incluso no son HiSi, formatos contenedores y codecs no son capaces de reproducirlos con el Gstreamer actual, enigma2 tiene una gran laguna en ese sentido.

Si partimos de esa base, dese cuenta que hay muchos usuarios que tienen el segundo reproductor por defecto instalado y configurado, solventa problemas en las reproducciones que con el reproductor por defecto no son capaces de solucionar.

Aparte tiene usted que saber, que este segundo reproductor es capaz de hacer la lectura con ambos servicios, 4097,5002, y bueno incluso uno más,  que no viene al caso ya que seria enredar un poco más todo esto que hablamos.

Un ejemplo, con su lista normal, con un receptor mips32el, ( este chip no provoca crash, simplemente no se viciona),  ¿que tengo que hacer con su lista? mandar un comando sed, buscar aquellos 4097 en los streams que no visiono, como es cuatro HD y cambiarlos por el 5002, usar el serviceapp y asi los visiono practicamente todos.

Un amigo, que creo estuvo hablando con usted hace pocos meses, se hizo un plugin y metio su URL de descarga y conversando con él, también me confirmaba dichos crash en receptores hisi, él lo que hizo fue cambiar la lista a todos los steamas a 5002 a modo código dentro de su plugin, para poder tener practicamente la totalidad de visionado de los canales.

Repito le entiendo y no le voy a insistir, lo único que a mi me parece es que nunca está demás dos tipos de lista dado que enigma2 así puede reproducirlas que tener solo una posibilidad de lista a como está ahora, el abánico lo harías aun más completo a nivel formato E2.

**Comment by malversan** [comment]
”enigma2 tiene una gran laguna en ese sentido”.
”el problema no es de su lista si no de los bugs en enigma2”.

Habiendo llegado por fin a la conclusión obvia a la que habíamos llegado los demás, ¿no sería adecuado que reportases estos errores y lagunas en el repositorio de Enigma2 y/o plugins asociados? Por mucha importancia que digas darles, si no lo haces en el lugar adecuado no los vas a ver solucionados nunca.

Con cariño te lo digo.
