### ISSUE TITLE
Canal no funciona: NOMBRE

### ISSUE THREAD

**Issue by elefant66** [LaQuay/TDTChannels#2323]
4410

https://directes-tv-int.ccma.cat/int/ngrp:324_web/playlist.m3u8)[https://directes-tv-int.ccma.cat/int/ngrp:324_web/playlist.m3u8](view-source:https://directes-tv-int.ccma.cat/int/ngrp:324_web/playlist.m3u8)

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
nuevo 
https://directes-tv-int.ccma.cat/live-content/canal324-hls/bitrate_1.m3u8
y
https://directes-tv-int.ccma.cat/live-content/canal324-hls/master.m3u8

**Comment by LaQuay** [comment]
Updated accordingly, thanks
