### ISSUE TITLE
Canales catalanes que no funcionan

### ISSUE THREAD

**Issue by jpgine** [LaQuay/TDTChannels#233]
Hola, bastantes de los canales catalanes no funcionan, así creo que estaría bien recuperar los flujos que funcionan en este fichero. Gracias de antemano

[Catalanes.zip](https://github.com/LaQuay/TDTChannels/files/3722160/Catalanes.zip)
[spain91.zip](https://github.com/LaQuay/TDTChannels/files/3722161/spain91.zip)

También estaría bien anadir estas cadenas de TDT catalana: http://mapa.laxarxa.com/

**Comment by LaQuay** [comment]
Hola! Tomo nota, gracias!

**Comment by LaQuay** [comment]
Hola! He revisado la web, todos están incluidos ya en el repositorio. Sobre los .zip, me es muy difícil ver cuales tenemos, cuales no, etc. Si crees que falta alguno, mencionalo explícitamente por favor, y lo miro. Gracias!

**Comment by jpgine** [comment]
La mayor parte de los canales catalanes en el m3u8 siguen disfuncionando...
Qué triste.

Missatge de Marc Vila <notifications@github.com> del dia dv., 15 de nov.
2019 a les 20:58:

**Comment by jpgine** [comment]
Bon dia

Ara solament repari que te dius Marc Vila i que deus ser català... Fins i
tot un nacionalista de Perpinyà com jo molt atent a tot això no hi he
caigut...

És una pena que no puguem proposar a tots els catalans del món de mirar
totes les cadenes en català disponibles, sobretot que amb Hola unblocker
fem saltar els geoblocatges.

Si ho fesses, series un heroi de la pàtria i qualsevol podria carregar la
llista en m3u8 de debò (amb les imatgetes de cada cadena) i en ordre (de
nacionals a locals) en qualsevol televisor dotat d'Android i un programa
d'IPTV.

Jo no entenc gaire gaire d'informàtica pura, però segur que fins i tot i
podem afegir la tercera francesa en la seua versió rebuda al Rosselló (que
té escassos minuts en català) i de l'Alguer, i ben segur les andorranes
completes, que s'haurien de capturar d'allà perquè sinó van capades.

Missatge de Ningú No res <iveragrau@gmail.com> del dia ds., 16 de nov. 2019
a les 19:22:

**Comment by pcalsina** [comment]
Hola Marc,

Primero de todo gracias por el currazo con las listas TDT y las actualizaciones. Uso Kodi para ver la TDT y desde hace unos días he visto que TV3 se emite a una resolución de 320X180. Es algo que se pueda corregir???

Gracias!

**Comment by LaQuay** [comment]
@jpgine Bona nit, no segueixo si necessites quelcom per a la llista a realitzar.

@pcalsina Hola! Debe ser alguna configuración de tu KODI. Los enlaces son adaptativos de la propia cadena.

**Comment by jpgine** [comment]
No funcionen pas, la major part, amb qualsevol programa per a Android


Missatge de Marc Vila <notifications@github.com> del dia dj., 9 de gen.
2020 a les 23:35:
