### ISSUE TITLE
Canal no funciona: Radio Clásica RNE

### ISSUE THREAD

**Issue by cdlvcdlv** [LaQuay/TDTChannels#2337]
URL de la web de origen del canal
https://www.rtve.es/radio/radio-clasica/directo/

URL de la emision
https://www.rtve.es/play/audios/programa/rne_rclasica-live/1712494/

Con el enlace que hay ahora no funciona: suena una trompeta unos segundos y se corta.

**Comment by LaQuay** [comment]
Se solucionará en un rato, gracias.
