### ISSUE TITLE
Algunas contribuciones.

### ISSUE THREAD

**Issue by Milikitez** [LaQuay/TDTChannels#236]
Saludos.

Aquí te paso algunas emisoras de radio.

Radio Marca Valladolid: http://radiomarcavalladolid.streaming-pro.com:8067
COPE Deportes: http://net2.cope.stream.flumotion.com/cope/net2.mp3.m3u
COPE Valladolid: https://wecast-b03-04.flumotion.com/copesedes/valladolid.mp3
Cadena Ser Radio Valladolid: http://19373.live.streamtheworld.com/SER_VALLADOLID.mp3
Castilla y León esRadio: http://livestreaming2.esradio.fm:8000/cylrdo16
Mortal FM: http://server6.20comunicacion.com:8044
LOCA FM: http://audio-online.net:2300/live

Saludos.

**Comment by LaQuay** [comment]
Añadidos, gracias! https://github.com/LaQuay/TDTChannels/commit/e0f2b062b168e0bdbc0c3af41ef59dcd6aee9171
