### ISSUE TITLE
DMAX sin m3u8

### ISSUE THREAD

**Issue by javadevone** [LaQuay/TDTChannels#237]
En primer lugar permitidme que os felicite a todos los que os encargáis de mantener y hacer posible este proyecto, gracias a vosotros puedo ver la TV desde KODI en casi cualquier lugar. ¡Un trabajo enorme!

El problema que tengo personalmente es que uno de los canales que más me gusta ver (sobre todo de noche) es DMAX. En KODI no me aparece y examinando vuestra lista de enlaces m3u8, he observado que efectivamente en DMAX no tenéis dicho archivo disponible (falta también en algunos otros canales).

Imagino que ya sois conscientes de ello y que si fuera posible obtener el m3u8 ya lo habríais hecho, simplemente me gustaría saber cual es el problema por parte de DMAX exactamente y cómo se podría incluir con el resto de canales.

¡Gracias, un saludo y seguid trabajando así de bien!

**Comment by LaQuay** [comment]
Hola! Gracias por el feedback!
DMax no emite online, y por tanto, es imposible que podamos enlazarlo... 

Saludos!
