### ISSUE TITLE
Canal no funciona: El Toro TV

### ISSUE THREAD

**Issue by killo3967** [LaQuay/TDTChannels#2380]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
https://www.tdtchannels.com/lists/tv.m3u
<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://live1-eltorotv.flumotion.com/playlist.m3u8

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
No existe la direccion web

**Comment by LaQuay** [comment]
Está funcionando, gracias.
