### ISSUE TITLE
ETB

### ISSUE THREAD

**Issue by paurg15** [LaQuay/TDTChannels#24]
En la web de eitb.eus han comenzado a emitir online los canales ETB1 HD y ETB2 HD. He intentado sacar los archivos y me ha salido esto:

http://etbvnogeo-lh.akamaihd.net/i/ETBSTR1_1@595581/master.m3u8
http://etbvnogeo-lh.akamaihd.net/i/ETBSTR2_1@595582/master.m3u8

Lo que no sé porque es porque con estos enlaces la emisión no tiene nada que ver entre el m3u8 y la web.

**Comment by LaQuay** [comment]
Hola!
Gracias @paurg15! Si que cuadran, lo único que en la web hay como una especie de anuncio antes, una vez acaba, la web y .m3u8 van de la mano.

Lo añado!
