### ISSUE TITLE
Pantalla en loading

### ISSUE THREAD

**Issue by ericgimenez** [LaQuay/TDTChannels#2446]
Buenos dias, hacabo de descargar la nueva version 2022.08.01 y de vez en cuando si salgo de la applicacion y vuelvo en ella la pantalla se queda en loading, tengo que forzar el cierre de la applicacion y vuelve a funcionar pero no siempre como si hubiera un timing de espera.

**Comment by acutbal** [comment]
Hola!!
Justamente a mí me pasa lo mismo, se queda cargando. Forzando cierre y/o borrando datos a veces vuelve a cargar. 
Mi dispositivo es una Xiaomi Mi Box S.

Salu2 y muchas gracias!! :smile:

**Comment by acutbal** [comment]
Hola, acabo de ver el aviso en Telegram:
https://t.me/s/tdtchannels_avisos

Muchísimas gracias por todo!!

**Comment by LaQuay** [comment]
Exacto, hay que usar la última, la 2022.08.02. La 2022.08.01 tenía ese error. Gracias!
