### ISSUE TITLE
NORTEvision Gran Canaria

### ISSUE THREAD

**Issue by kanetaker** [LaQuay/TDTChannels#25]
#EXTM3U
#EXTINF:0,NORTEvision
#EXTVLCOPT:program=109
#EXTVLCOPT:file-caching=300
http://nortevision.dyndns.org:8001/1:0:1:6D:24:3138:EEEE0000:0:0:0:

**Comment by LaQuay** [comment]
Hola!
No encuentro la web oficial de Nortevision, podrías pasarmela? Gracias!

**Comment by kanetaker** [comment]
No tiene web oficial de momento,  con lo que te mandé no puedes hacer nada?

**Comment by LaQuay** [comment]
Hola,
Necesitaría saber de donde procede el enlace para colocarlo...
Gracias

**Comment by kanetaker** [comment]
Procede del archivo m3u en donde está ubicado el canal

**Comment by playzzz** [comment]
Creo que esta es la web: https://aljoamy.wixsite.com/misitio pero no estoy seguro, es todo muy raro...
