### ISSUE TITLE
Aplicacion libre en repositorio libre: F-Droid

### ISSUE THREAD

**Issue by narcisgarcia** [LaQuay/TDTChannels#2513]
Muchos usuarios utilizan el catálogo de f-droid.org para confiar en la lealtad de las aplicaciones, que han pasado por cierta inspección de libertad y seguridad. Y en algunos dispositivos libres F-Droid es el único catálogo de aplicaciones en red.

Mi propuesta es promover «TDTChannels» en el repositorio de f-droid.org

**Comment by rollingafull** [comment]
+1

**Comment by LaQuay** [comment]
> "F-Droid es un catálogo instalable de aplicaciones de software libre (FOSS, «Free and Open Source Software») para Android. El cliente facilita la navegación, la instalación y el seguimiento de las actualizaciones en tu dispositivo."

Sin embargo. La aplicación de TDTChannels no es software libre.

**Comment by narcisgarcia** [comment]
Según leo, la licencia Apache 2.0 **sí es de software libre**:
https://www.gnu.org/licenses/license-list.html#apache2
