### ISSUE TITLE
Canal no funciona: LEBRIJA TV

### ISSUE THREAD

**Issue by Manme1993** [LaQuay/TDTChannels#2544]
El canal cuando entro en Emisión 1 se pone a cargar y después sale Error y se quita...

**Comment by LaQuay** [comment]
Hola, el problema lo tienen ellos en su web, cuando lo arreglen funcionará.

**Comment by Manme1993** [comment]
Amm vale. Muchas gracias 😊

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
