### ISSUE TITLE
canales TV que no funcionan a 6 de enero de 2020

### ISSUE THREAD

**Issue by raulsevimor** [LaQuay/TDTChannels#256]
He hecho un repaso por los primeros canales de la lista de TV y comparto los que no me han funcionado:

Playz, el toro tv, varios +24, todos los atresplayer, todos los +tdp, ud las palmas, los40 en tv, del 40 al 1, canal sur eventos, estepona tv, costa noroeste, teleantequera, mastv huelva, canal doñana, fuengirola tv, huesca tv, la tele tv, canal 10 hd, la 1 la 2 y 24h de Canarias, tindaya, canal 4 Tenerife, mi tierra tv, canal 10 tv, teletoledo, imas tv hd, visión 6, manzanares 10tv, nasa tv

Un saludo

**Comment by LaQuay** [comment]
Hola! Le daremos un vistazo. Sin embargo es difícil determinar si un enlace está "caído" o no, pues al ser oficial van "tumbándolos" y levantándolos a su merced.

**Comment by byteloco** [comment]
No funciona nada. Absolutamente nada. ¿Servidor caído?

**Comment by LaQuay** [comment]
> No funciona nada. Absolutamente nada. ¿Servidor caído?

Hola! Disculpa, esta mañana he estado retocando todo el proyecto. Lo estoy migrando a un dominio mejor. La app debería funcionarte ya y las listas están subidas.

Gracias!
