### ISSUE TITLE
Canal no funciona: El Toro TV

### ISSUE THREAD

**Issue by killo3967** [LaQuay/TDTChannels#2585]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
https://www.tdtchannels.com/lists/tv.m3u

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://streaming003.gestec-video.com/hls/eltoro_bal.m3u8

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
#EXTINF:-1 tvg-id="ElToroTV.TV" tvg-logo="https://graph.facebook.com/eltorotv.es/picture?width=200&height=200" group-title="Generalistas" tvg-name="El Toro TV",El Toro TV

**Comment by Rakso67** [comment]
This is working
https://streaming011.gestec-video.com/hls/eltoro_bal.m3u8
