### ISSUE TITLE
Canal no funciona: TOROTV

### ISSUE THREAD

**Issue by killo3967** [LaQuay/TDTChannels#2601]
Este canal ha desaparecido de la lista.

**Comment by malomehi** [comment]
La url https://streaming003.gestec-video.com/hls/eltoro_bal.m3u8 ya no funciona.

Parece que ha cambiado a https://streaming012.gestec-video.com/hls/eltoro_bal.m3u8 que sí funciona.

Lo extraño es que la nueva url me funciona bien en el pc, con VLC por ejemplo, pero no me funciona si la uso en un bouquet en receptor enigma2.
Estaréa agradecido si alguien sabe por qué y comenta.

Lo tengo configurado asi: `#SERVICE 4097:0:1:9:0p:0:0:0:0:0:https%3a//streaming012.gestec-video.com/hls/eltoro_bal.m3u8:El Toro TV`

**Comment by malomehi** [comment]
Investigando un poco he dado con la solución.

Primeramente había un error en la linea, hay un `0p` que debe ser solamente `0`.

Además parece que el certificado por `https` es rechazado por el receptor así que lo he cambiado para que conecte con `http`.

La siguiente configuración funciona bien:
```
#SERVICE 4097:0:1:9:0:0:0:0:0:0:http%3a//streaming012.gestec-video.com/hls/eltoro_bal.m3u8:El Toro TV
#DESCRIPTION El Toro TV
```

**Comment by killo3967** [comment]
Estoy de acuerdo, el problema es que en el m3u viene como:

https://streaming**003**.gestec-video.com/hls/eltoro_bal.m3u8

Pero el que funciona es:

https://streaming**012**.gestec-video.com/hls/eltoro_bal.m3u8

Por favor cambiadlo.

**Comment by killo3967** [comment]
He tenido que hacer un m3u a parte y fusionarlo ya que no le dais solucion.
