### ISSUE TITLE
EPG no funciona en canales HD con ss iptv

### ISSUE THREAD

**Issue by PIC16f841** [LaQuay/TDTChannels#261]
Por ejemplo, cuatro muestra la programacion EPG pero cuatro HD no.

**Comment by HelmerLuzo** [comment]
¿El EPG de Onda Cádiz o cualquiera de los 3 Canal Andalucía, por ejemplo, te carga?

**Comment by PIC16f841** [comment]
No me va ningunl, adjunto foto del problema
![IMG_20200201_120856](https://user-images.githubusercontent.com/60220709/73591847-b7361680-44eb-11ea-9a16-a5bc5130bc30.jpg)
La mayoría de los epgs no van o son erroneos, ejemplo
![IMG_20200201_121029](https://user-images.githubusercontent.com/60220709/73591867-e187d400-44eb-11ea-8a02-a5845d5f6ac0.jpg)
Este aparece en otro idioma y ni siquiera se corresponde a lo que estén emitiendo :D

**Comment by HelmerLuzo** [comment]
Por algún motivo que desconozco, ssiptv no te está cogiendo el EPG. Déjame que pregunte en el canal de telegram y te digo algo.

**Comment by PIC16f841** [comment]
Vale ya he descubierto cual es el problema. Ss iptv usa el nombre del canal como id para el EPG, por eso Cuatro pilla los subtítulos pero Cuatro HD no. La solución para por añadir el tag TV-name con el nombre del canal que coincida con el del EPG. Ejemplo 

#EXTINF:-1 tvg-id="Cuatro.TDTChannelsEPG" tvg-logo="https://graph.facebook.com/cuatro/picture?width=320&height=320" group-title="Generalistas",Cuatro
https://livehlsdai-i.akamaihd.net/hls/live/571643/cuatro/bitrate_2.m3u8

En este caso el nombre del canal es Cuatro por lo que el tag es opcional (y por eso funciona) 

#EXTINF:-1 tvg-id="Cuatro.TDTChannelsEPG" tvg-logo="https://graph.facebook.com/cuatro/picture?width=320&height=320" group-title="Generalistas",Cuatro HD
https://livehlsdai-i.akamaihd.net/hls/live/571643/cuatro/bitrate_4.m3u8

En este caso el nombre es Cuatro HD que no se corresponde con el canal en EPG. Para que este EPG funcionará hay que añadir tvg-name="Cuatro" 

Más info aquí https://ss-iptv.com/en/users/documents/m3u

**Comment by LaQuay** [comment]
Hola, le doy una vuelta a esto. Miraré de hacerlo compatible con el script que utilizo para generar las listas.

**Comment by PIC16f841** [comment]
Arreglado desde que renombraste los canales en otro día. Muchas gracias

**Comment by LaQuay** [comment]
> Arreglado desde que renombraste los canales en otro día. Muchas gracias

Así es! Con tu comentario me replanteé parte del orden de canales y no le ví sentido a como estaba actualmente. Así que... Solucionado! 👍

**Comment by PIC16f841** [comment]
Has cambiado los nombres de los canales otra vez y fallan los EPG de los que ponen GEO o HD.

**Comment by PIC16f841** [comment]
![IMG_20200216_213006](https://user-images.githubusercontent.com/60220709/74613127-8f59cc00-5103-11ea-8950-6d0588c266da.jpg)

**Comment by LaQuay** [comment]
OH! Vaya. Le doy una vuelta de nuevo, me interesa que se llamen diferente.

**Comment by LaQuay** [comment]
Arreglado! Cierro
