### ISSUE TITLE
Canal no funciona: Antena3

### ISSUE THREAD

**Issue by XSkyManX** [LaQuay/TDTChannels#2615]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by LaQuay** [comment]
https://github.com/LaQuay/TDTChannels/issues/2614
