### ISSUE TITLE
Canal no funciona: La Sexta Neox

### ISSUE THREAD

**Issue by nortasuna** [LaQuay/TDTChannels#2616]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>                
        Se queda CARGANDO...
bloqueado..

**Comment by LaQuay** [comment]
https://github.com/LaQuay/TDTChannels/issues/2614
