### ISSUE TITLE
Canal no funciona: Ninguno, carga la lista pero no reproduce el contenido

### ISSUE THREAD

**Issue by pablogarcialandeira** [LaQuay/TDTChannels#2618]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
La aplicacion carga pero el contenido de los canales no 
<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by pantera72** [comment]
También me ocurre a mí no me carga nada todo en blanco porque

**Comment by LaQuay** [comment]
https://twitter.com/tdtchannels/status/1591521733588275203
