### ISSUE TITLE
No funciona

### ISSUE THREAD

**Issue by JulianGomez943** [LaQuay/TDTChannels#2619]
No carga ningún canal y da este mensaje 
Algo fue mal
La lista no ha podido ser descargada

**Comment by JulianGomez943** [comment]
No carga ningún canal y da este mensaje
Algo fue mal
La lista no ha podido ser descargada

**Comment by JulianGomez943** [comment]
No funciona No carga ningún canal y da este mensaje
Algo fue mal
La lista no ha podido ser descargada

**Comment by JulianGomez943** [comment]
No carga ningún canal y da este mensaje
Algo fue mal
La lista no ha podido ser descargada

**Comment by pantera72** [comment]
No descarga lista de canales lo tengo en banco y pone error de conesion porque alguien puede explicar de los dueños de la aplicación
