### ISSUE TITLE
No descarga la lista de canales

### ISSUE THREAD

**Issue by JulianGomez943** [LaQuay/TDTChannels#2620]
Da un mensaje de error. Algo fue mal. La lista no ha podido ser descargada

**Comment by pantera72** [comment]
A mí también me ocurre porque

**Comment by jfranmarco2** [comment]
A mi también me pasa.

**Comment by Karlos-agp** [comment]
Desde el día 12 nov por la noche, igual. No muestra lista

**Comment by LaQuay** [comment]
https://github.com/LaQuay/TDTChannels/issues/2618
