### ISSUE TITLE
No descarga lista. No funciona 

### ISSUE THREAD

**Issue by Chuso1982** [LaQuay/TDTChannels#2621]
Hola.
Llevo 2 días que no funciona la app. Pone que la lista no ha podido ser descargada. Tengo la última versión de la app, la he vuelto a descargar por si acaso y sigue sin funcionar.

¿Hay solución?
![Screenshot_2022-11-13-13-10-56-777_laquay com canalestdt](https://user-images.githubusercontent.com/118110839/201521333-35536958-8ee5-42d4-829d-163b3e0fd029.jpg)
![Screenshot_2022-11-13-13-11-03-287_laquay com canalestdt](https://user-images.githubusercontent.com/118110839/201521348-125688bf-f8f2-47a9-9bae-fc399f8619d1.jpg)

**Comment by Yogamiau** [comment]
Estoy igual 😭

**Comment by pablogarcialandeira** [comment]
Yo ta,mbien estoy igual y ayer abri una incidencia y me la han dado por cerrada, la aplicacion no funciona, hay alguna solucion __

**Comment by LaQuay** [comment]
https://github.com/LaQuay/TDTChannels/issues/2618
