### ISSUE TITLE
Canal no funciona: todos

### ISSUE THREAD

**Issue by Elbicho23** [LaQuay/TDTChannels#2623]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by rajputroo** [comment]
Hace 3 días ningún canal no descarga ni funciona cuando abro la app tdtchannels. Además realicé una donación y tampoco funciona esta app. Por favor soliciona lo antes posible. Mil gracias.

**Comment by atnbueno** [comment]
https://twitter.com/tdtchannels/status/1591521733588275203

**Comment by jcolladosp** [comment]
nadie tiene un backup de las listas antes de cerrar?

**Comment by Rust1667** [comment]
Aqui hay un backup: https://notabug.org/Glamorous6584/TDTChannels-Archive

**Comment by jcolladosp** [comment]
Para quien solo le interese la radio: https://www.radio-browser.info/search?page=1&order=clickcount&reverse=true&hidebroken=true&countrycode=ES

Ahi podeis encontrar listas de radio bastante completas en varios formatos

**Comment by rajputroo** [comment]
Buenos días, me gustaría saber cómo puedo solucionar la app de
TDTChannels en mi móvil con el enlace de backup que usted me ha enviado (
https://notabug.org/Glamorous6584/TDTChannels-Archive ). No sé cómo
solucionarlo con este enlace. Gracias y quedo a su respuesta.

Saludos cordiales,
M E Hassan Raj
Barcelona
