### ISSUE TITLE
Canal no funciona: 7nn

### ISSUE THREAD

**Issue by gasolini** [LaQuay/TDTChannels#2624]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by gasolini** [comment]
Solo saca el logo, sin embargo en la web si emite.
Alguien sabe la nueva URL para enigma 2?

**Comment by nachocorreo** [comment]
Ese link ha quedado en bucle...
Ahora el que funciona para ver 7nn es:
https://dxf45ob769xpw.cloudfront.net/out/v1/90ce358337e14be3bb82b6566b50a8b1/index.m3u8

**Comment by LaQuay** [comment]
Aplicado en https://github.com/LaQuay/TDTChannels/commit/0d810d211590d048ced68ff1ea7f275c0b364cc1
