### ISSUE TITLE
Enlace de lista m3u no funciona

### ISSUE THREAD

**Issue by killo3967** [LaQuay/TDTChannels#2628]
He intentado descargar el enlace de m3u

https://www.tdtchannels.com/lists/tv.m3u

Y no funciona

**Comment by Rust1667** [comment]
Aqui hay un backup: https://notabug.org/Glamorous6584/TDTChannels-Archive

**Comment by killo3967** [comment]
Gracias, lo probaré.

**Comment by killo3967** [comment]
Muchas gracias, pero no me valen, son antiguos. Por ejemplo el enlace del Toro TV no se ha actualizado.

De todas formas como  he dicho antes muchas grascias.
