### ISSUE TITLE
No carga lista de canales

### ISSUE THREAD

**Issue by JM-MRT** [LaQuay/TDTChannels#2642]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by SimonBlancoE** [comment]
Alguna alternativa?

**Comment by LaQuay** [comment]
https://twitter.com/tdtchannels/status/1606781816588980224
