### ISSUE TITLE
Application vacia de canales tdt o radio

### ISSUE THREAD

**Issue by ericgimenez** [LaQuay/TDTChannels#271]
Buenos dias, abro la aplication y tengo una pantalla blanca tanto en radio que en television, todos los canales han desaparecido, vengo aqui para descargar los m3u y no estan o vacios.
Si alguien puede ayudarme :/ estoy en francia y era perfecto para ver los canales de espana.
Muchas gracias

**Comment by LaQuay** [comment]
Hola! Disculpa, esta mañana he estado retocando todo el proyecto. Lo estoy migrando a un dominio mejor. La app debería funcionarte ya y las listas están subidas.

Gracias!

**Comment by ericgimenez** [comment]
youpi han vuelto :)
muchas gracias
