### ISSUE TITLE
Canal no funciona: CMM

### ISSUE THREAD

**Issue by stef85271** [LaQuay/TDTChannels#2759]
Castilla la mancha media does not function anymore. It seems they have changed the CDN API backend.

Here is an alternative url 👍 

https://cdnapisec.kaltura.com/p/2288691/sp/228869100/playManifest/entryId/1_w9e95evt/protocol/https/format/applehttp/flavorIds/1_4h5yhwgv,1_pio2o58x,1_s3dc6p0p/a.m3u8

Let me know if that url works for you

**Comment by stef85271** [comment]
The url above has been working for 48 hours but now it's over.
Here is another url, assuming this will stop working in 48 hours too :

https://cdnapisec.kaltura.com/p/2288691/sp/228869100/playManifest/entryId/1_01fn4ycl/protocol/https/format/applehttp/flavorIds/1_d2eonh9z,1_s6952vtf,1_fbkg5j4n/a.m3u8

**Comment by stef85271** [comment]
After some additional research, it turns out that the reason the CMM stream link expires is because it includes an expirable item, known as the kaltura player id. Above we have 1_w9e95evt. We also have 1_01fn4ycl.
What is needed is to grab this expirable item somehow from the CMM website and then build the link above dynamically so it becomes a consumable M3U8 link that works all the time.

**Comment by trincowski** [comment]
> After some additional research, it turns out that the reason the CMM stream link expires is because it includes an expirable item, known as the kaltura player id. Above we have 1_w9e95evt. We also have 1_01fn4ycl. What is needed is to grab this expirable item somehow from the CMM website and then build the link above dynamically so it becomes a consumable M3U8 link that works all the time.

The channel is working again.
