### ISSUE TITLE
Lista sin canales geo

### ISSUE THREAD

**Issue by Dekih** [LaQuay/TDTChannels#276]
No sé si sería posible que subieseis la misma lista pero solo con 1 opción por canal, ya que es incómodo que salga varias veces el mismo canal. Gracias de antemano.

**Comment by LaQuay** [comment]
Hola, no tenemos previsto hacerlo.

**Comment by PIC16f841** [comment]
@LaQuay esta funcionalidad sería útil para los que vemos los canales en el extranjero pero entiendo que no quieras mantener otro fichero más. Si los canales geo estuvieran etiquetados en el id de alguna manera, se podría genera el archivo dinámicamente con un script que borrara los geo.

**Comment by LaQuay** [comment]
@PIC16f841 Buenas, correcto. Por el momento no lo mantengo ya que serían más ficheros a mantener, uno por cada lista. De momento hay los que se ven en la pestaña inicial.
Por que si empiezo a granularizar, porqué no hago un m3u8 por comunidades? Por ejemplo.
