### ISSUE TITLE
Ten y dkiss ya tienen m3u8

### ISSUE THREAD

**Issue by ALBERTO580** [LaQuay/TDTChannels#277]
Hola. Me pongo en contacto con ustedes para decirles que ten y dkiss ya tienen m3u8. Les dejo los enlaces por si quieren añadirlos a la lista.
Ten: http://91.126.141.201:1935/live/ten/.m3u8
Dkiss: http://91.126.141.201:1935/live/kiss/.m3u8
Muchas gracias

**Comment by LaQuay** [comment]
Hola Alberto, pintan un poco mal esos canales. Los has sacado de la web oficial?

**Comment by ALBERTO580** [comment]
Los he sacado de una web de ver televisión

**Comment by LaQuay** [comment]
Hola, los enlaces no son oficiales por lo que no podemos incluirlos en el proyecto. Gracias!
