### ISSUE TITLE
Canal no funciona: XTREMA FM Asturias

### ISSUE THREAD

**Issue by pedrytus** [LaQuay/TDTChannels#2821]
El streaming actual funciona pero no se corresponde con el Xtrema FM. Os dejo el correcto para actualizarlo.

<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
**Web:** https://www.xtremafm.es

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
**Streaming:** https://server1.radiocast.es/listen/xtrema_fm/xtrema_ext

**Comment by LaQuay** [comment]
Gracias por el aviso @pedrytus , durante este fin de semana lo solucionaremos.
