### ISSUE TITLE
Añadir canal de radio: Ràdio UPV, de Valencia

### ISSUE THREAD

**Issue by wimiti** [LaQuay/TDTChannels#283]
Hola:
Estaría bien que se añadiera para la siguiente revisión de canales de rádio, el canal de la RTV de la Universitat Politècnica de València: http://www.upv.es/rtv/radio/directo. El flujo de stream parece que va por rtmp://moneres.upv.es/radioupv/livestream, al menos por aquí lo puedo reproducir en el reproductor VLC del PC.
Antes emitían también un canal de TV pero ahora solo cuelgan vídeos, que yo sepa.
Gracias.

**Comment by LaQuay** [comment]
Hola, es posible que no emitan las 24h?
Estoy intentando probarla y no me carga la emisión en la web.

**Comment by wimiti** [comment]
Vaya! No me había dado cuenta. Por el 102.5 FM sí que se sintoniza todo el día (soy un nostálgico de la FM). Parece que hay problema en la página web. Voy a ver si se lo hago saber. Pero, cuando no puedo sintonizar, lanzo el streaming por RTMP que te indico, y ese sí que funciona.
En cualquier caso, les reporto y sigo comentando.

**Comment by LaQuay** [comment]
Vale, he visto que la web está rota. Pero en el código fuente hay "rtmp://moneres.upv.es/radioupv/livestream" que supongo que es el stream.
Por el momento no tenemos ninguno rtmp en la lista. Miro a ver como añadirlo.

**Comment by wimiti** [comment]
> Vale, he visto que la web está rota. Pero en el código fuente hay "rtmp://moneres.upv.es/radioupv/livestream" que supongo que es el stream.

Así es, ese es el URL que se descubre en el código fuente de la página, y que te comenté en el primer mensaje que funciona en VLC, por ejemplo.

> Por el momento no tenemos ninguno rtmp en la lista. Miro a ver como añadirlo.

Un nuevo reto pues. Ánimo. Veré si encuentro algo que te pueda ayudar. Comentar que en VLC lo reproduce como streaming de vídeo. Probaré a añadirlo a la lista m3u8 que generáis y reproducirlo desde el _addon_ de Kodi.

Por otro lado comentarte que les puse una incidencia reportando el mal funcionamiento, como ya comenté, y recientemente me han contestado que ya funciona ¿?
Tras volver a probar y ojear de nuevo el código fuente de la página veo que todo sigue igual y SIGUE SIN FUNCIONAR el reproductor integrado (sí el rtmp://... desde VLC). Pero me he dado cuenta que siempre intento reproducirlo en un Firefox en Linux. Tampoco funciona con Chromium, y tal. Pero si lo hago desde un Windows (en un Firefox con Flash), voilà, SÍ QUE FUNCIONA. En fin, tecnologías... Cuándo descubrirán el HTML5?

**Comment by LaQuay** [comment]
@wimiti Hola! Miro de incluirlo como radio. Se ha probado en varios reproductores y funciona 👍
