### ISSUE TITLE
Enlaces duplicados canales Super 3 y C33

### ISSUE THREAD

**Issue by vggonz** [LaQuay/TDTChannels#287]
Hola!
Los enlaces del canal Super 3 son los mismos que los del canal C33 😔
Un saludo y enhorabuena por el currazo!

**Comment by HelmerLuzo** [comment]
[.....]
"la programación infantil del Super3 y la cultural del canal 33 se emitirán en el mismo canal "de forma adecuada a los horarios de consumo de cada uno de los contenidos", según la CCMA"
[.....]

También es cierto que se podría mirar de dejarlo en uno solo.

**Comment by LaQuay** [comment]
Gracias a los dos por el dato!
Se podrían unir, sí. Pero entonces... Qué logo se deja?

**Comment by LaQuay** [comment]
Cierro, se usa uno u otro pero mantenemos separados por tema de logos.
