### ISSUE TITLE
No carga canales

### ISSUE THREAD

**Issue by tetradog** [LaQuay/TDTChannels#288]
Por alguna razón no me carga desde hace tiempo los canales...

haciendo eso que me decís (desinstalar, reiniciar y reinstalar) me vuelve a ir bien :) gracias

**Comment by pipcr2** [comment]
Tengo el mismo problema. He probado a actualizar a la última versión 0ero la lista aparece sin canales. Hay alguna forma de incluirlos manualmente?

**Comment by pipcr2** [comment]
Al final forcé la parada de la aplicación, reinstalé la última versión y reinicie el móvil. Ahora si me aparecen los canales
