### ISSUE TITLE
La 1

### ISSUE THREAD

**Issue by apynet** [LaQuay/TDTChannels#29]
La 1 cambia sus direcciones de stream durante el día y el que hay puesto no funciona correctamente.
El enlace de telecinco entra en bucle.
Estos son los enlaces:
http://rtvev4-live.hss.adaptive.level3.net/egress/ahandler/rtvegl7/la1_lv3_aosv4_gl7/la1_lv3_aosv4_gl7.isml/la1_lv3_aosv4_gl7-audio=128000-video=650000.m3u8

http://rtvev4-live.hss.adaptive.level3.net/egress/ahandler/rtvegl7/thd_lv3_aosv4_gl7/thd_lv3_aosv4_gl7.isml/thd_lv3_aosv4_gl7-audio=128000-video=2800000.m3u8

GEO:
http://rtvev4-live.hss.adaptive.level3.net/egress/ahandler/rtvegl1/la1_lv3_aosv4_gl1/la1_lv3_aosv4_gl1.isml/la1_lv3_aosv4_gl1.m3u8

**Comment by LaQuay** [comment]
Estos enlaces también caducan verdad? Gracias!
