### ISSUE TITLE
Canal no funciona: CMM Radio

### ISSUE THREAD

**Issue by teofilom3d** [LaQuay/TDTChannels#2952]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
https://cdnapisec.kaltura.com/p/2288691/sp/228869100/playManifest/entryId/1_hphqvgg7/format/applehttp/.m3u8

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://cdnapisec.kaltura.com/p/2288691/sp/228869100/playManifest/entryId/1_xfwsgzdj/format/applehttp/.m3u8

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by LaQuay** [comment]
Se arregló aquí, https://github.com/LaQuay/TDTChannels/commit/a464c11ec5fbb72ba9b5a081e8a67fe0455831ec. Gracias.
