### ISSUE TITLE
Dkiss

### ISSUE THREAD

**Issue by apynet** [LaQuay/TDTChannels#3]
El canal Dkiss no es en directo es un video que se repite todo el rato al reproducir el m3u.
También, no está la 2.

**Comment by LaQuay** [comment]
@apynet El canal DKiss no lo tengo ni con m3u8 ni con enlace web ahora mismo. A qué te refieres?

Sobre La 2, cuando pueda probar que sacan un m3u8 que funcione, lo añado. El último que salió lo sacaron ya, y cada vez que intento ver el nuevo están emitiendo un contenido geobloqueado, así que no puedo comprobarlo.

**Comment by apynet** [comment]
El real madrid tv que hay, no es Real Madrid Tv, es telemadrid

**Comment by LaQuay** [comment]
@apynet Gracias por el aviso. He aprovechado y ahora hay la versión en español y la versión en inglés.

Pero, qué comentabas de DKISS?

**Comment by apynet** [comment]
No se ve en directo, es como un video en bucle.
La 1, se ve con 5 horas de retraso... en sus dos m3u

**Comment by LaQuay** [comment]
@apynet Pero es que no entiendo que comentas sobre **DKiss, no está en la lista**.

He comprobado los enlaces de La 1 y siguen siendo los que da TVE como oficiales. Además, también he comprobado que van en "directo". Lo que si que puede ocurrir es que en momentos puntuales tengan Geobloqueo, y para no cortar emisión lo que hacen es bucle de las ultimas emisiones.

**Comment by LaQuay** [comment]
@apynet La doy por cerrada.
