### ISSUE TITLE
Canal no funciona: Onda Regional de Murcia

### ISSUE THREAD

**Issue by teofilom3d** [LaQuay/TDTChannels#3046]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
https://www.orm.es/directo/orm/

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://crmlive.redctnet.es/liveedge/orm/orm/playlist.m3u8

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by LaQuay** [comment]
Hola, debería estar funcionando, de no ser así, comentalo, gracias!
