### ISSUE TITLE
Euronews + Popular TV Melilla

### ISSUE THREAD

**Issue by paurg15** [LaQuay/TDTChannels#31]
He encontrado el directo de Euronews y este es el m3u8 que he podido sacar: https://euronews-es-b7-cdn.hexaglobe.net/d0381450f8d472663a50b300950f477f/5bb8c1a8/euronews/euronews-euronews-website-web-responsive-2/ewnsabresbkp_spa.smil/ewnsabresbkp_spa_720p.m3u8
Y el de Popular TV Melilla: https://5940924978228.streamlock.net/8009/8009/chunklist_w1880638743.m3u8

**Comment by LaQuay** [comment]
Lo dejo unos días por aquí para probar si son estables. Gracias!

**Comment by LaQuay** [comment]
La de Euronews no es estable, cambia. La de Popular TV Melilla sigue funcionando, la añado. Gracias
