### ISSUE TITLE
Canal no funciona: Radio Montecarlo Italia

### ISSUE THREAD

**Issue by lcapriotti** [LaQuay/TDTChannels#3109]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
https://www.radiomontecarlo.net/sezioni/11995/tv

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://live2.msr.cdn.mediaset.net/content/hls_h0_clr_vos/live/channel(bb)/index.m3u8

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by LaQuay** [comment]
Hola, está funcionando. De no ser así, comentalo. Gracias!
