### ISSUE TITLE
No tv channels what so ever. 

### ISSUE THREAD

**Issue by dbmc06** [LaQuay/TDTChannels#312]
Tried to check on Google play but seems the app is no  longer available

**Comment by LaQuay** [comment]
You are talking about the Android APP, right?
This issue should be in the TDTChannels-APP repository. https://github.com/LaQuay/TDTChannels/.

Although, you are using an outdated version of the app. Update to the latest one.

**Comment by dbmc06** [comment]
Thanks for your reply.

The app is no longer available on Google play store.

Any secure link I can download it?

Many thanks

**Comment by LaQuay** [comment]
Check the link I attached before.

**Comment by dbmc06** [comment]
I did. Reason why I ask you. Was unable to find where to download the app
since no longer available at Google play store.

Link you sent me does not show where to download the pdk
