### ISSUE TITLE
Canal Sur Andalucía

### ISSUE THREAD

**Issue by usuarionuevor** [LaQuay/TDTChannels#32]
Hace ya unos días que han quitado el streaming de Canal Sur Andalucía y lo han pasado a YouTube, pero hacen uno nuevo cada día asique el link también cambia a diario

este es el de hoy (12 octubre) https://www.youtube.com/watch?v=7fkOmk8Ivgc

pd: los links que genera youtube-dl en *.m3u8 tampoco sirven de mucho ya que llevan ip y no habría uno universal (que yo sepa) :(

edit: el link de Chiclana que hace tiempo que no va este es el nuevo: https://5940924978228.streamlock.net/8289/smil:8289.smil/master.m3u8

**Comment by usuarionuevor** [comment]
SOLUCIONADO: https://github.com/LaQuay/TDTChannels/issues/34
Podemos cerrar este

**Comment by LaQuay** [comment]
Gracias, me paso por el otro y actualizo
