### ISSUE TITLE
Disney Channel down?

### ISSUE THREAD

**Issue by malvinas2** [LaQuay/TDTChannels#323]
Alguien sabe lo que paso al Disney Channel? 
El link de la lista no funciona: 
http://cdnapi.kaltura.com/p/1068292/sp/106829200/playManifest/entryId/1_d8lnsqu0/format/applehttp/master.m3u8

**Comment by LaQuay** [comment]
Hola, Disney Channel ha dejado de emitir online. Con la llegada de Disney+.

**Comment by malvinas2** [comment]
A quién le corresponde: 
El sitio web alemán es más informativo, donde publicaron un 'comunicado oficial', diciendo algo como: 

_Estimados fanáticos, nos gustaría informarles que la aplicación de Disney Channel, la transmisión en vivo y todos los episodios se suspenderán aquí en el sitio web el 6 de marzo.
Gracias por usar estas ofertas. Esperamos que sigas divirtiéndote con tus series y videos favoritos de Disney en YouTube en youtube.com/disneychannelde._

Creo que no hace falta comentar dicha decisión... 

Fuente: [https://imgur.com/QQ6ost3](https://imgur.com/QQ6ost3)
