### ISSUE TITLE
Canal no funciona: Dmax

### ISSUE THREAD

**Issue by wuniversales** [LaQuay/TDTChannels#3243]
URL de la emision
https://dmax.marca.com/en-directo

Actualmente la app de TDT Channels muestra la siguiente URL obsoleta.
https://es.dplay.com/dmax/

Hay que cambiarla por la de arriba y a ser posible extraer su m3u8 y demás... Y si se abre mediante la app directamente sin abrir la web ya lo bordais...
¿Tal vez se pueda incluir el epg también?
Saludos

**Comment by LaQuay** [comment]
Actualizado con el embebido. El EPG ya estaba. Gracias 👍
