### ISSUE TITLE
Android TV

### ISSUE THREAD

**Issue by DanielRoig** [LaQuay/TDTChannels#3287]
No se puede poner ningún canal a pantalla completa. Al entrar a un canal se puede ver la previsualización del video en directo pero es imposible ponerlo en grande. No hay ningún botón para hacerlo

**Comment by LaQuay** [comment]
Hola, puedes adjuntar una imagen? Gracias

**Comment by DanielRoig** [comment]
![photo_2023-12-01_22-04-15](https://github.com/LaQuay/TDTChannels/assets/11554412/4e78d36a-6114-4786-8055-d27cd2051285)

**Comment by DanielRoig** [comment]
![photo_2023-12-02_18-31-51](https://github.com/LaQuay/TDTChannels/assets/11554412/f649f01a-d51a-462c-acb4-cb1a7f695b9f)

**Comment by DanielRoig** [comment]
A parte de esto, todos los canales de mediaset y de atresmedia no funcionan en la tv. Si en mobile.

Hay alguna manera de colaborar en el proyecto? Creo que la app para tv es muy inestable y quizas podria echar una mano. Un saludo

**Comment by LaQuay** [comment]
> ![photo_2023-12-02_18-31-51](https://github.com/LaQuay/TDTChannels/assets/11554412/f649f01a-d51a-462c-acb4-cb1a7f695b9f)
> 

En la segunda linea cambia TV por Radio. 

El problema está en que estás accediendo mediante la parte pensada para la Radio, le das al botón de TV e irá bien.

**Comment by DanielRoig** [comment]
Ahora funciona muy bien incluso atresmedia y mediaset! Muchas gracias!

Como feature que echo de menos es poder saltar de canal con el mando sin tener que volver al listado de canales.

Felicidades por el trabajo
