### ISSUE TITLE
Canal no funciona: TVG (Galicia)

### ISSUE THREAD

**Issue by Zebrone1** [LaQuay/TDTChannels#3312]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

http://www.crtvg.es/tvg/tvg-en-directo/canle/galicia-tv-europa

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

I can find it in the files but it cannot be founded in the playlist, it works on the website, i'm using the m3u8/m3u file

**Comment by LaQuay** [comment]
It is working properly: https://www.tdtchannels.com/television/TVG.
