### ISSUE TITLE
Duda!

### ISSUE THREAD

**Issue by andrenda93** [LaQuay/TDTChannels#332]
Lo primero decirte que eres un máquina! 

Pero yendo al grano, me pasa que he instalado la aplicacion en mi tv box engel mediante un USB, pero parece que dependo completamente de un explorador de archivos para acceder a la app cada vez que quiero ver un canal. No se si ese es el funcionamiento regular de la app pero si hay alguna manera de instalar la app en la rama interna del tv box me gustaria contar con ella! Y bueno, por ultimo, al navegar por los canales no se distingue sobre que canal pulsa OK para acceder entonces está un poco a tantas! Lo demás, de cine!

**Comment by LaQuay** [comment]
Hola!
Sobre la duda del Engel. Pues ni idea... Pruebate a pasar por nuestro Telegram y lo comentas, a ver si alguien te puede ayudar: https://t.me/tdtchannels

Referente a lo de la navegación, tomo nota 👍
