### ISSUE TITLE
Más canales nuevos (internacionales)

### ISSUE THREAD

**Issue by usuarionuevor** [LaQuay/TDTChannels#339]
el garage tv (Argentina)
http://186.0.233.76:1935/Garage/garage.smil/.m3u8
web http://elgarage.com/

ms motor tv (Italia)
https://streaming.wim.tv/live/streamingautomototv/.m3u8
web http://www.msmotor.tv/

only motors
https://kapang000.broadcastcdn.net/kapanglivetv-playout-onlymotors/index.m3u8
web https://kapang.com/onlymotors/

edge sports
https://edgesports-roku.amagi.tv/ingest/playlist.m3u8
web https://www.edgesport.com/

infowars (US)
https://infostream.secure.footprint.net/hls-live/infostream-infostream/_definst_/live.m3u8
web https://www.infowars.com/

No conozco muy bien el funcionamiento de github pero se pueden poner tags o algo parecido?
Lo digo porque no se muy bien como clasificarlos si como deportivos o internacionales… porque redbull está en deportes pero quizas deberia estar en internacionales? (o no)

pd: no conocia Arirang, es muy interesante gracias por seguir actualizando ;)

**Comment by LaQuay** [comment]
Hola! Muchas gracias, le doy una vuelta en cuanto pueda 👍

**Comment by LaQuay** [comment]
Hola! 
Únicamente en InfoWars he podido ver el stream en la web funcionando. Pero me he informado y es una web de fake news (https://en.wikipedia.org/wiki/InfoWars), así que no le veo el sentido añadirla...

A las otras, podrías pasar el enlace exacto donde se puede comprobar que emitan vía web? Gracias!

Sobre la pregunta de los TAGs. No hay concepto de tags de per se, es algo que he "inventado" yo para esta lista. Y normalmente los categorizamos por "categoría" a menos que no sean de España que entonces van a Internacionales directamente, sean de la categoria que sean. Sabemos que aquí hay punto de mejora, pero es dificil.

**Comment by usuarionuevor** [comment]
LOL entonces quita todos los canales de noticias... eso no tiene sentido es solo un canal más... pero bueno es tu decisión.

el garage tv --> http://elgarage.com/tv-en-vivo/

only motors sale directamente en el enlace que he puesto, eso si, despues de la publicidad..

otros requiere registrarse en la página pero el link es el oficial



por cierto Radio Planeta ha actualizado: https://radioplaneta.emitironline.com

**Comment by LaQuay** [comment]
Buenas,
Añado garagetv, msmotors y onlymotors. https://github.com/LaQuay/TDTChannels/commit/a2b8cf5fb10c9d6590fdcd5b8c20afb581192b99

Los demás por A o B no cumplen con el proyecto.

Gracias por el aviso de la radio!
Sobre las categorias, es un problema que tenemos de hace tiempo. El tema está en que las categorías son únicas, no puedes tener un enlace con dos categorias por que no hay forma física de verlo sin duplicar info...
