### ISSUE TITLE
Canal no funciona: Cuatro / Antena 3 (Mediaset / Atresmedia)

### ISSUE THREAD

**Issue by Numeritxs** [LaQuay/TDTChannels#3390]
URL original: https://www.mitele.es/directo/cuatro
URL original: https://www.atresplayer.com/directos/antena3/ 

Parece que estos canales han dejado de funcionar en formato W3U (Wiseplay).

**Comment by LaQuay** [comment]
Hola, según veo funcionan correctamente. Saludos!
