### ISSUE TITLE
error https en Kodi con Windows Siete x64

### ISSUE THREAD

**Issue by Cixert** [LaQuay/TDTChannels#3413]
Hola, cuando añado las listas M3U8 en Kodi a través de la extensión Playlistloader, me sucede en Windows Siete x64 que me da error https. No me sucede con la misma instalación en Windows Ocho y 10 (tengo Kodi 20.3 portable).
Actualicé los certificados Let's Encrypt y solo tras reiniciar funcionó, pero volví a añadir las listas IPTV de nuevo y otra vez que no funciona.
¿Qué motivo puede ser?
Y por curiosidad ¿la guía EPG tiene que ser específica de la lista IPTV o vale cualquiera?
Dejo el log del error:
https://paste.kodi.tv/agamojebim
Gracias.

**Comment by Cixert** [comment]
There is a problem with the dependence "Cloud Drive Common Module".
https://github.com/cguZZman/script.module.clouddrive.common/issues/24
The Magellan's error is also solved by installing the optional dependence "CloudScraper2".

**Comment by Televito** [comment]
Estás dando la respuesta en la misma consulta. Windows 7 no tiene soporte de ningún tipo desde 2020. Cambia de S.O

**Comment by LaQuay** [comment]
> Estás dando la respuesta en la misma consulta. Windows 7 no tiene soporte de ningún tipo desde 2020. Cambia de S.O

Gracias! Cierro
