### ISSUE TITLE
Telemadrid ==> new stream link

### ISSUE THREAD

**Issue by stef85271** [LaQuay/TDTChannels#3414]
Hello

Telemadrid is not working since yesterday (tuesday 6, feb 2024). But I have found that the reason it's not working is that the Telemadrid stream is now served through Akamai CDNs.

Here is the new stream link :

https://telemadrid-23-secure2.akamaized.net/master.m3u8

Hope it helps.

**Comment by LaQuay** [comment]
Was fixed here: https://github.com/LaQuay/TDTChannels/commit/034f26fa4f454aa5808d5a18545f27d40fbb2dd6

Thanks!
