### ISSUE TITLE
Canal no funciona: 101tv Costa del Sol

### ISSUE THREAD

**Issue by joaquinito2070** [LaQuay/TDTChannels#3437]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal>
https://www.101tv.es/

<En caso de saberlo indica debajo de esta linea la URL de la emision>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
El canal 101tv costa del sol no funciona.

**Comment by LaQuay** [comment]
Parece que tienen un problema de certificado, si.
