### ISSUE TITLE
Añadir radios de Shoutcast

### ISSUE THREAD

**Issue by wuniversales** [LaQuay/TDTChannels#344]
Hay muchisimas radios, todas disponibles en los formatos "m3u, pls y xspf", además están categorizadas :)
Creo que seria bueno añadirlas todas.
https://directory.shoutcast.com/

**Comment by LaQuay** [comment]
Hola! Gracias!

**Comment by LaQuay** [comment]
Hola! Esto sigue funcionando? He entrado a probar y no me va ninguna de las más escuchadas, se queda en bucle cuando le doy _play_.

**Comment by LaQuay** [comment]
Voy a cerrar la issue. Siguen sin cargarme...

**Comment by wuniversales** [comment]
> Hola! Esto sigue funcionando? He entrado a probar y no me va ninguna de las más escuchadas, se queda en bucle cuando le doy _play_.

Parece que no, que raro...
