### ISSUE TITLE
Añadir la guía de TV a la web (Aporte)

### ISSUE THREAD

**Issue by wuniversales** [LaQuay/TDTChannels#345]
Aquí tienes, añádelo a tu gusto :)
https://www.tvguia.es/webmaster/parrilla-tv-3-horas

**Comment by LaQuay** [comment]
Hola!
Embeberla no creo que lo haga, pero tengo en mente hacer algo personalizado para el proyecto 👍

**Comment by malversan** [comment]
Para mí que esa web la actualizan lanzando los dados.

Mirando la programación de ahora mismo, no coincide ni un solo programa que estén emitiendo en este instante. En ningún canal. Pero es que ni uno.

**Comment by LaQuay** [comment]
Ya hay información EPG! En un futuro pondré las siguientes emisiones y etc. Cierro!
