### ISSUE TITLE
Cambiar link de canales catalanes a "master.m3u8"

### ISSUE THREAD

**Issue by wuniversales** [LaQuay/TDTChannels#347]
Lo dicho, en vez de usar "playlist_DVR.m3u8", utilizar "master.m3u8"

Canales a aplicar el cambio:
TV3
Esport 3
Super 3
33
CCMA Exclusiu 1
CCMA Exclusiu 2

**Comment by LaQuay** [comment]
Hola! Por algún motivo en concreto?
La web de CCMA da el "playlist.m3u8" y el "playlist_DVR.m3u8" por defecto. Este segundo tiene las ventajas del DVR que, en principio, el master.m3u8 no tiene...

**Comment by wuniversales** [comment]
Bueno, entonces nada, gracias
