### ISSUE TITLE
Lista para enigma2

### ISSUE THREAD

**Issue by emanuelarico** [LaQuay/TDTChannels#36]
Existe la posibilidad de tener una lista para decodificador con enigma2? Muchas gracias!

**Comment by emanuelarico** [comment]
Es un formato para decoder:
Ejemplo:
`#NAME Lista
#SERVICE 4097:0:1:3:0:0:0:0:0:0:https%3a//mega-pull2a-a3player.secure.footprint.net/mega/bitrate_4.m3u8:MEGA
#DESCRIPTION MEGA

**Comment by LaQuay** [comment]
De momento no creo que lo implemente. Dejo la issue abierta pero.

**Comment by LaQuay** [comment]
Hecho!
Cuando puedas, pruebalo @emanuelarico. Gracias!

**Comment by LaQuay** [comment]
Cierro, en caso de tener algun problema, abridla de nuevo. Gracias!

**Comment by emanuelarico** [comment]
No, no me da ningún error. Voy a hacer un par de pruebas en modalidad Debug.
Igualmente, no funcionan algunos canales como La 1, supongo que sea porque estoy en el extranjero.

Añado ahora el iptv.sh qué va puesto en etc/enigma2 para actualización de lo script al boot (pero se puede también añadir al cron para tenerla actualizada todo lo día).

**Comment by miuipower** [comment]
Por que no le pasas el log se crea en root cuando sale pantalla azul

**Comment by miuipower** [comment]
@emanuelarico ya tengo funcionando los mediaset en enigma2 yo uso la imagen openld 3.3. Pero valla eso dará igual. tienes que instalar servicesapp. luego hay en services app tienes que cambiar el reproductor de vídeo audio que no sea por defecto. solo funciona con mediaset, exteplayer, e probado los otros y no los abre ya que este usa ffmpeg 3.2.4.entonces en la lista iptv tienes que cambiar el puerto de escucha por este que seria el 5002 cualquier cosilla me comentáis saludos

**Comment by emanuelarico** [comment]
> @emanuelarico ya tengo funcionando los mediaset en enigma2 yo uso la imagen openld 3.3. Pero valla eso dará igual. tienes que instalar servicesapp. luego hay en services app tienes que cambiar el reproductor de vídeo audio que no sea por defecto. solo funciona con mediaset, exteplayer, e probado los otros y no los abre ya que este usa ffmpeg 3.2.4.entonces en la lista iptv tienes que cambiar el puerto de escucha por este que seria el 5002 cualquier cosilla me comentáis saludos

Perfecto, funciona! Para el iptv.sh necesito un poco de tiempo, voi a añadir también las coordinadas para los picons.
