### ISSUE TITLE
Añadir emisora de radio: Pepe Radio

### ISSUE THREAD

**Issue by miguelangelgj** [LaQuay/TDTChannels#363]
Primero de todo Enhorabuena por la aplicación de Android. Me parece espectacular la gran cantidad de canales de tv y emisoras de radio que hay. Gran trabajo!!!!! Y segundo me gustaría que pudieras añadir la emisora Pepe Radio. En mi opinión tiene bastante variedad musical 
El stream es http://server10.emitironline.com:8000/stream y la web https://peperadio.es/
Un saludo

**Comment by miguelangelgj** [comment]
Se me había olvidado otra muy buena emisora que podría estar bien añadir a la aplicación. Se llama Tula Radio. Ponen buena música también. El enlace 
https://listen.radioking.com/radio/95137/stream/133672

**Comment by Nomenteros** [comment]
Miguel Angel: Gracias por tus comentarios ,y seria de gran ayuda que tus peticiones las formules en forma de Pull request , Abro PR en tu nombre y te animo a que colabores.Un saludo,Add Peperadio peticion @miguelangelgj #370

**Comment by miguelangelgj** [comment]
gracias a vosotros. lo tendré en cuenta para la próxima vez

**Comment by LaQuay** [comment]
Añadido en https://github.com/LaQuay/TDTChannels/pull/370.
