### ISSUE TITLE
Siguen sin funcionar (ACTUALIZADO 25-03-20)

### ISSUE THREAD

**Issue by chato99** [LaQuay/TDTChannels#367]
El Correo de Andalucía
http://common01.todostreaming.es/live/elcorreotv-livestream.m3u8

TeleAntequera
http://37.187.7.106/las4esquinastv/live.m3u8

TeleToledo
https://cdn01.yowi.tv/1H23S04G4M/master.m3u8

Aragón Deporte
https://cartv.streaming.aranova.es/hls/live/adeportes_deporte1.m3u8

Tindaya TV
https://streaming-fr02.enetres.net/0537FCE9817D4E9E930B6ED4D9C7BD5C021/smil:live.smil/master.m3u8

Canal 13 Digital
http://212.40.234.65/live/canal13/playlist.m3u8

Canal 10 TV
https://5940924978228.streamlock.net/8269/smil:8269.smil/master.m3u8

Información TV
http://teledifusion.tv:1935/informaciontvlive/informaciontvlive/master.m3u8

Latinos TV
https://5c21f7ec1999d.streamlock.net/8210/8210/playlist.m3u8

Popular TV La Rioja
https://live.vimeocdn.com/1569168790-0x88a43c7fe857571fea5dfd352188bc530b0dbcf7/f2c828c5-ea64-49bc-90bd-fd266f2bc4de/chunklist_b416000.m3u8

**Comment by LaQuay** [comment]
Hola! Este fin de semana le doy un vistazo. Gracias!

**Comment by LaQuay** [comment]
Buenas,
Correo -> OK
TeleAntequera -> Borrado
TeleToledo -> Borrado
Aragón Dep -> OK
Tindaya -> De momento la dejamos, parece que emite a veces.
Canal 13 -> De momento la dejamos, parece que emite a veces.
Canal 10 TV -> De momento la dejamos, parece que emite a veces.
Información TV -> Borrado
Latinos TV -> Borrado
Popular TV La Rioja -> OK, emite por Internet.

Cierro, gracias!
