### ISSUE TITLE
Añadir emisoras de radio:

### ISSUE THREAD

**Issue by palyss** [LaQuay/TDTChannels#371]
Añadir emisoras: Hola, podrían añadir las siguientes emisoras? 40 Guadix  Y cadena dial Andalucía este? Ambas de la provincia de Granada.
Les dejo sus enlaces sacados de la web del grupo Andalucía este radio. Los enlaces son oficiales ya que he contactado con ellos y me lo han confirmado.
Los 40 Guadix:
http://20873.live.streamtheworld.com:3690/LOS40_ASO_GUADIX_SC
Dial Andalucía este: http://streaming5.elitecomunicacion.es:8226/stream
Sigan con este magnífico proyecto. Saludos

**Comment by LaQuay** [comment]
Hola! Puedes enlazarme las webs? Gracias!

**Comment by palyss** [comment]
Cadena dial Andalucía este: dialandaluciaeste.com
40 Guadix: https://cadenaser.com/emisora/radio_guadix/ es la web de la ser de Guadix aunque también es web de 40 Guadix

**Comment by palyss** [comment]
Y andaluciaeste.es es de donde he conseguido los enlaces si te sirve

**Comment by LaQuay** [comment]
Le doy un vistazo, gracias!

**Comment by LaQuay** [comment]
En la siguiente actualización las tienes!
