### ISSUE TITLE
Canal no funciona: SER Lugo

### ISSUE THREAD

**Issue by teofilom3d** [LaQuay/TDTChannels#3753]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
https://cadenaser.com/radio-lugo/

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://playerservices.streamtheworld.com/api/livestream-redirect/SER_LUGOAAC.aac

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by LaQuay** [comment]
Hola, lo aplico, gracias!
