### ISSUE TITLE
Canal no funciona: Radio Galega

### ISSUE THREAD

**Issue by teofilom3d** [LaQuay/TDTChannels#3771]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
https://crtvg-radiogalega-hls.flumotion.cloud/playlist.m3u8

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://crtvg-radiogalega-hls.flumotion.cloud/playlist.m3u8

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
La cadena está duplicada en "Populares" y "Galicia", pero la que está en "Galicia" tiene "format": "mp3" (mal) y "Populares" tiene "format": "m3u8" (correcto)

**Comment by LaQuay** [comment]
Lo arreglo, gracias!
