### ISSUE TITLE
Lista de emisoras de radio

### ISSUE THREAD

**Issue by miguelangelgj** [LaQuay/TDTChannels#378]
Spektra FM: http://stm1.emiteonline.com:8008/spektrafm
http://www.spektrafm.es/index.php/es/

06AM Ibiza Underground Radio: https://streams.radio.co/sd1bcd1376/listen
https://www.06amibiza.com/

Espacio 4 FM: http://radiogestion.com:7003/mount3
https://www.espacio4fm.com/

MIX Fm Radio Tenerife: http://server6.20comunicacion.com:8064
https://www.mixfm-radio.com/

Si me podeis decir como se hace para hacer un pull request os lo agradecería por que la verdad es que estoy muy perdido. Lo he intentado de todas las maneras y no hay forma. Me gustaría saber los pasos que hay que hacer.

**Comment by LaQuay** [comment]
Hola! No te preocupes por la PR, con lo que has hecho ya nos sirve perfectamente. 

Tomo nota y le doy un vistazo cuando pueda, gracias!

**Comment by miguelangelgj** [comment]
Vale

**Comment by LaQuay** [comment]
Hola! Añadidas, gracias!
https://github.com/LaQuay/TDTChannels/commit/738f147d1c6ab6880f4944f06826fc893282f3cf
