### ISSUE TITLE
canales apagados

### ISSUE THREAD

**Issue by adamo331** [LaQuay/TDTChannels#38]
Algunos canales ya no funcionan FDF Energy Bemad ..... Creo que se agregaron algunos cambios a los enlaces m3u.

**Comment by LaQuay** [comment]
Hola! A qué te refieres?
En el apartado M3U8 o en el WEB?

**Comment by LaQuay** [comment]
En la sección M3U8 no aparecen esos canales, no entiendo a qué te refieres...

**Comment by adamo331** [comment]
Sé y propongo la pregunta si puedes agregar el m3u de estos canales tv

**Comment by LaQuay** [comment]
Hola, por el momento no es posible tener los M3U8 de Mediaset, al cambiar casi cada día.
