### ISSUE TITLE
Canal no funciona: Flaixbac

### ISSUE THREAD

**Issue by manelgmail** [LaQuay/TDTChannels#3802]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
https://flaixbac.cat/
<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://flaixbac.streaming-pro.com:8007/flaixbac.mp3

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
Error code: 503

Message: Resource temporarily unavailable..

Error code explanation: 503 - The server cannot process the request due to a high load.

**Comment by manelgmail** [comment]
Possible solucion
https://us-b4-p-e-zs14-audio.cdn.mdstrm.com/live-audio-aw/65afe517d47dc208abd053d2/playlist.m3u8

**Comment by Nomenteros** [comment]
Ya estan ambos cabales actualizados
