### ISSUE TITLE
SER Rioja

### ISSUE THREAD

**Issue by teofilom3d** [LaQuay/TDTChannels#3826]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
https://cadenaser.com/radio-rioja/

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://playerservices.streamtheworld.com/api/livestream-redirect/SER_RIOJAAAC.aac

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
Emite en AAC, no en MP3 como la anterior

**Comment by Nomenteros** [comment]
Ya esta actualizado el enlace.
