### ISSUE TITLE
TV.xml descarga mal.

### ISSUE THREAD

**Issue by hellishvictor** [LaQuay/TDTChannels#3836]
Hola, suelo descargar "[https://tdtchannels.com/epg/TV.xml](https://tdtchannels.com/epg/TV.xml)" para ver la programación en algún programa y va genial, pero desde hoy el enlace descarga "**TV.xml.gz**", no el "**TV.xml**" en texto plano.
Un saludo.

**Comment by LaQuay** [comment]
Hola, así es. Desde ayer el .xml ya no está disponible. Has de usar el .xml.gz. Es lo mismo, sólo hay que descomprimirlo.

https://x.com/tdtchannels/status/1811467635910905992

Saludos
