### ISSUE TITLE
Canal no funciona: OndaCero Radio

### ISSUE THREAD

**Issue by ferimer-dev** [LaQuay/TDTChannels#3859]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
https://www.ondacero.es/directo/

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://atres-live.ondacero.es/live/delegaciones/oc/cadena/master.m3u8

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by Nomenteros** [comment]
Están funcionando ambas emisiones correctamente y es la que oficialmente trasmite en su web, Si hicieron algún cambio seria por mantenimiento o cuestiones técnicas temporales.
