### ISSUE TITLE
Cuatro HD y Telecinco HD

### ISSUE THREAD

**Issue by saidma** [LaQuay/TDTChannels#4]
http://cuatro-mediaset-esp-live.secure.footprint.net/mediaset/cuatro/stream2/streamPlaylist.m3u8

http://telecinco-mediaset-esp-live.secure.footprint.net/mediaset/telecinco/stream2/streamPlaylist.m3u8

**Comment by LaQuay** [comment]
Los añado, gracias @saidma !
