### ISSUE TITLE
Canal no funciona: 101TV Málaga

### ISSUE THREAD

**Issue by teofilom3d** [LaQuay/TDTChannels#4026]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
https://www.101tv.es/endirecto101tv/

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://liveingesta318.cdnmedia.tv/101televisionlive/smil:rtmp01.smil/playlist.m3u8

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
Han cambiado la URL por la indicada. La actual no va
Como antes, hay que añadir en la llamada la cabecera 
Referer: https://player.instantvideocloud.net/

**Comment by LaQuay** [comment]
Hola, gracias por la información. Así lo hicimos. Saludos!
