### ISSUE TITLE
Cambiar la url de la radio COPE MIRAMAR (Barcelona)

### ISSUE THREAD

**Issue by sergialarconrecio** [LaQuay/TDTChannels#406]
Hola Buenas 

La url que tenéis no funciona, os paso la url que si funciona para que se escuche la emisora.

URL: https://wecast-m01-03.flumotion.com/copesedes/barcelona.mp3

Saludos.

**Comment by LaQuay** [comment]
Hola! No encuentro a cuál te refieres. Cómo se llama? Por Miramar no aparece ninguna en la lista, y la "COPE Barcelona" funciona...

Gracias!

**Comment by sergialarconrecio** [comment]
És la Cope Barcelona pero a mi no me funciona por la dirección que tenéis
actual y por la que os he enviado yo si funciona, la otra dirección da este
error en ingles "The file you requested could not be found" por eso quiero
que se cambie la dirección por la que envie.

Saludos.

**Comment by LaQuay** [comment]
Cierro, ya la incluí pero se me olvidó cerrar. Saludos!
