### ISSUE TITLE
Añadir emisoras de radio: Jazz Radio Bcn & Radio Sitges

### ISSUE THREAD

**Issue by miguelangelgj** [LaQuay/TDTChannels#411]
Jazz Radio Bcn: http://listen64.radionomy.com/JazzRadioBcn
Tasa de bits: 128kb/s
https://www.jazzradiobcn.com/

Radio Sitges: https://s2.radio.co/s8e5dffe5e/listen
Tasa de bits: 192kb/s
http://www.radiositges.com/

**Comment by playzzz** [comment]
Ya está la Pull Request (PR) hecha con esas emisoras pero te recomiendo buscar como hacer una PR en GitHub para que en futuro puedas proponer las emisoras que quieras por tu propia cuenta.

**Comment by miguelangelgj** [comment]
gracias. me miraré mejor el tema de los pull request a ver si de una vez consigo poder hacerlos. de momento he sido incapaz

**Comment by playzzz** [comment]
Esta issue puede cerrarse
