### ISSUE TITLE
TDT de la Comunidad de Madrid Desactualizada

### ISSUE THREAD

**Issue by kioon** [LaQuay/TDTChannels#412]
Hola. Veo que faltan muchos canales de la comunidad de Madrid. Tenéis las urls o las busco. Falta Tele k. Pride no funciona, etc

**Comment by playzzz** [comment]
Puedes especificar un poco más en los canales que faltan y fallan?

**Comment by Nomenteros** [comment]
Hombre no estaría de mas una Ayuda......Pero ten en cuenta que dependemos 1º de que emitan por internet oficialmente .Pride acabo de abrir pull request para actualizarlo; Tele K Vallecas ; cuando puedas nos pasas el enlace, ya que por Internet no veo que emita en ningún sitio,o mejor ponte en contacto con ellos, por si amablemente nos quieren facilitar un enlace,para poder disfrutar de su emisión, incluidos los que no somos de Madrid. ;-)

**Comment by kioon** [comment]
Hola. Gracias por vuestra respuesta. Por ejemplo. El canal de Pride Channel desde la lista IPTV no esta accesible. Si te metes dentro de la web, emiten sin problemas. http://pridechanneltv.com/#endirecto
Sobre Telek. Les escribi por Twitter para preguntar el enlace. Os mantengo informados y busco otros canales de la comunidad que emiten por internet. Gracias por vuestro gran trabajo

**Comment by kioon** [comment]
Otro canal que se puede añadir es el canal Life tv. Emite en la TDT pirata y en esta web se puede ver su emisión online bajando un poco

http://tvespana.blogspot.com/2018/02/life-tv-en-directo.html

La web oficial es http://www.lifetelevision.es/

**Comment by kioon** [comment]
Buscando en internet he conseguido la URL m3u8 para añadirla a la C Madrid:

Life TV: http://media.profesionalhosting.com:1935/8439/8439/playlist.m3u8

Gracias.

**Comment by LaQuay** [comment]
Hola! Si no sale de la web oficial no podemos incluirlo. Gracias!
