### ISSUE TITLE
SACAR URL de los CANALES

### ISSUE THREAD

**Issue by capitanpeter** [LaQuay/TDTChannels#416]
Hola, me gustaria saber como puedo obtener los enlaces, en especial el del canal NEOX para utilizarlo como lista de canales IPTV. el canal neox creo que está caido o no funciona, se puede arreglar, 

gracias.

**Comment by playzzz** [comment]
Neox funciona perfectamente en la app. Recuerda que si eres de fuera de España solo puedes usar el enlace GEO, tienes más info en la wiki.
