### ISSUE TITLE
el enlace m3u Atresmedia ya no funciona

### ISSUE THREAD

**Issue by adamo331** [LaQuay/TDTChannels#42]
Tengo problemas con todos los enlaces m3u Atresplayer no abierto en VLC Geo y no geo ninguno de ellos abierto. Antes de que jueguen sin problema. Por favor, confirme si tiene el mismo problema y qué recomienda como consejo

Atresplayer eSports
https://esports-pull1a-a3player.secure.footprint.net/geoesports/master.m3u8
https://esports-pull1a-a3player.secure.footprint.net/esports/master.m3u8
Atreseries
https://a3series-pull1a-a3player.secure.footprint.net/geoa3series/master.m3u8
https://a3series-pull1a-a3player.secure.footprint.net/a3series/master.m3u8

**Comment by LaQuay** [comment]
Actualizo atreseries, gracias por el aviso.
Sobre eSports, es un canal que emite en ciertos momentos, quizá por eso no lo ves.
