### ISSUE TITLE
Error con la URL usando HTTPS

### ISSUE THREAD

**Issue by RicardoVelaC** [LaQuay/TDTChannels#429]
He detectado que la URL https://www.tdtchannels.com/ no funciona correctamente por HTTPS, aparece un error de seguridad por el certificado, porque redirige a la a tu foro de ruedoenelectrica, en cambio si accedes por HTTP redirige y accede bien a la web.

Me di cuenta siguiendo el enlace a la nueva app de Android en [README.md](https://github.com/LaQuay/TDTChannels/blob/master/README.md) que accede por HTTPS.

**Comment by LaQuay** [comment]
Hola! Cambiado el enlace en el README. Tengo pendiente implementar el https para la web y así no hará esos redirects.

Gracias!!

**Comment by LaQuay** [comment]
Ya le he incorporado HTTPS! 👍
