### ISSUE TITLE
Añadir Radio 7 Valencia

### ISSUE THREAD

**Issue by carlos-48** [LaQuay/TDTChannels#454]
Podrías añadir esta emisora? https://radiosiete.com/

Aprovecho para felicitarte por el gran trabajo, es una app magnífica.

Un saludo

**Comment by LaQuay** [comment]
Hola! Ya la tienes!
https://github.com/LaQuay/TDTChannels/commit/f6a230db991a81dde511c7ba8f5ad6b7e61531d9
