### ISSUE TITLE
Earth TV no funciona

### ISSUE THREAD

**Issue by chato99** [LaQuay/TDTChannels#463]
Pues eso...

#EXTINF:-1 tvg-logo="https://graph.facebook.com/earthTV/picture?width=320&height=320" group-title="Internacional" tvg-name="Earth TV",Earth TV EN
https://livecdn-de-earthtv-com.global.ssl.fastly.net/edge0/cdnedge/HicYJzEAB5E/master.m3u8

Saludos y gracias por todo el trabajo.

**Comment by arufl** [comment]
Ahora necesita un parámetro token que da la propia web.

**Comment by LaQuay** [comment]
Una lástima. En la próxima actualización cae de la lista. Gracias por el aviso!
