### ISSUE TITLE
Canales Peruanos

### ISSUE THREAD

**Issue by cprados** [LaQuay/TDTChannels#475]
Buenos días. 

¿Se podrían agregar algunos enlaces a canales peruanos? Entiendo podrían ir en el grupo de internacionales. 

Los he obtenido de las páginas web de los propios canales por lo que deberían ser 100% legales, los indico por aquí tal como los tengo configurados en mi lista por si consideráis interesante añadirlos:

#EXTINF:-1 tvg-logo="https://cdn.atv.pe/2018/v3/images/logo_atv.png" group-title="Canales Peruanos",ATV Peru
https://pe-atv-atv-live.ned.media/atv/smil:atv.smil/chunklist_b850000.m3u8?iut=eyJwYXJhbXMiOnsiZXhwIjoxNTg2NTM0OTc4LCJzZXNzaW9uIjoiNDYuMjYuNDkuMzUiLCJ3aGl0ZWxpc3QiOlsiNDYuMjYuNDkuMzUiXX0sInNpZ25hdHVyZSI6IjI1YzljZDhjZTIxMWQyOWU1N2RiMDI5OGNhMTRmYWNmYjFjMGJiNjgifQ%3D%3D

#EXTINF:-1 tvg-logo="https://cdn.atv.pe/2018/v3/images/logo.png" group-title="Canales Peruanos",ATV+ Peru
https://pe-atv-atv-mas-live.ned.media/atv/smil:atv-mas.smil/chunklist_b200000.m3u8?iut=eyJwYXJhbXMiOnsiZXhwIjoxNTg2NjIxOTQwLCJzZXNzaW9uIjoiNDYuMjYuNDkuMzUiLCJ3aGl0ZWxpc3QiOlsiNDYuMjYuNDkuMzUiXX0sInNpZ25hdHVyZSI6ImIzZjgyN2UzOGMzYjM1M2ViOTQ4ZTExOTIxMjkxOTg4NTBkNDlkNDYifQ%3D%3D

#EXTINF:-1 tvg-logo="https://www.tvperu.gob.pe/sites/all/themes/stability/images/logo_TVPE_PLAY.png" group-title="Canales Peruanos",TV Peru
http://cdnh15.iblups.com/hls/R9WtilpKKB.m3u8

#EXTINF:-1 tvg-logo="https://www.tvperu.gob.pe/sites/all/themes/stability/images/logo_TVPE_NOTICIAS_PLAY.png" group-title="Canales Peruanos",TV Peru Noticias
https://cdnh15.iblups.com/hls/RMuwrdk7M9.m3u8

#EXTINF:-1 tvg-logo="https://panamericana.pe/imagenes/logo.png" group-title="Canales Peruanos",Panamericana TV
https://stream-01.dc3.dailymotion.com/sec(mj562f6n9IrWiHyCluoeFlSDavl8mj7xHev9rflC1hM)/dm/3/x774s7s/s/live-2.m3u8

#EXTINF:-1 tvg-logo="http://bhtv.pe/wp-content/uploads/2019/04/bhtv-logo-web-300x219.png" group-title="Canales Peruanos",BHtv
https://5949aa132c8fb.streamlock.net:554/iptvbhtv/livebhtvtv/chunklist_w74548293.m3u8

En alguno he usado el enlace de mas baja calidad porque el de alta calidad tiende a estar menos disponible, supongo que por un tema de capacidad.

Un saludo,
Carlos Prados.

**Comment by LaQuay** [comment]
Hola! Gracias por los aportes. ATV Perú, ATV+ Perú, TV Perú y TV Perú Noticias los tendrás disponibles en un rato. Saludos!

**Comment by malvinas2** [comment]
(Re-open porfa si es posible)

Los links de ATV resp. ATVmás no funcionaran, porque esas cadenas usan un token (el 'iut' en tus enlaces). Necesitas usar el plugin _albavision.py_ en el proyecto Streamlink. 
Aparte de eso Streamlink tmb soporta la cadena Latina (antes: Frecuencia Latina). 
Y todos esas cadenas estan geobloqueado. 
Panamericana: Utilizando Streamlink puedes usar el enlace http://www.dailymotion.com/PanamericanaPTV. 

Ademas existe Canal IPE, television para los mas pequenios: http://cdnh15.iblups.com/hls/OVJNKV4pSr.m3u8

**Comment by LaQuay** [comment]
Hago reopen. 

Sobre los ATV y ATV+. Llevan el iut (como un token propio), pero no lo están usando.

![image](https://user-images.githubusercontent.com/6410250/79509773-76569400-803c-11ea-9c72-c465a76a69c3.png)

Puedes probarlos en nuestra web, ya están disponibles.

Sobre el Panamericana, por el momento no lo incluyo, pues no podemos incorporar Streamlink ni relacionado al proyecto.

Sobre Canal IPE, le doy un vistazo.
Gracias!

**Comment by LaQuay** [comment]
Añadido el IPe y doy por concluido. Gracias!
