### ISSUE TITLE
CNN en Español

### ISSUE THREAD

**Issue by malvinas2** [LaQuay/TDTChannels#480]
Dicen que esta solo para Venezuela, pero al menos aca en Alemania funciona sin problemas: 
https://www.youtube.com/channel/UC_lEiu6917IJz03TnntWUaQ

**Comment by LaQuay** [comment]
Hola! Es este mismo que he añadido justo antes? 😄 
https://github.com/LaQuay/TDTChannels/commit/d7f5341dc2e9c2df493420f9f970687435a0cafb#diff-69339f0bfd081f120b02d8eb91136b14R530

**Comment by LaQuay** [comment]
Cierro! 👍
