### ISSUE TITLE
Propuesta añadir varias radios

### ISSUE THREAD

**Issue by miguelangelgj** [LaQuay/TDTChannels#482]
Las pongo por aquí ya que con los Pull Requests lo he intentado de todas las formas posibles y no me acaban de salir bien

Gum FM. Cataluña
http://gum-fm01.streaming-pro.com:8018/;
https://gum.cat/

Formula Hit. Pais Vasco
http://server1.emitironline.com:9400/formulahit
https://www.formulahit.com/

Xtra FM . Comunidad Valenciana
http://streams.dynamicradiogroup.com/xtrafm
https://xtrafm.es/player/#South

**Comment by LaQuay** [comment]
Los añado, gracias Miguel
