### ISSUE TITLE
Locomotion TV EPG

### ISSUE THREAD

**Issue by samuiyo** [LaQuay/TDTChannels#485]
Por si desean agregar XMLTV de LocomotionTV:

http://epg.locomotiontv.com/guia.xml

Gracias por el trabajo realizado!

**Comment by HelmerLuzo** [comment]
El EPG es del 20 de marzo, y en su página solo encuentro una foto. Si no hay una fuente mejor y actual, no se puede hacer nada.

Gracias de todas maneras.

**Comment by LaQuay** [comment]
Cierto, gracias igualmente!

**Comment by samuiyo** [comment]
XMLTV es una fuente actualizada hasta 30/04/2020, no entiendo su comentario, solo contiene una foto?
![Screenshot_2020-04-21-20-55-43](https://user-images.githubusercontent.com/33809078/79903294-1a608680-8413-11ea-8914-87dacbd36d6d.jpg)

Es la fuente oficial de JAG que realiza el streaming.

**Comment by LaQuay** [comment]
Reabro. Yo lo ví mal, a ver que dice @HelmerLuzo.
Gracias.

**Comment by LaQuay** [comment]
Vamos a esperar hasta el 30/04 a ver si actualizan y cómo. Gracias.

**Comment by HelmerLuzo** [comment]
Vamos a ver,

yo abro el enlace que envías y lo primero que veo es 20 de marzo, voy a la página de locomotiontv y solo encuentro una foto con una programación que encima no cuadra con lo que tu mandas. 

Como comprenderás, sin ver la información del xml reflejada en ningún sitio,  no tengo mas referencia que el enlace que tu me das, y lo peor de todo, solo "se usar un script que descarga de webgrab plus y todo lo que salga de ahí me viene grande", lo descarté. 

Por cierto, me parece correcta tu reacción de tratarme de inútil por no haber atendido tu petición. 

Si el 1 de abril está actualizada, me leeré el manual de webgrab a ver como hacer un merge de tu xml. 

Ah no calla, que ya lo hago así.

**Comment by samuiyo** [comment]
Disculpa Helmer,

No pretendía ofender con mi comentario, solo causar una reacción, use un treat similar a tal efecto. Lo siento, pero ciertamente me sentó mal un cierre sin motivo aparente y sobretodo sin dar tiempo de respuesta.

Este canal LocomotionTV fue proporcionado por playz hace algún tiempo, y por el os seguí. La historia de Loco puede que no dure, ciertamente, es un stream que se realiza desde la casa de un nostálgico de este canal que cerró hace ya mas de ocho años. Tanto la programación, la parrilla/imagen que localizaste en su web y la guía EPG que os ofrecí lo va actualizando el mismo en sus ratos libres, tiene caídas de señal y perdidas de sincronización con el EPG cuando sucede esto. La programación la repite cíclicamente por semana, por ese motivo genera un xml para mucho tiempo, hasta su previsión de algún cambio importante.

De nuevo 1000 perdones y gracias por darnos la oportunidad de realizar peticiones, sé que no es fácil mantener esto que habéis creado.

Un saludo,

**Comment by HelmerLuzo** [comment]
Puedes estar tranquilo que no me has ofendido, por lo tanto no has de disculparte.

Sabiendo ahora lo que comentas, me pondré en contacto con esa persona para saber si tira la toalla o tiene ganas de seguir.

Gracias por la última explicación, ahora está todo mas claro.

**Comment by usuarionuevor** [comment]
Muchos recuerdos de la infancia… alguien conoce canales similares en Inglés o Castellano? todos los que veo son en Español Latino.

**Comment by LaQuay** [comment]
4 días que empezó el mes y sigue sin actualizarse :(

**Comment by samuiyo** [comment]
![la_cosa_no_pinta_bien--i_135623156867013562391](https://user-images.githubusercontent.com/33809078/81208890-0a7aa200-8fd0-11ea-835d-cbe074234fe0.jpeg)

**Comment by Toei79** [comment]
Tiene arreglo.

**Comment by Toei79** [comment]
yo puedo mandarlo quincenal aqui.  pero creo el canal esta down o no siempre online en este momento.
