### ISSUE TITLE
Propuesta añadir Fórmula Fun Radio & QD Radio

### ISSUE THREAD

**Issue by miguelangelgj** [LaQuay/TDTChannels#487]
Fórmula Fun Radio. Galicia
http://s30.myradiostream.com:30464/;?1587236733497
http://www.formulafungalicia.es/

QD Radio. Andalucía
http://www.hitsfm.org:8026/;
http://www.bpvmedia.com/qdradio/player/

**Comment by LaQuay** [comment]
Hola! Añado la primera. El enlace de la segunda de dónde ha salido? En la web no lo encuentro. Gracias!

**Comment by miguelangelgj** [comment]
De esta web http://www.bpvmedia.com/qdradio/
