### ISSUE TITLE
Nueva estructura del proyecto

### ISSUE THREAD

**Issue by LaQuay** [LaQuay/TDTChannels#49]
Hola a todos!

Ahora que el proyecto ha crecido, me gustaría preguntar de que forma os gustaría estructurar la página principal. A mí se me ocurren dos opciones, os parece alguna bien o se os ocurre otra?

1) Dejarlo como está, todo en una única página.

2) Separarlo en dos ficheros. El README que contenga únicamente la información del proyecto y que luego haya el fichero de TV y el fichero de RADIOS.

Gracias!

**Comment by paurg15** [comment]
Yo de momento lo dejaría y en un futuro con más contenido en el repositorio lo plantearía.

**Comment by franmartosr** [comment]
En mi opinion, seria bueno separar los ficheros de radio y TV aparte para acceder mas rapido. Hay muchas emisoras/canales y cuesta encontrarse, no me quiero imaginar cuando la lista se haga más grande.

**Comment by paurg15** [comment]
Pull enviada

**Comment by LaQuay** [comment]
Correcto, muchos opinábamos así, más gente nos lo había comunicado vía Telegram. 

Reestructuración hecha 👍
