### ISSUE TITLE
Propuesta añadir Ona de Sants-Montjuïc & Onda Loja Radio

### ISSUE THREAD

**Issue by miguelangelgj** [LaQuay/TDTChannels#494]
Ona de Sants-Montjuïc. Cataluña
http://onastream.no-ip.info:8000/live
https://onadesants.cat/wp/

Onda Loja Radio. Granada. Andalucía 
http://5.196.73.188:8008/;
http://www.ondaloja.es/

**Comment by LaQuay** [comment]
Añado Onda Loja.
La de Ona de Sants me está dando el stream. Probaré mañana, gracias!

**Comment by miguelangelgj** [comment]
Vale

**Comment by LaQuay** [comment]
Ya les va el stream, añado!
