### ISSUE TITLE
EPG Canal Extremadura

### ISSUE THREAD

**Issue by Berto9050** [LaQuay/TDTChannels#496]
Hola.

La señal por internet de Canal Extremadura es la SAT (se puede ver en el logo que usan en la transmisión que lleva la palabra "SAT"), pero la guía que usáis es la del canal normal donde se emiten películas y series.
La correcta sería esta http://www.movistarplus.es/canal/canal-extremadura-sat?id=EXTREM

Un saludo.

**Comment by samuiyo** [comment]
Hola Berto,

No te voy a dar buenas noticias, a mi me acaban de cerrar un petición de EPG del canal Locomotion, con una url de un XMLTV bien formado y actualizado hasta final de mes, diciendo que solo contenía una imagen.
Así que no tengas muchas esperanzas...
Me da que usan un script de descarga de EPGs de www.webgrabplus.com, y todo lo que se salga de ahí...

Suerte,

**Comment by LaQuay** [comment]
He borrado un comentario que, a mi parecer, no aportaba nada a esta petición. Por favor, no me hagáis bloquear a alguien por no saber comportarse.

A lo que la _issue_ se refiere. A ver si se pasa @HelmerLuzo por aquí y le da un vistazo. Gracias Berto.

**Comment by HelmerLuzo** [comment]
Desconocía esta información, y como nadie se había quejado hasta ahora, pues así seguía.

Cambiado de EXTRE a EXTREM. 

Gracias.

**Comment by LaQuay** [comment]
Los cambios serán efectivos para esta madrugada, cierro. Y gracias!
