### ISSUE TITLE
Logos y calidad de los canales

### ISSUE THREAD

**Issue by 000cuenta0001** [LaQuay/TDTChannels#5]
En la medida de lo posible, sería conveniente incluir los logos (picons) de los canales. También sería recomendable diferenciar, en el tag del canal, la calidad del mismo (Como la mayoría son HD, distinguir con SD los de menos de 720p). Paso un ejemplo:

#EXTINF:-1 tvg-logo="https://i.imgur.com/lW3uzax.png" group-title="TVfree",TRECE (SD)
http://streaming.enetres.net:1935/091DB7AFBD77442B9BA2F141DCC182F5021/live.smil/stream.m3u8

**Comment by LaQuay** [comment]
@000cuenta0001 Hola! El .m3u8 que genero se hace automáticamente a partir del contenido que hay este repositorio. Entonces como fuente de datos utiliza el README que hay aquí. 
Como propones que funcione? Serviría si añado un par de columnas más, una con la calidad y otra con las imágenes?

Veo que tienes un repositorio con algo parecido, si lo tienes por la mano y te apetece puedo hacer las columnas (Para revisar que siga funcionando con mi generador) y las rellenas con un pullrequest?

Gracias!

**Comment by 000cuenta0001** [comment]
No me manejo muy bien en Github, pero haré lo que pueda. ¿Piensas dar mantenimiento a los canales? Es decir, ir actualizando a medida que vayan cayendo.

**Comment by LaQuay** [comment]
@000cuenta0001 Perfecto! Yo en lo que pueda iré haciendo lo que has propuesto 👍 

Si, yo voy mirando los que me interesan, de momento manualmente los mantengo. Y si la gente aporta si va o no, mejor 😄

**Comment by LaQuay** [comment]
Cierro, se ha implementado ahora. 👍
