### ISSUE TITLE
Red TV, Media TV, Life TV

### ISSUE THREAD

**Issue by Fernandopsp** [LaQuay/TDTChannels#504]
Red TV
http://media.profesionalhosting.com:1935/8437/8437/playlist.m3u8
Media TV
http://media.profesionalhosting.com:1935/8441/8441/playlist.m3u8
Life TV
http://media.profesionalhosting.com:1935/8439/8439/playlist.m3u8

**Comment by alykuekano** [comment]
Genial

**Comment by Berto9050** [comment]
Hola Fernando.

Los enlaces tienen que ser extraídos de la página web del canal.
Por ejemplo, Life TV http://www.lifetelevision.es/ (suponiendo que esa es la página oficial), no emite desde su web (o yo no logro verlo). Y en caso de que transmitan de forma oficial desde una plataforma de terceros, creo que te pedirán que proporciones más información al respecto.

Un saludo.

**Comment by Fernandopsp** [comment]
Pues que mala suerte, entonces ¿estos canales no se pueden agregar a la
lista no?

Cnn en español emite en youtube, ¿sería posible agregarlo a la lista de
canales?

Euronews emite en español en su web, aqui tienes la url:

https://es.euronews.com/live

El canal 24 horas y tdp estan enganchados desde hace un par de días, ¿se
puede solucionar?

**Comment by Berto9050** [comment]
Primero que todo, te comento que yo no formo parte del team, pero vi tu issue y quise ayudar.

Con respecto a la primera pregunta, yo creo que no. Pero esperemos a ver qué dice Marc.

En relación con los canales que emiten en Youtube, no los cargan en la lista m3u. Desconozco si en las otras sí.

Sobre Euronews, es cierto que tiene un enlace .m3u8, pero lo cambian cada día y así es muy complicado mantenerlo actualizado.

Y en lo referente a 24h y Teledeporte, los siguientes enlaces funcionan pero habrá que esperar que actualicen la lista. 
24h: https://rtvelivestream.akamaized.net/hls/nxrtgolumi/24h_dvr.m3u8
Teledeporte: https://rtvelivestream.akamaized.net/hls/nxrtgolumi/tdp_dvr.m3u8

**Comment by LaQuay** [comment]
Hola! Ante todo gracias a ambos!

@Fernandopsp Tal como comenta @Berto9050 , esos canales siempre han sido un tanto raros. En el proyecto solo añadimos aquellos que de base pueden "defender" cierta autoría sobre los contenidos que emiten. De estos no hay mucho a observar. Igualmente dejo la issue abierta por que investigaré.

CNN está en el proyecto. En la lista W3U y en nuestra APP de Android. Los enlaces a youtube no pueden ponerse en las listas m3u/m3u8, pues son personalizados.

Euronews es tal y como lo comenta @Berto9050 .

Y el 24 y TDP los estoy actualizando. Saludos!

**Comment by LaQuay** [comment]
Hola. No podemos aceptarlos en el proyecto. Pues no hay información de qué/quién son, más que ese enlace. Gracias igualmente.
