### ISSUE TITLE
Propuesta de EPG

### ISSUE THREAD

**Issue by Berto9050** [LaQuay/TDTChannels#510]
Hola.

No sé si estás interesado en ir ampliando la guía a los canales que aún no la tienen. En caso de ser así, te dejo datos para DW (en español), RT (en español), CGTN (en español) y NTN24.

DW:   site="dw.com" site_id="3_6309/28"
RT:   site="movistarplus.es" site_id="RTESP"
CGTN:   site="movistarplus.es" site_id="CCTV-E"
NTN24:   site="gatotv.com" site_id="ntn24_nuestra_tele_noticias"

Un saludo.

**Comment by HelmerLuzo** [comment]
Me pongo a ello.
Gracias.

**Comment by Berto9050** [comment]
Ahora que se ha añadido TeleSUR Venezuela, estos son los datos para su guía:
TeleSUR Venezuela: site="movistarplus.es" site_id="TLESUR"

**Comment by HelmerLuzo** [comment]
Añadido.
Voy a hacer una PR para añadir los id's.

**Comment by Berto9050** [comment]
Hola.

Lo siento, pero los datos que escribí de DW ya no funcionan (o al menos a mí), sin embargo los de NTN24 sí. El site="gatotv.com" está en el pack International.
