### ISSUE TITLE
TVCS Mediterráneo

### ISSUE THREAD

**Issue by Fernandopsp** [LaQuay/TDTChannels#516]
Aqui os dejo la emisión en directo:

https://tvcs.tv/en-directe/

**Comment by Nomenteros** [comment]
Fernandopsp  todas las issue abiertas me supongo que no te paraste a pensar o preguntar, por que a no ser TeleSUR ,los demas canales, los tienes en la apk Tdtchannels o en la Lista W3U de Wiseplay....el motivo es que o son emisiones de Youtube o emiten protegidas con Token. Por lo cual la única manera de reproducirlos es como te digo(imposible en m3u8). Saludos,
PD: Abro Para la inclusión de TeleSUR

**Comment by Fernandopsp** [comment]
ok, gracias, pero deberías revisar el canal 24 horas y tdp que en la lista actual no funcionan.
Aqui están los enlaces actualizados:

24h: https://rtvelivestream.akamaized.net/hls/nxrtgolumi/24h_dvr.m3u8
Teledeporte: https://rtvelivestream.akamaized.net/hls/nxrtgolumi/tdp_dvr.m3u8

**Comment by LaQuay** [comment]
Hola! El canal se encuentra en el proyecto. Los enlaces a twitch no pueden ponerse en las listas m3u/m3u8, pues son personalizados.
