### ISSUE TITLE
Propuesta añadir Barcelona City FM & Styl FM

### ISSUE THREAD

**Issue by miguelangelgj** [LaQuay/TDTChannels#530]
Barcelona City FM
https://s2.radio.co/sd9da54aa0/listen
http://www.barcelonacityfm.com/

Styl FM. Manresa
http://s2.nexuscast.com:8024/;
http://www.stylfm.com/

**Comment by LaQuay** [comment]
Buenas, la de Barcelona City FM no emiten en ninguna frecuencia, verdad?
Sobre Styl, ya la propusiste y la tenemos, gracias!

**Comment by LaQuay** [comment]
Las añado, gracias!
