### ISSUE TITLE
varias webcams

### ISSUE THREAD

**Issue by JordiFC77** [LaQuay/TDTChannels#538]
_**DOS WEBCAMS DE LA PLAYA DE SALOU (TARRAGONA)**_
web
https://www.visitsalou.eu/es/descubre-salou/sobre-salou/salou-vivo-y-360-deg
stream de l´espigó del moll
http://195.76.183.92:8888/mjpg/video.mjpg
stream de Passeig Jaume I
http://webcam.salou.cat:8889/axis-cgi/mjpg/video.cgi?resolution=380x290&amp;dummy=1452859544402

**_WEBCAM  DE EL MIRADOR EN EL SANTUARI DE BELLMUNT (BARCELONA_**)
web
http://www.miradorbellmunt.cat/es/
stream
http://isp4.maesbyte.net:1935/live/bellmunt.stream/playlist.m3u8

**_ANFI RESORTS 3 WEBCAMS - ARGUINEGUIN - GRAN CANARIA_**
web
https://anfi.com/en/webcam/
stream anfi del mar
https://s14.ipcamlive.com/streams/0e5ea532b38c5d25a/stream.m3u8
stream anfi del mar beach
https://s9.ipcamlive.com/streams/095ea532ad24f504b/stream.m3u8
anfi tauro
https://s14.ipcamlive.com/streams/0e5e9bcbf78454a13/stream.m3u8

**Comment by LaQuay** [comment]
Hola Jordi!
Consulto con los demás miembros del equipo acerca de integrar webcams, ya que por ahora no es el objetivo del proyecto. Las que tenemos tituladas como Webcams son en realidad cámaras a estudio de TV / Radio.

**Comment by LaQuay** [comment]
Por el momento no incluimos webcams del medioambiente. Gracias!
