### ISSUE TITLE
Script automatización m3u8 y streams

### ISSUE THREAD

**Issue by playzzz** [LaQuay/TDTChannels#54]
Script para que al introducirle una página web te saque el m3u8 o Stream directamente. La página web debe ser la oficial del canal/emisora.
Marc ya me ha dicho que esto es muy complicado de hacer pero si alguien se anima estaría bien añadirlo al repositorio.

**Comment by usuarionuevor** [comment]
No sería muy complicado, buscar todos los elementos que carga la página (tanto internos como externos), con extension .m3u8

Otra cosa es que salga "rentable" ya que hacerlo manualmente no cuesta nada y es muy rápido.

Cosa diferente sería los links que llevan key y fecha de caducidad, etc ahí ya no tengo ni idea...

**Comment by LaQuay** [comment]
@usuarionuevor Correcto, al punto de "rentable" me refiero, sumándole el tema tokens, y etc. Se podría mirar, si alguien tiene tiempo para hacerlo, adelante 👍

**Comment by usuarionuevor** [comment]
Hace tiempo estuve viendo esto este script para generar links válidos, pero es para una página específica (esa que también tiene canales no legales)
https://www.forocable.com/foro/threads/92165-Redireccion-de-enlaces-M3u8-para-reproductores/page60
