### ISSUE TITLE
Propuesta canal

### ISSUE THREAD

**Issue by Berto9050** [LaQuay/TDTChannels#543]
Hola.

He visto que en el listado está CBN (en inglés). Aquí tienes los datos para CBN en Español.
web: https://www1.cbn.com/tv/cbn-espanol
m3u8: https://bcliveunivsecure-lh.akamaihd.net/i/iptv2_1@500579/master.m3u8

Un saludo.

**Comment by LaQuay** [comment]
La añado, gracias!
