### ISSUE TITLE
Añadir Betevé

### ISSUE THREAD

**Issue by Fernandopsp** [LaQuay/TDTChannels#546]
Hola buenas, os dejo por aqui la dirección url de la emisión en directo de Betevé, la televisión local de Barcelona, no se si será posible añadirla a la lista m3u8, ojala que si.

https://beteve.cat/en-directe/

**Comment by LaQuay** [comment]
Hola! El canal se encuentra en el proyecto. Los enlaces de beteve no pueden ponerse en las listas m3u/m3u8, pues son personalizados. En la APP y W3U lo encontrarás.
