### ISSUE TITLE
Propuesta mejora app

### ISSUE THREAD

**Issue by alexito1990** [LaQuay/TDTChannels#548]
Buenas tardes quería proponerte haber si es posible, que se pudiera poner un modo de solo audio como en la app de LaSexta, para escuchar solo el audio, y también que se pueda suspender el teléfono y siga continuando la reproducción. Esta genial esta app! Un saludo!

**Comment by albmarsan** [comment]
Eso estaría genial

**Comment by playzzz** [comment]
Esta propuesta está recogida en #471 desde hace tiempo.
