### ISSUE TITLE
Propuesta Listas Internacionales

### ISSUE THREAD

**Issue by Berto9050** [LaQuay/TDTChannels#552]
Hola.

Te dejo los siguientes datos por si consideras cambiarlos de listas:
- Cachipum TV emite desde Chile.
- ACS Network desde Puerto Rico.
- Garage TV desde Argentina.
- Rathergood LoL desde Reino Unido.

Un saludo.

**Comment by LaQuay** [comment]
Al ser canales de temática tan especial, los dejé así ordenados a propósito para que estuvieran juntitos. Qué opináis?

**Comment by Berto9050** [comment]
Creo que tienes razón en dejar los más temáticos aparte.

Por cierto, Zee Mundo se especializa en series y pelis de Bollywood, por lo que propongo moverlo a Asia.

Y [aquí](https://github.com/LaQuay/TDTChannels/issues/510#issuecomment-620829818) están los datos para DW.

**Comment by LaQuay** [comment]
OK!
Sobre Zee Mundo. He ordenado los canales en base de dónde emiten. Y esta emisora está localizada en América (Concretamente Miami, https://es.wikipedia.org/wiki/Zee_Mundo)

Sobre DW. Le paso la info a Helmer. Pero, por favor, no mezcles contenidos en diferentes Issues, que se nos complica el manejo.

Gracias!

**Comment by Berto9050** [comment]
De acuerdo. Tendré en cuenta lo del origen de la emisión.

Y disculpa por haber hecho mención de DW aquí, lo vi como una oportunidad para recordar aquella información y no volver a escribir allí sólo preguntando por eso, pero entiendo que esto pueda ser contraproducente para vosotros.
