### ISSUE TITLE
Duda sobre Fight Time

### ISSUE THREAD

**Issue by Berto9050** [LaQuay/TDTChannels#553]
Hola.

¿El m3u8 de Fight Time lo habéis extraído de su app? Porque desde su web no he logrado ver que emitan en directo.

Un saludo.

**Comment by HelmerLuzo** [comment]
Creo que si. Pero no me acuerdo quien lo pasó.

**Comment by LaQuay** [comment]
Si, si no recuerdo mal salió de su app o de la de fibwi por ahí inicios del 2020.
Saludos!

**Comment by Berto9050** [comment]
Vale. Lo preguntaba por si había ocurrido como con Canal Sur Cocina, que aunque su enlace m3u8 puede que siga funcionando, en realidad ya no emite desde su web y supongo que por eso ya no está en el listado.

**Comment by LaQuay** [comment]
Con Canal Sur cortaron el m3u8 :(

**Comment by Berto9050** [comment]
El m3u8 del de Cocina del [23 de Enero](https://github.com/LaQuay/TDTChannels/blob/63608225cfd3fcfde87f46d2e93944a8784f00ff/TELEVISION.md) todavía funciona. Por eso había comentado lo anterior.
