### ISSUE TITLE
Juntar los canales PTV

### ISSUE THREAD

**Issue by wuniversales** [LaQuay/TDTChannels#554]
PTV Málaga y PTV Córdoba se encuentran separados, para mejorar el orden de la lista propongo poner uno al lado del otro. :)

**Comment by LaQuay** [comment]
Hola! Los canales están ordenados en base a lo que creemos que tienen mayor audiencia. Hicimos un pequeño estudio y ese fue el orden... (Con excepción de generalistas y los populares de cada autonomia)
