### ISSUE TITLE
Propuesta de Canal

### ISSUE THREAD

**Issue by Berto9050** [LaQuay/TDTChannels#556]
Hola.

Dejo los datos de un canal musical llamado Spirit tv.
web: https://myspirit.tv/
m3u8: https://cdnlive.myspirit.tv/LS-ATL-43240-2/index.m3u8
logo: https://graph.facebook.com/MySpirittv/picture?width=320&height=320

Un saludo.

**Comment by LaQuay** [comment]
Lo añado, gracias!
