### ISSUE TITLE
Link Betevé

### ISSUE THREAD

**Issue by NicoGamer2020** [LaQuay/TDTChannels#557]
Logre obtener un link del canal de Betevé hace más de un mes, y aún sigue funcionando, pero tan solo deja un solo apartado de Betevé y quita el Betevé web
Bueno, aquí te dejo el link (esta extraído de la web): https://cdnapisec.kaltura.com/p/2346171/sp/234617100/playManifest/entryId/1_n6442jz0/format/applehttp/.m3u8?referrer=aHR0cHM6Ly9iZXRldmUuY2F0

**Comment by Fernandopsp** [comment]
Oleeee, haber si lo añaden a la lista de canales m3u8

**Comment by LaQuay** [comment]
Hola! He probado ahora mismo y sale en negro, igual que en la web de betevé.
Lo reviso en cuanto vea señal. Gracias!

**Comment by Fernandopsp** [comment]
A la 1:57 AM el link tiene señal, creo que puedes añadir el canal

**Comment by wuniversales** [comment]
Lo acabo de probar y funciona.

**Comment by Berto9050** [comment]
A veces está en negro. Quizás esto ocurre cuando emiten algún contenido para el cual no poseen los derechos de emisión por internet.

**Comment by Fernandopsp** [comment]
El link funciona perfectamente, no se porque tardan tanto en agregarlo a la lista m3u8, a este paso cuando lo vayan a añadir el link no funcionara

**Comment by LaQuay** [comment]
Venía con intención de añadirlo ahora mismo. Pero este último comentario, creo que no hacía falta.

Muchas gracias Nico por el aporte. Pronto lo agregaré.

**Comment by HelmerLuzo** [comment]
¿No será porque tenemos vida mas allá de TDTChannels.....?

**Comment by Fernandopsp** [comment]
Yo esque ahora con el confinamiento no tengo vida, llevo mas de 35 días sin salir de casa, pero eso va a cambiar a partir de mañana por la tarde, si vosotros habeis podido salir durante el confinamiento sois muy afortunados.

**Comment by Fernandopsp** [comment]
Me encantan los foros donde si no les gusta tu comentario, el admin lo borra, es que me parto de risa

**Comment by CabraMan** [comment]
Hasta luego Maricarmen.

**Comment by Fernandopsp** [comment]
Y me sigo partiendo de risa, jajajajaja

**Comment by Fernandopsp** [comment]
Seguid borrando jajajajajaja, que me sigo partiendo de risa, baneadme ya hombre que os saldra mejor, jajajaja

**Comment by LaQuay** [comment]
Que lamentable que a algunos no les de para más.

**Comment by LaQuay** [comment]
Lo añado, gracias Nico!
