### ISSUE TITLE
Señal Colombia

### ISSUE THREAD

**Issue by usuarionuevor** [LaQuay/TDTChannels#558]
web https://www.senalcolombia.tv/senal-en-vivo/

asi da error: https://play.cdn.enetres.net/85F57E947FBC4A648B8BE9DA1A772FA2024/024/playlist.m3u8
pero asi sí que funciona: https://streaming.enetres.net/85F57E947FBC4A648B8BE9DA1A772FA2024/live-300/index.m3u8
misterios de la vida

**Comment by LaQuay** [comment]
Hola! Pero, el enlace que funciona ha sido obtenido de la web? 
Quedo a la espera, gracias!

**Comment by usuarionuevor** [comment]
lo he sacado usando el codigo del canal original: https://streaming.enetres.net/85F57E947FBC4A648B8BE9DA1A772FA2024/smil:live.smil/manifest.f4m?idLive=024

"85F57E947FBC4A648B8BE9DA1A772FA2024"
"024"
y luego la terminación en hd o ld o que sea... el caso es que debería funcionar con "playlist.m3u8" que es el que se adapta automáticamente a la resolución, pero al menos a mi no me funciona…

sin embargo en baja calidad si que me funciona "live-300/index.m3u8"
https://streaming.enetres.net/85F57E947FBC4A648B8BE9DA1A772FA2024/live-300/index.m3u8
la version movil que tiene la misma calidad Tambien "mobile/playlist.m3u8"
https://streaming.enetres.net/85F57E947FBC4A648B8BE9DA1A772FA2024/mobile/playlist.m3u8

la de calidad media "live-1000/index.m3u8" no me funciona, como si lo hace en otros canales de enetres.

y la de alta calidad si que funciona  "live-1500/index.m3u8"
https://streaming.enetres.net/85F57E947FBC4A648B8BE9DA1A772FA2024/live-1500/index.m3u8

**Comment by LaQuay** [comment]
Excelente explicación. La añado! Gracias!
