### ISSUE TITLE
Emmanuel TV

### ISSUE THREAD

**Issue by usuarionuevor** [LaQuay/TDTChannels#559]
Internacional, series de animación y sermones (según el horario)

web https://emmanuel.tv/es/en-vivo/

m3u8 http://api.new.livestream.com/accounts/23202872/events/7200883/live.m3u8

**Comment by LaQuay** [comment]
Hola, no logro ver el m3u8 del stream en la web. Esa URL es de la web?
Gracias!

**Comment by wuniversales** [comment]
Si que funciona el enlace `http://api.new.livestream.com/accounts/23202872/events/7200883/live.m3u8`
Al menos a mi me funciona.

**Comment by LaQuay** [comment]
No... Me refiero a que no lo encuentro en la web, en la web veo otro contenido m3u8...

**Comment by usuarionuevor** [comment]
Si claro, pero creo que cambia si lo sacas del "elemento" o el link en "network" donde va capturando los .ts y todo eso, si el tuyo funciona, aunque sea diferente añade ese si quieres estar más Seguro pero creo que da igual? es que estoy viendo algunas páginas que generan links diferentes dependiendo por ejemplo del tamaño de la Ventana (version movil a menos resolucion) como el de esta pagina https://github.com/LaQuay/TDTChannels/issues/558

**Comment by usuarionuevor** [comment]
Creo que ya se lo que pasa, tu lo sacas del capturador no? porque asi capturas directamente el link con el bitrate y todas las opciones ya ajustadas, yo he puesto el link directo. pero cuando lo abres se ajusta y si te fijas cambia al mismo que obtienes de la otra forma.

**Comment by LaQuay** [comment]
OK! Entendido. Lo añado, gracias!
