### ISSUE TITLE
Propuesta añadir Europa Plus TV

### ISSUE THREAD

**Issue by miguelangelgj** [LaQuay/TDTChannels#561]
https://ad-hls-europaplus.cdnvideo.ru/europaplus/smil:eurptv2.smil/chunklist_b5128000.m3u8?md5=0REhzDyVkXvTQR_aLeijBg&e=1588818629&hls_proxy_host=dtmf-01&zoid=web

https://europaplustv.com/online
Europa Plus TV. Rusia. Musical

**Comment by LaQuay** [comment]
Hola. El enlace únicamente funciona en su web. Si pruebas en VLC por ejemplo, no funciona. Puedes confirmarlo?
Gracias

**Comment by miguelangelgj** [comment]
En VLC en Windows 10 a mí me funciona poniendo ese enlace y sin ningún corte. En VLC para Android no me funciona. En Wiseplay he estado viendo que funciona

**Comment by LaQuay** [comment]
![image](https://user-images.githubusercontent.com/6410250/80869541-793ebf00-8ca1-11ea-97b4-9819865cb90e.png)

VLC para Windows...

**Comment by miguelangelgj** [comment]
Voy a mirar otra vez y te digo algo

**Comment by miguelangelgj** [comment]
![europa plus](https://user-images.githubusercontent.com/62312532/80869771-a63fa180-8ca2-11ea-8d4f-8abfb37cb179.png)
Me funciona en VLC

**Comment by LaQuay** [comment]
OK! Lo pongo en el proyecto para probar con todos los medios, si vemos que no funciona de forma generalizada, lo saco. Gracias!

**Comment by LaQuay** [comment]
Vale, ya he visto que ocurre. El enlace que genera en realidad lleva un hash con datos personales. Es decir, el enlace es único. Por eso no funciona.
