### ISSUE TITLE
Cliente IPTV WIndows

### ISSUE THREAD

**Issue by zhyxor** [LaQuay/TDTChannels#562]
He probado distintos programas para visualizar los enlaces m3u. En todos los programas hay un problema con el visionado de la 1 de TVE. 

La emisión es de unas 4 horas antes, es decir, si son las 12:00h la emisión corresponde a las 8:00h.

Este problema no lo encuentro con el visionado directo de los enlaces con una extensión en mi navegador, pero ese problema tampoco se produce con ningún otro canal.

**Comment by playzzz** [comment]
Entonces es un problema de los clientes IPTV en Windows

**Comment by LaQuay** [comment]
Tu hora del reloj de Windows es correcta? No llego a ver dónde podemos actuar nosotros.

**Comment by zhyxor** [comment]
En efecto lo solucioné usando el cliente simpleTV. 

Todos los demás clientes tenían el problema pero solo con la 1, no se si por estar la primera en el listado. No lo sé. En todo caso muy buen trabajo el que realizais.
