### ISSUE TITLE
Nuevo Link TBN España

### ISSUE THREAD

**Issue by NicoGamer2020** [LaQuay/TDTChannels#569]
Aquí te dejo el link y esta extraído de su web y funciona: http://5e4e2e0bb2914.streamlock.net/live/ngrp:tbnlive_all/playlist.m3u8 (Recuerda el poner el de Betevé del comentario del otro día que puse de un link de Betevé que funciona)

**Comment by LaQuay** [comment]
Lo añado. Gracias!

Recordad que este proyecto lo llevamos entre unos cuantos en lo que nuestra vida personal nos permite. Es por ello que a veces las respuestas tardan unos días en llegar. Gracias.
