### ISSUE TITLE
Añadir canal: IMPACT Wrestling TV

### ISSUE THREAD

**Issue by NicoGamer2020** [LaQuay/TDTChannels#581]
Link: https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/59b722526996084038c01e1b/master.m3u8?deviceType=0&deviceMake=0&deviceModel=0&sid=0&deviceId=0&deviceVersion=0&appVersion=0&deviceDNT=0
Web: https://www.eu-landing.corp.pluto.tv

**Comment by LaQuay** [comment]
Hola, si los canales sólo se pueden reproducir directamente en el navegador con necesidad de previo registro / pago, no son compatibles con la filosofía del proyecto.
Gracias igualmente!
