### ISSUE TITLE
Propuesta de Canal

### ISSUE THREAD

**Issue by Berto9050** [LaQuay/TDTChannels#585]
Hola.

Dejo los datos de un canal musical.
RadioU:  [web](https://radiou.com/tv/) , [m3u8](https://cdnlive.radiou.com/LS-ATL-43240-1/index.m3u8) , [logo](https://graph.facebook.com/RadioU/picture?width=320&height=320)

Un saludo.

**Comment by LaQuay** [comment]
La añado, gracias!
