### ISSUE TITLE
Propuesta de EPG

### ISSUE THREAD

**Issue by Berto9050** [LaQuay/TDTChannels#586]
Hola.

Dejo los datos de EPG de algunos canales.

TVG América: site="movistarplus.es" site_id="TVG"
ETB SAT: site="movistarplus.es" site_id="ETB"
Al Jazeera Qatar EN: site="movistarplus.es" site_id="ALJAZE"
Bloomberg Europe: site="movistarplus.es" site_id="BL"
France 24 Francia EN:  site="movistarplus.es" site_id="FRA+EN"

DW Alemania EN: site="filmweb.pl" site_id="181" 
RT News EN: site="filmweb.pl" site_id="313" 
Sky News UK EN: site="filmweb.pl" site_id="326"
CGTN News EN: site="filmweb.pl" site_id="159"
Arirang TV Korea EN: site="filmweb.pl" site_id="138"
NHK World Japan EN: site="filmweb.pl" site_id="262"
RT Documentary EN: site="filmweb.pl" site_id="306"

ZEE Mundo USA: site="gatotv.com" site_id="zee_mundo"

CGTN Documentary EN:  site="yourtv.com.au" site_id="431122#168##Melbourne"

RTP 1 Portugal: site="nos.pt" site_id="5"
RTP 2 Portugal: site="nos.pt" site_id="3"
RTP 3 Portugal: site="nos.pt" site_id="64"
Rai News 24 Italia IT: site="nos.pt" site_id="55"
France 24 Francia FR:  site="nos.pt" site_id="132"

Un saludo.

**Comment by HelmerLuzo** [comment]
Lo primero de todo darte las GRACIAS por echarnos una mano, y sobretodo a mi, en el tema EPG.

He añadido todos salvo los que son 2 m3u de diferente idioma bajo un mismo tag porque habría que desdoblarlo. 

Yo entiendo que podamos "obviar" los GEO y no GEO, pero en el tema de diferentes idiomas igual es ver si es la misma información.

Repito. GRACIAS por tu ayuda.

**Comment by Berto9050** [comment]
Qué bien que he leído tu comentario, porque pensaba hacer una PR proponiendo ese desdoblamiento para algunos canales, ya que en lo que se refiere a información EPG:
 - DW Alemania ≠ DW Alemania EN
 - France 24 Francia ≠ France 24 Francia EN ≠ France 24 Francia FR (de hecho aún no he encontrado datos para cargar la de español)

Pero mejor espero a ver qué decidís al respecto.

Por cierto, he visto que aunque al principio del .xml de la programación EPG están los datos identificativos de los canales que usan las webs "filmweb.pl" y "yourtv.com.au"; luego no existen datos de programación para ellos. Y es para que sepas que antes los he probado y a mí sí me funcionan.

**Comment by HelmerLuzo** [comment]
Si, tienes razón pero tiene un porqué. Hasta ayer usaba la 2.1.11, que para el grabber de plus.es es suficiente.

Pero al pasarme tu los grabbers nuevos, me saltó el mensaje de que igual era hora de cambiar a v3.

Me he registrado, bajado la nueva y lo curioso es que si pruebo solo un canal funciona, si lo meto con el resto se queda en un bucle justo en ese canal. 

Ya me iba a currar y lo he dejado. Supongo que es algo de licencias.

**Comment by HelmerLuzo** [comment]
Por cierto ahora que releo tu mensaje, creo recordar que France24 en español no era muy complicado sacarla de la web.

**Comment by Berto9050** [comment]
Yo estoy con la 2.1.5.

Hace unos días buscando y probando datos nuevos para los canales me vi "obligado" a actualizar, y al ejecutar me decía que movistar estaba encriptado. Así que he vuelto a la 2.1.5.
Con esta versión me funcionan los datos de "movistarplus.es", "gatotv.com", "filmweb.pl", "nos.pt" y "yourtv.com.au". Aunque es cierto que con este último me advierte que: _SiteIni yourtv.com.au.ini contains debugs arguments. Expect slower processing_. Y es verdad que tarda más que el resto, así que se podría dejar fuera por ahora.

**Comment by HelmerLuzo** [comment]
El debug se lo puedes quitar. Edita el ini y busca esta línea:
index_showsplit.scrub {multi(debug includeblock........

Déjala así:
index_showsplit.scrub {multi(includeblock.

**Comment by Berto9050** [comment]
> El debug se lo puedes quitar. Edita el ini y busca esta línea:
> index_showsplit.scrub {multi(debug includeblock........
> 
> Déjala así:
> index_showsplit.scrub {multi(includeblock.

Muchas gracias. Ya no me da el mensaje, aunque no sabría decirte si es mucho más rápido ahora. El resto de sites es que los carga bastante rápido y supongo que lo sigo viendo algo lento por eso.

**Comment by HelmerLuzo** [comment]
Igual es cosa de la página. Yo he metido los que faltaban ya desencriptados y funcionan.

Hoy he estado mirando los channels de la carpeta Spain y aun puedo rascar mas canales. 

Gracias de nuevo por estar atento al EPG.
