### ISSUE TITLE
Añadir canal: Ibiza BPM Radio

### ISSUE THREAD

**Issue by miguelangelgj** [LaQuay/TDTChannels#590]
https://streams.radio.co/s3ed04b8f7/listen

https://www.ibizabpmradio.es/

Chillout, Techno, House, Jazz
Frecuencias. Ibiza: Online

**Comment by LaQuay** [comment]
Hola, vamos a ser más restrictivos ahora con las peticiones de añadir canales de TV o Radio. Este canal tiene poca información en internet, pocos seguidores y no veo frecuencia en FM, la hay?

**Comment by miguelangelgj** [comment]
Por lo que he visto solo emite por Internet

**Comment by miguelangelgj** [comment]
![Screenshot_20200505-203809_Chrome](https://user-images.githubusercontent.com/62312532/81102915-96c59000-8f10-11ea-940f-1ce008db1c38.jpg)

**Comment by miguelangelgj** [comment]
La información es muy confusa. Pone que se puede escuchar en diales de Ibiza, Madrid y Cataluña pero no he logrado encontrar en que frecuencias emite

**Comment by miguelangelgj** [comment]
Cierro el tema
