### ISSUE TITLE
Añadir canal: Barca TV HD

### ISSUE THREAD

**Issue by NicoGamer2020** [LaQuay/TDTChannels#593]
Web: http://photocall.tv/ (esta es la web donde se puede ver la emisión pero el link original es este: https://www.fcbarcelona.es/es/barca-tv
pero ese link no tienen emisión
Link: http://stream.pcriot.com/Zl8H/ftv.php/BARCAHD/S9014/2.m3u8

**Comment by LaQuay** [comment]
Hola, como no emiten desde la web, no podemos incluirlo. No sirve que esté en photocall. Esa web emite contenido no legal y por tanto no podemos confiar.
Gracias
