### ISSUE TITLE
Cambiar URL canal Sur eventos

### ISSUE THREAD

**Issue by albmarsan** [LaQuay/TDTChannels#598]
Hola. Han cambiado las urls. Aquí están sacadas de la web oficial de canal Sur
Canal Sur eventos 1: https://cdnlive.shooowit.net/rtvalive/smil:channel2.smil/playlist.m3u8
Canal Sur Eventos 2: https://cdnlive.shooowit.net/rtvalive/smil:channel3.smil/playlist.m3u8

**Comment by NicoGamer2020** [comment]
Hola puedo saber el link de donde los sacaste yo no pertenezco a este proyecto pero es que en la web oficial no me aparece

**Comment by albmarsan** [comment]
Los saqué de la web de canal Sur media que es la web de eventos de canal
Sur y es la siguiente
https://www.canalsur.es/portada-alternativdirecto-1272.html

**Comment by LaQuay** [comment]
Lo incluyo, gracias!
