### ISSUE TITLE
Problema en EPGs

### ISSUE THREAD

**Issue by teretn** [LaQuay/TDTChannels#600]
hola pueden arreglar los EGP de tv melilla, navarra tv, popular tv cantabria?muchas gracias

**Comment by teretn** [comment]
hola de nuevo an cambiado la escritura del EPG nose si lo an cambiado para que funcionaran los canales que no iban pues sigen sin ir o .hay que poner un nombre en concreto? muchas gsacias

**Comment by HelmerLuzo** [comment]
No tienes que tocar nada. Los reviso a ver que han cambiado.

**Comment by teretn** [comment]
vale gracias. Cuando este me puede avisar? muchas gracias

**Comment by HelmerLuzo** [comment]
Melilla ya lo tienes. Navarra y Popular tengo que rehacer el script o buscar alternativas.

**Comment by teretn** [comment]
buenos dias. Muchas gracias.  Ya me vas comentando x eras dos

**Comment by teretn** [comment]
hola. An consegido sacar el epg de navarra tv y popular cantabria?

**Comment by HelmerLuzo** [comment]
NavarraTV ya está funcionando, Popular Cantabria de momento no se puede hacer nada porque deben estar cambiando cosas y no es estable.
