### ISSUE TITLE
A3Series no funciona sin Token

### ISSUE THREAD

**Issue by arufl** [LaQuay/TDTChannels#601]
Buenas, parece que están empezando a tokenizar los streams de A3Media y han empezado por este.

Saludos

**Comment by LaQuay** [comment]
Si... Una lástima. Borramos canales m3u8. Gracias!

**Comment by malvinas2** [comment]
Peor: Ahora hay que contratar una cuenta premium: Si vives dentro de Espania pagaras 2,99 €/mes, afuera de Espania son 4,99 €/mes. Las unicas ventajas son que te ofrecen descarga offline, calidad 4K y ninguna publicidad.

**Comment by usuarionuevor** [comment]
Impresentables, y regados con dinero público.

**Comment by LaQuay** [comment]
Voy a cerrar... Saludos.
