### ISSUE TITLE
Canal no funciona: El Toro TV

### ISSUE THREAD

**Issue by usuarionuevor** [LaQuay/TDTChannels#608]
Me pasa lo mismo que con este https://github.com/LaQuay/TDTChannels/issues/558 no se si soy el único...

con "playlist.m3u8" no funciona, pero poniendo el bitrate directamente sí: "live-300/index.m3u8" y HD "live-1000/index.m3u8"
https://streaming.enetres.net/16011939C62D44ED91350508FB25828B021/live-300/index.m3u8
https://streaming.enetres.net/16011939C62D44ED91350508FB25828B021/live-1000/index.m3u8

Otra cosa, seguro que es un canal autonómico? porque lo veo en casi todas las comunidades, en Andalucía que no sale en la lista también emite. Yo lo pondría como nacional en vez de repetir el mismo canal en todas las comunidades, salvo el de Valencia que parece que tiene su propio canal (no se si otras comunidades también)

**Comment by LaQuay** [comment]
Voy a subirlo temporalmente a Generalistas. Y actualizo. Gracias!
