### ISSUE TITLE
Cope

### ISSUE THREAD

**Issue by albmarsan** [LaQuay/TDTChannels#610]
Hola. Las señales locales de COPE que utilizan el Stream oficial de la COPE como este https://wecast-b01-03.flumotion.com/copesedes/motril.mp3
Se agota el tiempo de espera y solo me pasa con estas señales en concreto pero si cambia la b  junto a 01 y se pone una m me carga perfectamente como esto https://wecast-m01-03.flumotion.com/copesedes/motril.mp3
A alguien más le pasa?

**Comment by Berto9050** [comment]
Gracias por la info. Los nuevos enlaces de streams desde sus respectivas webs llevan la m.
He realizado un [PR](https://github.com/LaQuay/TDTChannels/pull/611#issue-415611750) con los enlaces corregidos, sólo queda esperar la aprobación de alguien del equipo.

**Comment by albmarsan** [comment]
Ok. Muchas gracias

**Comment by LaQuay** [comment]
Gracias a ambos, acepto la PR. Cierro!
