### ISSUE TITLE
Emisoras locales

### ISSUE THREAD

**Issue by albmarsan** [LaQuay/TDTChannels#617]
Los40 Valencia: http://80.28.153.57:8000/40pvalencia
Los40 Ontinyent: http://185.59.49.139:8000/40p
Los40 Elda: http://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_ASO_ELDA.mp3
Los40 Benidorm: 
http://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_ASO_BENIDORM.mp3
Los40 Dance Castellón: http://stream.radiocastellon.com/40dc
Los40 Gandía: http://stream.radiogandia.net:8661/stream
Los40 Antequera: http://5.83.75.146:8000/cuarentaantequera
Los40 Estepa: http://5.83.75.146:8000/cuarentaestepa
Los40 Almería: http://212.83.164.82:8001/40almeria.mp3
Los40 Poniente: http://212.83.164.82:8007/40poniente.mp3
Los40 Índalo: http://212.83.164.82:8011/40indalo.mp3
Los40 Jerez: http://streaming6.elitecomunicacion.es:8634/stream
Los40 Classic Almería: http://212.83.164.82:8003/m80.mp3
Los40 León: http://www.radioleon.com:8000/radio

Todos los streams los saqué de la web oficial

**Comment by LaQuay** [comment]
Hola! Todos salen de la misma web? Podrías indicarla? Gracias!

**Comment by albmarsan** [comment]
Para comunidad Valenciana: https://fans40madrid.blogspot.com/p/los40-comunidad-valenciana.html?m=1
Para Andalucía: https://fans40madrid.blogspot.com/p/los40-andalucia.html?m=1
Para Castilla y León: https://fans40madrid.blogspot.com/p/los40-castilla-y-leon.html?m=1
Los 40 Classic Almería, 40 poniente, 40 Índalo: http://www.seralmeria.com/onlineradio/

**Comment by LaQuay** [comment]
Añado el de los40 almería y Indalo, el de poniente no va.

Los demás salen de una página no oficial y no podemos añadirlos, gracias!
