### ISSUE TITLE
A3 Series

### ISSUE THREAD

**Issue by Raka74** [LaQuay/TDTChannels#619]
Hola LaQuay

Acabo de ver que a tres series no se puede ver y en la lista no está.

Sabes si la volverán a poner de nuevo?

**Comment by LaQuay** [comment]
Hola, han eliminado el acceso abierto. Ahora para acceder al stream hace falta token, y por tanto, no podemos enlazarlo en las listas. Sin embargo, en nuestra App Android tienes un enlace directo.
