### ISSUE TITLE
CNN en español y añadir nuevos canales de youtube

### ISSUE THREAD

**Issue by Fernandolavila** [LaQuay/TDTChannels#625]
El sabado CNN en español dejó de emitir temporalmente por Youtube y sobre las 8:00 PM de hoy lunes 11 de Mayo a vuelto a emitir pero el canal no funciona por wiseplay, supongo que algo ha cambiado en los parámetros de emisión, pero yo no se lo que es, a si que, lo único que puedo hacer es notificarlo para que cuando podais le echeis un vistazo. Aqui os dejo la url de CNN en español por youtube.

https://m.youtube.com/watch?v=e7al4xDmZ7Q

Por otra parte, me preguntaba si sería posible añadir el canal 24 horas de noticias de chile, aqui os dejo su url de youtube.

https://m.youtube.com/watch?v=LtTdw_bAURE

También os dejo la url del canal T13 (creo que de argentina) de su emisión por youtube:

https://m.youtube.com/watch?v=bOvhCYr1NYk

Os dejo también la url de youtube del canal América TV (creo que también es argentino)

https://m.youtube.com/watch?v=li3GN0Hm7w8

Os dejo también la url de youtube del canal Crónica HD de Latinoamérica.

https://m.youtube.com/watch?v=WjEGCwzOKHI

Y por último os dejo la url de youtube del canal de noticias A24 de latinoamérica

https://m.youtube.com/watch?v=MdJsCt1ThIQ

Si algúno de estos canales emitiera también por las listas m3u y m3u8 estaría bien añadirlo.

Gracias por vuestro trabajo que es increible.

**Comment by LaQuay** [comment]
Hola! Actualizo CNN. Lo demás lo miro en poco. Gracias!

**Comment by Fernandolavila** [comment]
Gracias a vosotros por vuestro trabajo

**Comment by Fernandolavila** [comment]
El enlace de youtube de CNN en español por wiseplay da error pero la emisión por youtube funciona. 
Este es el error:

Se produjo un error. Inténtalo de nuevo más tarde. (ID de reproducción: mJ0PrtFhRE8UGpCP).
Más información

**Comment by Fernandolavila** [comment]
Hola Marc, ¿como va lo de incorporar los canales que te dije que emiten por youtube? ¿has mirado si emiten por m3u ó m3u8?

**Comment by LaQuay** [comment]
Hola! Añado los más importantes, gracias!
