### ISSUE TITLE
Añadir 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by wuniversales** [LaQuay/TDTChannels#637]
Tengo en siguiente error en la TV.
`Your remote playlist address (URL) doesn't provide 'Access-Control-Allow-Origin' header required by some of TV Vendors.`
¿Podríais añadir la cabecera?
Gracias

Edito 

Esto sucede con los enlaces m3u de tipo "http", he cambiado a "https" y ya no aparece el error.
Saludos

**Comment by wuniversales** [comment]
Vuelvo abrir esto, también parece continuar el error en "https".

**Comment by LaQuay** [comment]
Hola, podrías indicar qué canales son?
Igualmente, ese error no es que nos hayamos dejado nada, si no que el canal tiene una protección extra y nosotros no podremos hacer más que "avisar" al usuario que el enlace no funcionará en navegadores web. Son los NONAV de la lista.

**Comment by wuniversales** [comment]
Es la lista en general, puedes ver el error en el ss-iptv.
Accede aqui:
https://ss-iptv.com/en/users/playlist
En las listas externas de TDT Channels aparece una alerta diciendo que falta la cabecera "Access-Control-Allow-Origin" .

**Comment by LaQuay** [comment]
Llevo usando SSIPTV desde el inicio del proyecto y no veo este error que comentas, y nadie más lo ha comentado.
Así que no tengo ni idea de qué ocurre.

Qué URL estás poniendo? Puedes poner una captura?

**Comment by wuniversales** [comment]
Solo sucede en algunos televisores.
Mira esto:
![imagen](https://user-images.githubusercontent.com/48658161/82050315-396fd280-96b8-11ea-8b9e-e7d9bb92509b.png)
Al pulsar en **"check"** aparece esto.
![imagen](https://user-images.githubusercontent.com/48658161/82050364-50162980-96b8-11ea-8c43-410a64c38612.png)
https://ss-iptv.com/en/operators/creating-playlist

**Comment by LaQuay** [comment]
Desde cuando te ocurre?

**Comment by wuniversales** [comment]
Ni idea, hace tiempo que no uso ss-iptv, me di cuenta ayer del error porque añadi una lista a ss-iptv, y me daba esa alerta la web.

**Comment by LaQuay** [comment]
Voy a cerrarlo, el único reporte que ha habido es en esta issue, si veo que más gente se queja, lo miraremos. Gracias!
