### ISSUE TITLE
Añadir canal: Latinos 1 - Radio Italia Tv

### ISSUE THREAD

**Issue by simandry** [LaQuay/TDTChannels#639]
<Indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
Latinos 1 https://www.latinos1.tv
Radio Italia Tv https://www.radioitalia.it/radioitaliatv
<Indica debajo de esta linea la URL de la emision><REQUERIDO>
Latinos 1 https://5b38ce71f1f00.streamlock.net/8196/8196/playlist.m3u8
Radio Italia Tv https://radioitaliatv-lh.akamaihd.net/i/radioitaliatv_1@329645/index_720x480_av-p.m3u8

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

Latinos 1 es un canal suizo que transmite música latina las 24 horas del día.
Radio Italia Tv es un canal de la tdt italiana que transmite música italiana

**Comment by LaQuay** [comment]
Las añado, gracias!
