### ISSUE TITLE
Añadir canal: RTL 102.5  - ClassCnbc - TVI 24 - Net Tv - Ecuador Tv - Rede Brasil - Canal 4 RD - ABC news Australia

### ISSUE THREAD

**Issue by simandry** [LaQuay/TDTChannels#640]
<Indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
RTL 102.5 Tv https://www.rtl.it/radiovisione
Class Cnbc https://video.milanofinanza.it/classcnbc
TVI 24 https://tviplayer.iol.pt/direto/TVI24
Net Tv https://www.canalnet.tv/page/en-vivo
Ecuador Tv https://www.ecuadortv.ec
Rede Brasil https://rbtv.com.br/
Canal 4 RD https://canal4rd.com/senal-en-vivo
ABC News Australia https://iview.abc.net.au/programs/abc-news-24/NS1413V001S00
<Indica debajo de esta linea la URL de la emision><REQUERIDO>
RTL 102.5 Tv https://rtl-video1-stream.thron.com/live-video/video1/ngrp:video1/playlist.m3u8
Class Cnbc https://player-api.new.livestream.com/accounts/25225027/events/7999644/live.m3u8
TVI 24 https://video-auth4.iol.pt/live_edge/tvi24_abr/edge_servers/tvi24-480p/chunks.m3u8
Net Tv https://unlimited6-us.dps.live/nettv/nettv.smil/nettv/livestream2/chunks.m3u8
Ecuador Tv https://player-api.new.livestream.com/accounts/27228685/events/8710465/live.m3u8
Rede Brasil https://59f2354c05961.streamlock.net:1443/rbtv/_definst_/rbtv/playlist.m3u8
Canal 4 RD https://player-api.new.livestream.com/accounts/27035275/events/8371710/live.m3u8
ABC News Asutralia https://abc-iview-mediapackagestreams-2.akamaized.net/out/v1/6e1cc6d25ec0480ea099a5399d73bc4b/index.m3u8
<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
Rtl 102.5 es una de las mas éxitosas radios de Italia
ClassCnbc es la versión italiana de Cnbc
TVI 24 Noticias desde Portugal
Net Tv canal tv de Argentina
Rede Brasil Canal tv de Brasil
Ecuador Tv canal de Ecuador
Canal 4 RD Canal de Republica Dominicana
ABC News Australia Noticias desde Australia

**Comment by LaQuay** [comment]
Hola, por ahora añado Ecuador TV, Radio Italia y RTL TV Italia. Gracias!
