### ISSUE TITLE
Añadir canal: Cope Elche (radio)

### ISSUE THREAD

**Issue by elchefm** [LaQuay/TDTChannels#642]
<Indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
copeelche.com
<Indica debajo de esta linea la URL de la emision><REQUERIDO>
https://sonic.mediatelekom.net/9314/stream

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by LaQuay** [comment]
Hola! Podemos añadirlo. Sois vosotros mismos elchefm? O eres un usuario de la plataforma común?
Gracias

**Comment by elchefm** [comment]
Yo soy parte del equipo de la emisora

**Comment by LaQuay** [comment]
Perfecto, bienvenidos y apunto para añadir!

**Comment by LaQuay** [comment]
Añadido, antes de esta noche ya apareceréis.
https://github.com/LaQuay/TDTChannels/commit/4efd4f099fb6a1c5e65d8cce2c658b51d6f36bc8

Saludos!
