### ISSUE TITLE
Añadir canal: Arte Francia

### ISSUE THREAD

**Issue by NicoGamer2020** [LaQuay/TDTChannels#644]
Aquí os dejo el link de este canal, pero el problema que tiene es que tiene GEO bloqueo en Francia pero el m3u8 funciona con una VPN no se si me podéis dar una solución para no tener que conectarse a una vpn cada vez que se quiera ver el canal pero os lo dejo igual espero que te sirva:
https://artelive-lh.akamaihd.net/i/artelive_fr@344805/index_1_av-b.m3u8?sd=10&rebase=on

Esta cogido de la web oficial

**Comment by LaQuay** [comment]
Hola! No, en nuestra lista no añadimos canales que obliguen a usar VPNs para ver contenido exterior. Gracias!
