### ISSUE TITLE
Añadir canal: Party FM Radio

### ISSUE THREAD

**Issue by miguelangelgj** [LaQuay/TDTChannels#647]
https://www.partyfmradio.es/

http://radioserver11.profesionalhosting.com:9312/live

Frecuencias: 

Culleredo: 99.6
Pontevedra: 94.3  
Santiago de Compostela: 92.9  
Vigo: 107.9 

Fuente: http://guiadelaradio.com/

**Comment by LaQuay** [comment]
Hola, es una emisora con muy pocos seguidores, de momento no lo añadimos. Gracias!
