### ISSUE TITLE
Añadir canal: Canales 24/7 y Gulli (Francia)

### ISSUE THREAD

**Issue by NicoGamer2020** [LaQuay/TDTChannels#648]
Aquí te dejo algunos canales 24/7 que emiten por YouTube espero que te sirvan para incluirlo en la sección de Infantiles:

Mr Bean (Cartoons):
https://m.youtube.com/watch?feature=youtu.be&v=c0Um4kXfs4U
Mr Bean (Best Of):
https://m.youtube.com/watch?v=Ue0xaq1Q-B4&feature=youtu.be
Mr Bean (Classic): https://m.youtube.com/watch?feature=youtu.be&v=tdjyvRfJeJM
WB Kids (Español): https://m.youtube.com/watch?feature=youtu.be&v=bvS_bMRHtks
WB Kids (Latino): https://m.youtube.com/watch?v=Ulji9eaDYcM&feature=youtu.be
WB Kids (Ingles): https://m.youtube.com/watch?v=BRkQ-ZGiNbc&feature=youtu.be
PJ Masks (Español): https://m.youtube.com/watch?v=f8SPCSmhGxs&feature=youtu.be
PJ Masks (Ingles): https://m.youtube.com/watch?v=apecnkh2f3c&feature=youtu.be
Peppa Pig (Latino): https://m.youtube.com/watch?v=iiI8PA_0J9U&feature=youtu.be
Peppa Pig (Ingles): https://m.youtube.com/watch?feature=youtu.be&v=9dqBX8rltJw
Ben y Holly (Español): https://m.youtube.com/watch?feature=youtu.be&v=0ZXq7cL4VSI
Ben y Holly (Latino): https://m.youtube.com/watch?feature=youtu.be&v=4dvlsMncJNk
Pocoyo (Ingles): https://m.youtube.com/watch?feature=youtu.be&v=Lr4Z2zcdo-Q

Gulli (Francia)
m3u8: https://n0rk.org/proxy.php/https://gulli-hls-live.akamaized.net/gulli.isml/gulli-audio102_fre=64000-video=900000.m3u8
Web: https://replay.gulli.fr/Direct (en la web la emisión tiene Geobloqueo en Francia pero el m3u8 funciona por un servidor proxy)

**Comment by LaQuay** [comment]
Hola! Añado mr bean y WB kids, gracias!
