### ISSUE TITLE
Añadir compatibilidad Chromecast

### ISSUE THREAD

**Issue by NoRWoR** [LaQuay/TDTChannels#649]
<Indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<Indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
1.Es posible poder hacer mirroring directamente con un Chromecast?

Hay canales muy buenos que podrían enviarse directamente a la TV sin necesidad de disponer de dispositivos adicionales.

2. Poder suspender el dispositivo para poder escuchar emisoras o canales de TV con la pantalla apagada.

Voy a hacer una donación por tu labor ;)

Este programa es REALMENTE BUENO y su sencillez marca las diferencias.

GRACIAS.

**Comment by LaQuay** [comment]
Hola! Gracias por la donación!
Está previsto el soporte a Chromecast, sin fecha por determinar.

Me apunto la segunda propuesta para revisar.
Saludos!

**Comment by playzzz** [comment]
Las dos propuestas están recogidas en #471 desde hace tiempo.
