### ISSUE TITLE
Añadir canal: Canales BFM TV Francia y TV5MONDE

### ISSUE THREAD

**Issue by NicoGamer2020** [LaQuay/TDTChannels#650]
Aquí te dejo los m3u8 de los otros canales de BFM TV que emiten en la web oficial:
BFM Business: https://bfmbusinesshds-lh.akamaihd.net/i/BFMBUSINESS_KB@664128/index_1000_av-p.m3u8?sd=10&rebase=on
BFM Paris: https://bfmparishdslive-lh.akamaihd.net/i/BFMPARIS_KB@429747/index_1236_av-p.m3u8?sd=10&rebase=on
BFM Lyon: https://bfmlyon-lh.akamaihd.net/i/BFMLYON_KBS@797041/index_2008_av-p.m3u8?sd=10&rebase=on
TV5MONDE Asia: https://tv5asievi-i.akamaihd.net/hls/live/631619/tv5asievi/tv5asie_vie_1200.m3u8
TV5MONDE Pacífico: https://tv5pacifiqueen-i.akamaihd.net/hls/live/630175-b/tv5pacifiqueen/tv5pacifique_eng_1200.m3u8
TV5MONDE Maghreb Orient: http://livecdnh1.tvanywhere.ae/hls/tv5/04.m3u8
TV5MONDE Style: https://tv5styleen-i.akamaihd.net/hls/live/631650/tv5styleen/tv5style_eng_1200.m3u8
(Estos links son sin geobloqueo y se puede visualizar sin VPN)

Además os dejo el link del Directo de Vaughan TV que emiten en YouTube para que los añadas a la lista:
https://m.youtube.com/watch?v=RfKTn6UGsiw&feature=youtu.be

**Comment by simandry** [comment]
Os dejo el enalce de TV5MONDE Europe:
https://tv5europe-i.akamaihd.net/hls/live/729480/tv5europehls/master.m3u8
Sitio web:
https://europe.tv5monde.com/en/live

**Comment by NicoGamer2020** [comment]
El link de TV5MONDE EUROPE No funciona, pero los que puse yo si funcionan porque las he probado hace nada

**Comment by simandry** [comment]
Hola. A mi me funciona perfectamente. Probablemente funciona sólo en Europa.

**Comment by LaQuay** [comment]
Hola a ambos! De estas peticiones, por el momento, solo puedo incluir la de Vaughan.
Las demás son emisiones que no son de interés para el proyecto, lo lamento. 

P.D: No me funciona el enlace @simandry , desde Catalunya.
