### ISSUE TITLE
Añadir canal: Al Arabiya y Al Hadath

### ISSUE THREAD

**Issue by NicoGamer2020** [LaQuay/TDTChannels#651]
Aquí os dejo los m3u8 de estos dos canales árabes y también su web de origen donde obtengo los links:
Al Arabiya: https://live.alarabiya.net/alarabiapublish/alarabiya.smil/playlist_1080p.m3u8
Al Hadath: https://av.alarabiya.net/alarabiapublish/alhadath.smil/playlist_1080p.m3u8

Web (Al Arabiya): https://www.alarabiya.net/ar/live-stream#
Web (Al Hadath): https://www.alarabiya.net/ar/live-stream-hadath

**Comment by LaQuay** [comment]
Los voy a añadir para probar. Son canales muy populares pero arabes. Si tiene visores los dejaré. Gracias!
