### ISSUE TITLE
Añadir canal: The Weather Channel

### ISSUE THREAD

**Issue by NicoGamer2020** [LaQuay/TDTChannels#652]
Aquí te dejos el m3u8 del canal Internacional de The Weather Channel y su web donde cojo el link:

The Weather Channel: https://weather-lh.akamaihd.net/i/twc_1@92006/index_2400_av-b.m3u8?sd=10&rebase=on

Web: https://weloveweather.tv/twc/ (de momento pone que esa sección de tv en directo está en construcción pero el link es oficial)

**Comment by LaQuay** [comment]
Gracias! Lo añado!
