### ISSUE TITLE
Añadir canal: Canales Deportivos

### ISSUE THREAD

**Issue by NicoGamer2020** [LaQuay/TDTChannels#655]
Aquí os dejos unos m3u8 de unos canales deportivos y su web de origen:

CDO
m3u8: http://edge1.cl.grupoz.cl/cdofree/smil:cdn.smil/chunklist_w1547394383_b1800000_slesp.m3u8
Web: http://www.canalcdo.cl/senal-en-vivo-cdo/

All Sports:
m3u8: https://5cf4a2c2512a2.streamlock.net/dgrau/dgrau/chunklist_w1531803738.m3u8
Web: https://www.allsports.tv.br

America Sports (este emite por YouTube):
https://m.youtube.com/watch?feature=youtu.be&v=1SmKEIpmcLU

**Comment by LaQuay** [comment]
Hola, se agradece, pero los 3 canales tienen muy pocos seguidores. Eso es un indicador directo de "poca calidad".
