### ISSUE TITLE
Añadir canal: Canales Internacionales

### ISSUE THREAD

**Issue by NicoGamer2020** [LaQuay/TDTChannels#657]
Aquí os dejo las m3u8 de estos canales internacionales que lo emiten por su web original y no tienen geobloqueo:
Antena 3 Internacional: https://livestartover.atresmedia.com/a3internacional/bitrate_4.m3u8
Cincomas: https://mdslivehls-i.akamaihd.net/hls/live/571673/internacional/bitrate_4.m3u8
Atreseries Internacional: https://livestartover.atresmedia.com/a3seriesinternacional/bitrate_4.m3u8

**Comment by LaQuay** [comment]
Hola, no consigo ver dónde emiten en su web. Podrías indicarmelo? Gracias!

**Comment by Fernandolavila** [comment]
Una pregunta: en las direcciones m3u8 de los canales Antena 3 internacional y Atreseries Internacional sale la dirección atresmedia.com, ¿eso significa que emiten por su web?, lo digo porque como atreseries emite con token estaría bién tener la versión internacional.

Gracias por el trabajo

**Comment by NicoGamer2020** [comment]
Si, porque en España te aparecen los canales de ATRESMEDIA normales pero si te conectas con una VPN a Estados Unidos o México en la sección de Directos te encontrarás con Antena 3 Internacional y Atreseries Internacional pero el m3u8 no tiene geobloqueo excepto AtresCine y Hola TV y en Mitele más o menos es lo mismo

**Comment by Berto9050** [comment]
> Si, porque en España te aparecen los canales de ATRESMEDIA normales pero si te conectas con una VPN a Estados Unidos o México en la sección de Directos te encontrarás con Antena 3 Internacional y Atreseries Internacional pero el m3u8 no tiene geobloqueo excepto AtresCine y Hola TV y en Mitele más o menos es lo mismo

Me interesa cómo se resolverá esto para saber la política respecto a canales cuyas webs indican que no están disponibles en x región, pero luego sus enlaces directos de emisión funcionan sin problemas en dicha región.

**Comment by Fernandolavila** [comment]
Aqui están las webs oficiales desde donde emiten, pero hay que acceder con VPN de Estados Unidos o México, la de cincomas no la he encontrado

https://www.atresplayer.com/antena3-internacional/

https://www.atresplayer.com/atreseries-internacional/

**Comment by LaQuay** [comment]
Hola, he accedido a las webs y no aparece el stream. Luego he probado a acceder desde USA, y me aparece que son de pago. Podéis enviarme capturas conforme está en abierto? A ver si hago algo mal. Gracias.

**Comment by Fernandolavila** [comment]
Ya ves NicoGamer2020, con la VPN se puede acceder a la web de los canales, pero dice que son de pago, ¿cómo has podido acceder a la emisión online?, ¿has pagado?, y si no has pagado, ¿cómo lo has echo?

Gracias por vuestro tiempo

**Comment by NicoGamer2020** [comment]
Fernandolavila en su momento cogieron la m3u8 de la web oficial y la pusieron en otras web y antes que pusieran que para ver los streams tenias que pagar hice lo mismo y eran los mismos m3u8 y eran originales pero ahora desde la web oficial no se puede porque es de pago es extraido de la web oficial en su momento antes de que lo pusieran de pago

**Comment by Fernandolavila** [comment]
A mi me parece bien, pero al que le tiene que convencer es a LaQuay, por mi que los pongan ya en la lista m3u8

**Comment by LaQuay** [comment]
Hola. Estamos hablando internamente. Gracias.

**Comment by LaQuay** [comment]
Estos canales NO son válidos para la lista. Los enlaces no están disponibles desde ninguna plataforma y además hay que pagar para acceder. Gracias igualmente.
