### ISSUE TITLE
Añadir canal: Añadir Canales Italianos Mediaset

### ISSUE THREAD

**Issue by NicoGamer2020** [LaQuay/TDTChannels#658]
Aquí te dejo los m3u8 de los canales de Mediaset Italia, por lo que yo se son canales muy populares italianos pero espero que sirvan:
Canale 5: https://live3-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(C5)/stream04/streamPlaylist.m3u8
Italia Uno: https://live3-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(I1)/stream05/streamPlaylist.m3u8
Rete 4: https://live3-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(R4)/stream04/streamPlaylist.m3u8
20: https://live3-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(LB)/stream04/streamPlaylist.m3u8
LA 5: https://live3-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(KA)/stream04/streamPlaylist.m3u8
Italia 2: https://live3-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(I2)/stream04/streamPlaylist.m3u8
Estos son unos pocos canales cogidos de su web oficial, si quieres que ponga más de los que pueda obtener de la web oficial me lo dices

**Comment by LaQuay** [comment]
Hola, recuerda indicar la web exacta de dónde sacas los enlaces, si no me haces el trabajo mucho más dificil... He probado la primera y me indica que solo funciona en Italia, por lo que no puedo comprobar la web.

**Comment by NicoGamer2020** [comment]
La web es esta: www.mediasetplay.mediaset.it/diretta/

**Comment by LaQuay** [comment]
Pero, el contenido está geolocalizado o similar? Y si pruebo otras opciones indica que me registre. Más información? Gracias

**Comment by adamo331** [comment]
links are working but only video with no audio
