### ISSUE TITLE
AÑADIR CANAL #O DE MOVISTAR PLUS

### ISSUE THREAD

**Issue by Abel-1020** [LaQuay/TDTChannels#661]
https://vercanalestv1.com/ver-canal-0-online-y-gratis-las-24h-en-directo-por-internet

Hola, me puedes poner el canal #0 de MOVISTAR xfa

**Comment by NicoGamer2020** [comment]
Hola yo no pertenezco al proyecto, pero esa web de vercanales 1 emite contenido de manera "no legal" además de contener token así que no se podrá añadir

**Comment by LaQuay** [comment]
Gracias @NicoGamer2020
