### ISSUE TITLE
IPTV LATINO

### ISSUE THREAD

**Issue by Abel-1020** [LaQuay/TDTChannels#662]
Iptv latino

ANTENA 3
http://mylatinotv.com:8080/nousiptv/nousiptv345/81792
Azteca 7
http://mylatinotv.com:8080/nousiptv/nousiptv345/81802
VH1
http://mylatinotv.com:8080/nousiptv/nousiptv345/81838
ISAT
http://mylatinotv.com:8080/nousiptv/nousiptv345/81857

**Comment by LaQuay** [comment]
Como te han comentado, estás indicando canales que son de fuentes IPTV ilegales. Aquí no hay cabida para eso.
