### ISSUE TITLE
Añadir canal CANAL SUR RADIO JEREZ

### ISSUE THREAD

**Issue by Abel-1020** [LaQuay/TDTChannels#664]
CANAL SUR RADIO JEREZ
http://cdnlive.shooowit.net/rtvalive/smil:channel18.smil/playlist.m3u8

**Comment by LaQuay** [comment]
De dónde sale la emisión? Gracias.

**Comment by albmarsan** [comment]
Esa emisión sale de la web de canal Sur. Además, emiten las de todas las provincias andaluzas. Creo que estaría bien añadirlas

**Comment by LaQuay** [comment]
Buenas, si no se facilita la información correcta cierro. Falta la web.

Gracias.
