### ISSUE TITLE
Añadir canal: BBC World Service

### ISSUE THREAD

**Issue by NicoGamer2020** [LaQuay/TDTChannels#672]
Link: http://bbcmedia.ic.llnwd.net/stream/bbcwssc_mp1_ws-eieuk
Web: https://www.bbc.co.uk/sounds/play/live:bbc_world_service

**Comment by LaQuay** [comment]
Esta URL sale de su web?

**Comment by LaQuay** [comment]
Ahora lo he visto, hay que registrarse. No entra en el proyecto, gracias.
