### ISSUE TITLE
Añadir canal: Radio Italia y Montecarlo

### ISSUE THREAD

**Issue by NicoGamer2020** [LaQuay/TDTChannels#673]
Radio Montecarlo: https://icy.unitedradio.it/RMC.mp3
Radio Italia: https://radioitaliasmi-lh.akamaihd.net/i/radioitaliasmi_1@329643/index_1_a-p.m3u8?sd=10&rebase=on
Web (Radio Montecarlo): https://www.radiomontecarlo.net/sezioni/10476/radio-monte-carlo-fm
Web (Radio Italia): https://www.radioitalia.it/player

**Comment by LaQuay** [comment]
Añadi Radio Italia. Radio Montecarlo no me funciona. Probaré más adelante

**Comment by LaQuay** [comment]
Añado Radio Montecarlo, ahora si que me va, gracias.
