### ISSUE TITLE
Añadir canal: Radio Premiére Belgica y Suiza

### ISSUE THREAD

**Issue by NicoGamer2020** [LaQuay/TDTChannels#675]
Link (Premiére Bélgica): http://radios.rtbf.be/laprem1ere-128.mp3
Link (Premiére Suiza): https://lsaplus.swisstxt.ch/audio/la-1ere_96.stream/playlist.m3u8
Web (Premiére Suiza): https://www.rts.ch/play/radio/livepopup/la-1ere
Web (Premiére Belgica): https://www.rtbf.be/radio/liveradio/lapremiere

**Comment by LaQuay** [comment]
Hola, son radios que según veo sigue poca gente, de momento no las incluimos. Gracias!
