### ISSUE TITLE
Añadir canal: Canal Sur 2

### ISSUE THREAD

**Issue by JoseOnubense** [LaQuay/TDTChannels#678]
Link: http://46.105.119.83/rtvalive/canal2/mpeg.2ts
Web: http://www.canalsur.es/tv_directo-1193.html

La emisión se hace por el botón rojo de Smart TV

**Comment by LaQuay** [comment]
Por el botón rojo? No te sigo

**Comment by JoseOnubense** [comment]
> Por el botón rojo? No te sigo

Los que vemos en canal en andalucía, nos aparece su emisión por HBBTV.
Algo parecido a lo que tiene TVE, que se puede ver a la carta las series y programas, no se si me entiendes.

**Comment by NicoGamer2020** [comment]
Una pregunta no pertenezco al proyecto, pero tengo curiosidad si tienes más de este tipo de links de HBBTV O COMO VA ESTO DEL HBB TV

**Comment by Fernandolavila** [comment]
http://46.105.119.83/rtvalive/canal2/mpeg.2ts

He probado el enlace y funciona a la perfección, es Canal Sur 2, ¿Se podría sacar el enlace de Canal Sur 1?

**Comment by LaQuay** [comment]
Gracias. Vamos a investigar la procedencia de la URL. Puesto que de primeras no da información acerca de su autenticidad.

**Comment by LaQuay** [comment]
Nuestro equipo ha conseguido verificar la versión oficial de ese enlace, y con certificado HTTPS.
Así que dejo constancia aquí que hasta este momento somos la única plataforma que ofrece este enlace: https://eg128.tmira.com/rtvalive/canal/playlist.m3u8

Gracias!

**Comment by LaQuay** [comment]
Nuestro equipo ha conseguido verificar la versión oficial de ese enlace, y con certificado HTTPS.
Así que dejo constancia aquí que hasta este momento somos la única plataforma que ofrece este enlace: https://eg128.tmira.com/rtvalive/canal2/playlist.m3u8

Gracias!
