### ISSUE TITLE
Canal no funciona: HIT TV

### ISSUE THREAD

**Issue by JoseOnubense** [LaQuay/TDTChannels#680]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
http://www.hittv.es/
<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
La web no emite el canal, solo un video corporativo de publicidad, no hay emisión.

**Comment by Fernandolavila** [comment]
Hace mucho tiempo que la web de Hit TV está así

**Comment by LaQuay** [comment]
Bien visto, si emiten la añadiré. La elimino, gracias
