### ISSUE TITLE
¿Añadir tecnología P2P a los canales en la web?

### ISSUE THREAD

**Issue by wuniversales** [LaQuay/TDTChannels#681]
Creo que esto podria mejorar bastante la velocidad de carga de los canales, además se reduciria la carga de los servidores originales.
Todos los usuarios de la web se ayudarian entre ellos utilizando p2p para mejorar la velocidad de carga de los canales.

Por otra parte, se mejoraria el tema de los canales "GEO", ya que se podrian ver esos canales desde cualquier lugar si algun usuario del pais indicado está viendo el canal "GEO".

Dejo por aquí una herramienta que me gustaria que se añadiera.
https://github.com/Novage/p2p-media-loader
Saludos

**Comment by LaQuay** [comment]
Hola!
Por ahora lo descartamos, los streams no vienen de nuestros servidores y no podemos "controlar" el flujo de datos, pero parece muy interesante. Gracias!
