### ISSUE TITLE
Añadir canal: Zico TV Albania

### ISSUE THREAD

**Issue by JoseOnubense** [LaQuay/TDTChannels#682]
Link: https://www.twitch.tv/zicotv1
Web: https://zico.tv

Canal de música.

**Comment by miguelangelgj** [comment]
Si me permites JoseOnubense pongo el stream del canal que me ha salido:

https://video-weaver.arn03.hls.ttvnw.net/v1/playlist/CrcEDC1UECU7npEXHFk3UBzGqAajy_ZixZOHumwFrNAhWmlplp-2y2rJ9gsiJViO2x2LI2YuelD64qCGVnogYTqskxnNVmAxAGZRacuJDEpPA6aDJ0mOLlcb6jxOcuSjwRM9FN3ymLtzO-4UQKL2XD-xbNHThO51eb-uYDaJ5p7l50sWx3-7br9_Sw24YBcBOJCmVwX4DazpNdA9CNSgR6tqENPnMvAE1I9I7_B-g-sD6PSe3s-JTQ8S2oSPe0VPzmMXX63RNREoDKw-bxYcHUWYzY85-Xc3hctSDF43nnYxyN0jQp8IwhwqzyvNGaX7ySWqcs6vnqShpaVSXg8v73GefhrH7PBn6l-zvrMsSc3GmCwNANVZUnH9hgRX35gCO9VBkXk14pxz0kH4iVhWXio9jkhU2F2pX0EDJJdqo8CGWZBAZjtTKwvp4UeaTdfZrk8CwE1Rht6tcVbglqp8H-VeHCxrMgBS5Oh9nqTfT2O1s-PWyFLwstu5BDDcwAip-U-OW

**Comment by LaQuay** [comment]
Esta si que no la añadiré, el enlace es twitch y la emisora es poco conocida, gracias!
