### ISSUE TITLE
Añadir canal: TOP TV Brasil

### ISSUE THREAD

**Issue by JoseOnubense** [LaQuay/TDTChannels#683]
Link: https://5d23bdca513db.streamlock.net/8006/8006/chunklist_w2086218085.m3u8
Web: https://mundialcom.com.br/toptv/

**Comment by LaQuay** [comment]
Buenas, esto es música demasiado local, brasileña, entiendo... Y con pocos seguidores, seguramente la descartaré... gracias!

**Comment by LaQuay** [comment]
La añado. gracias!
