### ISSUE TITLE
Añadir canal: QMusic Holanda (TV)

### ISSUE THREAD

**Issue by miguelangelgj** [LaQuay/TDTChannels#684]
https://dpp-qmusicnl-live.akamaized.net/streamx/QmusicNL_720p.m3u8

https://qmusic.nl/live/kijk

En la app está la radio y creo que estaría bien para complementarla el canal de TV que lleva el mismo nombre. Canal musical con mezcla de videoclips internacionales y estudio de radio en directo -Visual Radio-Holanda. Con programación independiente al QMusic de Bélgica

**Comment by LaQuay** [comment]
La añado, gracias!
