### ISSUE TITLE
Añadir canal: QMusic Bélgica (TV)

### ISSUE THREAD

**Issue by miguelangelgj** [LaQuay/TDTChannels#685]
https://dcs-live.apis.anvato.net/server/play/GBy52sn59BJUpw223/rendition.m3u8?track=video-4&anvsid=i176422951-n3b9b5b1b-120e-4362-8899-47a798f943ff&ts=1590202968&anvtrid=237408e680c7e9358477415866ba7480

https://qmusic.be/live/kijk

Canal musical con mezcla de videoclips internacionales y estudio de radio en directo -Visual Radio-Bélgica. Con programación independiente al QMusic de Holanda.

Me he fijado que al poco rato cambian el stream por uno nuevo por lo que ese que había puesto ya no funciona. De todas formas te sigo dejando el "issue" para que le eches un vistazo a ver si se puede hacer algo

**Comment by LaQuay** [comment]
Hola! Parece que esta no se puede enlazar, mañana lo miro de nuevo a ver.
Gracias!

**Comment by miguelangelgj** [comment]
De acuerdo

**Comment by LaQuay** [comment]
Nada, va con token. Gracias igual!
