### ISSUE TITLE
Canal no funciona: TVG EVENTOS

### ISSUE THREAD

**Issue by carlosmur** [LaQuay/TDTChannels#686]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://events1-crtvg.flumotion.com/crtvg/events1_high/chunks.m3u8
https://events2-crtvg.flumotion.com/crtvg/events2_high/chunks.m3u8
https://events3-crtvg.flumotion.com/crtvg/events3_high/chunks.m3u8
https://events4-crtvg.flumotion.com/crtvg/events4_high/chunks.m3u8
https://events5-crtvg.flumotion.com/crtvg/events5_high/chunks.m3u8
<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
los 4 primeros canales no funcionan, estas son las urls actualizadas en HD 720, el que teneis ahora identificado como canal 5 si que funciona y emite de manera permanente la señal del parlamento de Galicia, además considero que deberían ser añadidos a la lista de canales eventuales

**Comment by LaQuay** [comment]
Hola! He estado mirando mejor... A excepción de nuestro 5º que es diferente, esos enlaces son los mismos que tenemos... Mismo comportamiento ahora mismo. Iré mirando

**Comment by carlosmur** [comment]
Ahora mismo no están activos esos canales, el único es el de parlamento,
cuando yo he mirado que había varios activos en la web no funcionaban

**Comment by LaQuay** [comment]
Hola! Acabo de comprobarlos, son los mismos enlaces los tuyos que los que tenemos actualmente. No los pruebes por la web tdtchannels que no funcionan, prueba vía app o vlc.

Añadiré el 5, gracias!
