### ISSUE TITLE
Añadir canal: Travel TV

### ISSUE THREAD

**Issue by Fernandolavila** [LaQuay/TDTChannels#688]
<Indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
http://traveltve.com/
<Indica debajo de esta linea la URL de la emision><REQUERIDO>
http://194.179.53.124:1935/live/traveltv/.m3u8

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
Aqui os dejo Travel TV, canal de documentales de la tdt

**Comment by LaQuay** [comment]
Lo analizamos, gracias!

**Comment by Fernandolavila** [comment]
Un placer ayudar

**Comment by LaQuay** [comment]
Buenas, este canal, como p.e. Life TV y etc, parecen no tener dueño. Si buscas por internet cesó emisiones hará 3 años. Así que no se saben quién hay detras, no hay certificados, etc. No la añadimos. Gracias!
