### ISSUE TITLE
Canal no funciona: La 1, La 2, 24 horas, Teledeporte y Fibwi

### ISSUE THREAD

**Issue by Fernandolavila** [LaQuay/TDTChannels#690]
Los canales de TVE (La 1, La 2, 24 horas y Teledeporte) están en bucle y Fibwi directamente no se abre el enlace

**Comment by NicoGamer2020** [comment]
Los Canales de RTVE (La 1,La 2,24 Horas y Teledeporte) han vuelto a sus antiguos m3u8 y tambien puede que tengan las 2 emisiones por canales (Con GeoBloqueo y la No Geobloqueo) excepto 24 Horas que tendria 1 emision y lo de Fibwi Live intentaré hacer algo

**Comment by LaQuay** [comment]
Cierro issue, los tenemos en PR.

Fibwi ha implementado token. Nada que hacer por ahora.
