### ISSUE TITLE
Canal no funciona: LIBERTAD DIGITAL TV

### ISSUE THREAD

**Issue by carlosmur** [LaQuay/TDTChannels#694]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
https://tv.libertaddigital.com/directo.html
<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://stream-15.dc3.dailymotion.com/sec(99xYsjgbwcGgYHHT_FT-A-8z62JzFOK48YooLn78jHE)/dm/3/xnm032/s/live-2.m3u8

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by NicoGamer2020** [comment]
Hola yo no pertenezco a este proyecto pero el m3u8 de dailymotion que has sacado tiene token y no vale

**Comment by carlosmur** [comment]
Lo he sacado del player de la web

**Comment by LaQuay** [comment]
A lo que se refiere Nico es que esos carácteres del medio parece un token. Vamos a esperar 1 día para ver si falla. De momento me funciona.

**Comment by LaQuay** [comment]
3 días más y sigue funcionando... Lo añado y vemos que pasa, gracias!
