### ISSUE TITLE
Añadir canal: Fórmula 30

### ISSUE THREAD

**Issue by JoseOnubense** [LaQuay/TDTChannels#697]
Link: https://stm2.emiteonline.com:9001/formula30
Web: https://tunein.com/radio/Formula-30-Sevilla-923-s173614/ - https://formula30.com/ (sin mantenimiento)

**Comment by LaQuay** [comment]
Hola! Hasta que no funcione la web oficial no podré revisarla, le damos unos días más a ver si recupera.

**Comment by LaQuay** [comment]
Sigue caída. Cerrando.
