### ISSUE TITLE
Añadir canal: Bolivia TV 

### ISSUE THREAD

**Issue by JoseOnubense** [LaQuay/TDTChannels#698]
Link: https://5ca9af4645e15.streamlock.net/boliviatv/smil:boliviatv.smil/chunklist_w1004551178_b26128000_sleng.m3u8
Web: http://www.boliviatv.bo/principal/tvenvivo71.php

Primer canal de la televisión pública de Bolivia

**Comment by Fernandolavila** [comment]
No funciona el enlace

**Comment by LaQuay** [comment]
Ahora mismo no funciona, probaré de nuevo más adelante, gracias!

**Comment by LaQuay** [comment]
La añado, gracias!
