### ISSUE TITLE
Añadir canal: Bolivia TV2

### ISSUE THREAD

**Issue by JoseOnubense** [LaQuay/TDTChannels#699]
Link:  http://btvboliviatv.srfms.com:6568/live/livestream/chunklist_w1627976569.m3u8
Web: http://www.boliviatv.bo/principal/tvenvivo72.php

Segundo canal de la televisión pública de Bolivia, equivalente a "La 2" de España

**Comment by NicoGamer2020** [comment]
Este enlace si funciona ahora debemos esperar la respuesta de Marc

**Comment by LaQuay** [comment]
La añado, gracias!
