### ISSUE TITLE
Canal Castilla la Mancha

### ISSUE THREAD

**Issue by matiroda** [LaQuay/TDTChannels#7]
Hola compi, muy buen trabajo te has currado, y se agradece mucho....
Podrias hecharle un vistaso al canal Castilla la Mancha, hay un link que no funciona y el otro siempre pone la misma imagen...

**Comment by LaQuay** [comment]
Actualizado, gracias por el aviso!

**Comment by matiroda** [comment]
Hola crak, otra vez se me ha ido el canal castilla la mancha...me gustaria mucho seguir viendolo...gracias y feliz navidad...

**Comment by LaQuay** [comment]
@matiroda Se les ha caido en la web, tampoco les funciona http://www.cmmedia.es/en-directo/tv/.

Si quieres, cuando ahí vuelva a funcionar me avisas y lo revisamos. 👍

**Comment by matiroda** [comment]
Ostias..que rapido eres...yo le doy a abrir al link que me has pasado, me sale una pubicidad y despues me sale como cuando estan sin emision...porque hay algunas horas que no emite...no se si es eso o que esta fuera...igualmente muchas gracias...ire mirando y te aviso cuando se vea algo por aqui...

**Comment by LaQuay** [comment]
@matiroda Me has pillado por aquí... 👍  De acuerdo!

**Comment by matiroda** [comment]
Te cometo que el canal ya se vuelve a ver otra vez, asi que seguramente ha sido fallo en la emision, gracias por el trabajo que haces...

**Comment by LaQuay** [comment]
@matiroda Perfecto, cierro!
