### ISSUE TITLE
Añadir canal: First Music Channel (TV)

### ISSUE THREAD

**Issue by miguelangelgj** [LaQuay/TDTChannels#700]
http://hz1.teleport.cc/HLS/HD.m3u8

http://www.1muz.com/

Logo: 
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9HV-WOXYRe60Xw18-2JHEgpF81BZo7EUUCKuDM4022uCQfSadsg&s

First Music Channel. Canal de Videoclips Internacionales. Bielorrusia

**Comment by LaQuay** [comment]
Lo añado, gracias!
