### ISSUE TITLE
Añadir canal: Onda Sur Motril

### ISSUE THREAD

**Issue by Padial10** [LaQuay/TDTChannels#707]
<Indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

https://telemotril.com/

<Indica debajo de esta linea la URL de la emision><REQUERIDO>

http://radio.telemotril.com:8000/live
![B4438DD2-6C1F-4021-A610-F450997ADEE9](https://user-images.githubusercontent.com/66113578/83239740-a72bfc00-a198-11ea-8d39-85a8d523b009.png)

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by LaQuay** [comment]
Tenemos PR, cierro. Gracias!
