### ISSUE TITLE
Añadir emisora: Onda 15 Castalla

### ISSUE THREAD

**Issue by albmarsan** [LaQuay/TDTChannels#715]
Aquí te dejo sus correspondientes datos: 
M3U8: https://radioserver11.profesionalhosting.com:59166/stream
Web procedencia: www.onda15.com
Logo: https://scontent-mad1-1.xx.fbcdn.net/v/t1.0-1/c105.32.394.394a/s200x200/1936238_112009228239_4962375_n.jpg?_nc_cat=109&_nc_sid=0c64ff&_nc_oc=AQn40z_Too2NTP_AMg_R3d_UFy6hySXPICjij-gwOA0KvlwpAULRdEm9wRd5FXhWT4k&_nc_ht=scontent-mad1-1.xx&oh=6cdfa18b009ecc78b9371504f309c13c&oe=5EFB477A

**Comment by LaQuay** [comment]
Hola! Esta mañana hemos cambiado la forma de proponer canales. Las issues antiguas se aceptan de este modo pero a partir de ahora aceptaremos únicamente via www.tdtchannels/peticion y por Pull Request bien formateada.
Gracias!
