### ISSUE TITLE
Problemas 

### ISSUE THREAD

**Issue by simandry** [LaQuay/TDTChannels#723]
Hola.
Usando la app en Android Tv hay problemas con algunos de los enlaces a YouTube: no siempre se abre la app YouTube (Euronews, Todo Noticias, Tv Channel Nigeria, Sky News Uk, América tv Argentina).

**Comment by LaQuay** [comment]
Hola, hasta ahora no teníamos noticias de esto. Y si no se abre la app YouTube qué ocurre?

**Comment by simandry** [comment]
Hola! 
La app de YouTube no se abre y no es posible ver el canal.

**Comment by LaQuay** [comment]
Entiendo que los que has mencionado antes NO van. Puedes indicarme alguno youtube que si que vaya? Gracias!

**Comment by simandry** [comment]
Funcionan, por ejemplo, cnn, c5n de Argentina, 24 Noticias Chile, Tele13 Chile.

**Comment by LaQuay** [comment]
OK! Lo dejo pendiente de revisión

**Comment by LaQuay** [comment]
Hola, lo que se ha realizado en la v2.1 es el máximo que está en nuestras manos. Saludos!
