### ISSUE TITLE
Selección de tema

### ISSUE THREAD

**Issue by rulogarcillan** [LaQuay/TDTChannels#725]
Hola, los móviles con últimas versiones se puede tener seleccionado el modo oscuro por defecto. La opción de ajustes de seleccionar modo oscuro no tiene sentido puesto ya tengo el modo oscuro. Creo q sería más útil 3 opciones el SDK lo proporciona. 

Modo oscuro
Modo claro
Definido por el sistema

Basta con guardar la opción elegida en un shared preference y que cargue esa variable al iniciar la app. Heredando de un tema daynight el cambio es sencillo incluso no hace falta reiniciar la app para que cambie el tema de color
        AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM)

Sustituir la constante por la que corresponda cargada del sharedpreference, Basta con ponerlo en el create de un globalactivity.

Por otro lado deberías crear un atributo de color para tintar los iconos de redes sociales en los diferentes modos y q en el modo oscuro sean blancos y no negros

Si necesitas colaboración no dudes en escribirme

**Comment by LaQuay** [comment]
Por otro lado, en la aplicación hay un único ajuste de Dark mode o no:

Dark Mode activo -> Fuerza Dark Mode
Dark Mode inactivo -> Definido por el sistema

Cualquier otra combinación carece de sentido. Saludos y gracias por escribir!

**Comment by rulogarcillan** [comment]
Tengo la última bajada de tu web.

Igual que puedes forzar el darkmode, también se debería poder forzar el day mode

Actualmente uso darkmode en mi teléfono pero con esa configuración es evidente que no tengo manera de poner el modo día.

**Comment by LaQuay** [comment]
Ah! No lo hice por que me parece extraño que se fuerce el móvil en Dark Mode y la app en Day Mode. Puedo hacerlo, tomo nota para más adelante.
Saludos!

**Comment by LaQuay** [comment]
Hola @rulogarcillan, disculpa que no me acordé de dar el aviso por aquí. Pero ya está disponible desde la v2.0. Saludos!
