### ISSUE TITLE
Canal no funciona: Mega y Atreseries

### ISSUE THREAD

**Issue by Maria9224** [LaQuay/TDTChannels#730]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by Maria9224** [comment]
El resto de cana les van perfectos pero estos ya ni aparecen

**Comment by LaQuay** [comment]
Hola, han cambiado el enlace y ahora implementan seguridad. No están disponibles en las listas m3u/m3u8.
