### ISSUE TITLE
Canal no funciona: Atresmedia (todos)

### ISSUE THREAD

**Issue by usuarionuevor** [LaQuay/TDTChannels#731]
TODOS.
antena3, la secta, neox, nova... parece que ya han caido todos.

**Comment by corrido** [comment]
Efectivamente. Yo también lo he notado y creía que era algún tema de mi conexión o app, pero ya veo que os pasa a más personas

Todas las cadenas del grupo Atresmedia

**Comment by LaQuay** [comment]
Hola, ahora solo emiten en GEO. Si estás fuera, no emiten.
Neox y Nova, por ejemplo, funcionando ahora mismo.

En 1 hora actualizo lista.

**Comment by corrido** [comment]
Estoy en Alemania.

Significa eso, que ya no voy a poder más ninguno de esos canales? 

En la lista siempre me han aparecido estos canales duplicados, y creía que era precisamente eso, uno emitiendo contenidos para territorio nacional y el otro para internacional

**Comment by LaQuay** [comment]
Si, eso significa. Han cortado la emisión que permitía ver desde fuera de España.

Por su web puedes verlo?

**Comment by corrido** [comment]
Me matan entonces!! 

Desde su web? si no recuerdo mal había que darse de alta en Atresplayer y también tenía problemas con geolocalización.

No me creo que no vaya a poder ningún canal a partir de ahora. No hay otra manera? otro enlace m3u?

**Comment by Opardi** [comment]
Buenas noches. A los canales de mediaset les pasa lo mismo, no se ven desde esta tarde. Muchas gracias por su ayuda

**Comment by LaQuay** [comment]
Si cruzáis atresmedia con mediaset cierro hilos.

**Comment by corrido** [comment]
mea culpa, las he mezclado yo. Aunque supongo que el problema es el mismo en ambas plataformas y solucionado uno, solucionados todos

**Comment by rferreras** [comment]
Los de Mediaset desde méxico solo puedo verlos via VPN, todos estan GEO y te piden pagar 3euros para poder verlos desde fuera,

**Comment by LaQuay** [comment]
Lamentablemente, Mediaset ha añadido protección token a sus streams. Esto implica que no van a estar disponibles a partir de ahora en las listas M3U/M3U8, no es culpa nuestra, llamad a Mediaset, no a nosotros. Ambas, además, han cerrado streams a Geolocalizados, por lo que desde la web sólo se puede ver en España.
Además, Atresmedia también está realizando cambios. Ha cerrado totalmente los streams M3U8 de Mega y Atreseries. Ahora solo dísponibles mediante su web y también georeferenciados.
