### ISSUE TITLE
Corregir error: Canal Sur 1

### ISSUE THREAD

**Issue by albmarsan** [LaQuay/TDTChannels#732]
El que tenéis titulado como Canal Sur 1 Andalucía es en realidad Canal Sur Andalucía

**Comment by LaQuay** [comment]
Hola, recibimos una petición diciendo justamente lo contrario... Por eso lo cambiamos...

**Comment by albmarsan** [comment]
Pues es canal sur Andalucía. Sí se va al directo sale en el logo una A de Andalucía en vez de un 1. Es que hay diferentes versiones de canal sur

**Comment by Fernandolavila** [comment]
Tienes toda la razón del mundo, no es Canal Sur 1, es Canal Sur Andalucía, la versión internacional de la RTVA

**Comment by albmarsan** [comment]
En el canal Sur eventos 2 tienen puesto el canal sur 1 pero tarde o temprano lo quitarán

**Comment by LaQuay** [comment]
OK, revierto el cambio del nombre, gracias.

**Comment by LaQuay** [comment]
Y cambio el nombre del otro, avisadme cuando cambien. Gracias!
