### ISSUE TITLE
Grupo Mediaset no funcionan

### ISSUE THREAD

**Issue by RDMMDLC** [LaQuay/TDTChannels#733]
No funcionan Telecinco, FDF, Divinity, Cuatro, etc... 
Corregid el error

**Comment by MiguelAngel2345** [comment]
Gracias por el aporte por cierto no se te vaya a olvidar decir donde tienes el error o que dispositivo estas usando no vaya a ser que perdamos practica con la bola de cristal.
Saludos.

**Comment by RDMMDLC** [comment]
Kodi Leia

**Comment by MiguelAngel2345** [comment]
movil? pc? tostadora siemens? tablet?

**Comment by Sl64298** [comment]
A mi me pasa lo mismo. Versión de Kodi 18.6. Sistema operativo Android 5.1.1.
El aparato desde el que lo veo es Tronsmart Vega S95_Meta.
Lo intento ver desde Alemania.

**Comment by RDMMDLC** [comment]
Raspberry Pi 3 B+

**Comment by LaQuay** [comment]
"Corregid el error". Esto se trata de un proyecto abierto, y sin ánimo de lucros. Ordenes las justas. Cierro.
