### ISSUE TITLE
Canal no funciona: Mediaset (Telecinco, Cuatro,BeMad,etc)

### ISSUE THREAD

**Issue by arufl** [LaQuay/TDTChannels#734]
Los canales de Mediaset han pasado todo a token.

**Comment by corrido** [comment]
Estamos discutiendo este tema precisamente ahora por el hilo #731

Al parecer han desconectado la emisión GEO. Estás fuera de España?

**Comment by LaQuay** [comment]
Si cruzáis atresmedia con mediaset cierro hilos.

**Comment by LaQuay** [comment]
Lamentablemente, Mediaset ha añadido protección token a sus streams. Esto implica que no van a estar disponibles a partir de ahora en las listas M3U/M3U8, no es culpa nuestra, llamad a Mediaset, no a nosotros. Ambas, además, han cerrado streams a Geolocalizados, por lo que desde la web sólo se puede ver en España.
Además, Atresmedia también está realizando cambios. Ha cerrado totalmente los streams M3U8 de Mega y Atreseries. Ahora solo dísponibles mediante su web y también georeferenciados.
