### ISSUE TITLE
por que quitan canales?

### ISSUE THREAD

**Issue by supernestor** [LaQuay/TDTChannels#735]
se sabe por que han quitado estos canales? cuatro, telecinco, fdf, energy, divinity ?
¿los volveran a poner?
soy nuevo en esto...
gracias

**Comment by alcosa09** [comment]
https://github.com/LaQuay/TDTChannels/issues/734

**Comment by alcosa09** [comment]
> se sabe por que han quitado estos canales? cuatro, telecinco, fdf, energía, divinidad?
> ¿Los volveran a poner?
> soy nuevo en esto ...
> gracias

https://github.com/LaQuay/TDTChannels/issues/734
