### ISSUE TITLE
AÑADIR: A3Series Internacional (Atresmierda)

### ISSUE THREAD

**Issue by usuarionuevor** [LaQuay/TDTChannels#736]
pues eso, el internacional si se ve, aunque desconozco si la programación es la misma que en el canal normal

.

PD: bitrate_3 para 720p si lo queries 1080p usad bitrate_4, para moviles bitrate_1, etc

EDIT: **SI QUE FUNCIONA,** no se porque he puesto la etiqueta "canal-no-funciona" perdón si genera confusión

**Comment by LaQuay** [comment]
Hola, edito tu mensaje. Ese canal no cumple, por ahora, las condiciones en las que nos movemos en el proyecto. Ya que si te pregunto por la url exacta donde retransmite, no sabrás darmela.

Igualmente recuerdo que las peticiones se deben hacer vía www.tdtchannels.com/peticion, gracias.

**Comment by usuarionuevor** [comment]
Es exactamente la misma url que tienes puesta en Antena3, Lasecta, Neox y Nova... añadiendo "internacional", igual que las que son "geo"

**Comment by arufl** [comment]
Esas URLs salen al conectarse desde fuera de España a A3player y con una cuenta pagada

**Comment by LaQuay** [comment]
Todo el mundo sabe de donde salen, pero también se sabe que para acceder a esa emisión, además de estar en américa has de haber pagado la subscripción, por eso no se pueden añadir. Por lo menos por ahora. Gracias.
