### ISSUE TITLE
Canal no funciona: Mediaset canales m3u8

### ISSUE THREAD

**Issue by Adveo2020** [LaQuay/TDTChannels#738]
Telecinco: 
https://linear01-i.akamaihd.net/hls/live/837810/telecinco/master.m3u8

Cuatro: 
https://linear02-i.akamaihd.net/hls/live/837811/cuatro/master.m3u8

FDF:
https://linear02-i.akamaihd.net/hls/live/837813/fdf/master.m3u8

Energy:
https://linear02-i.akamaihd.net/hls/live/837816/energy/master.m3u8

Divinity:
https://linear01-i.akamaihd.net/hls/live/837812/divinity/master.m3u8

Bemad:
https://linear02-i.akamaihd.net/hls/live/837815/bemad/master.m3u8

Boing: 
https://linear01-i.akamaihd.net/hls/live/837814/boing/master.m3u8
<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by Adveo2020** [comment]
Espero que les sirva. 😉

**Comment by albmarsan** [comment]
De donde sacaste los links?

**Comment by Fernandolavila** [comment]
Si son enlaces legales sería manjar 😀

**Comment by byJS93** [comment]
Tenéis los canales de mega y de atreseries ?

**Comment by LaQuay** [comment]
Hola, estamos analizando los enlaces. Necesitamos saber el origen de ellos. En qué web están? O plataforma?
Gracias.

Borro comentario que no era del tema.

**Comment by juanef** [comment]
Buenas sabéis link canal mega no funciona 
Gracias 
Un saludo

**Comment by LaQuay** [comment]
Hemos podido comprobar la validez de los canales, gracias por dar el primer paso! Ya los tenéis disponibles

**Comment by arufl** [comment]
> Hemos podido comprobar la validez de los canales, gracias por dar el primer paso! Ya los tenéis disponibles

¿Se sabe de qué web proceden?

**Comment by arufl** [comment]
Han dejado de funcionar

**Comment by albmarsan** [comment]
Sí, por desgracia. Esos enlaces eran geniales
