### ISSUE TITLE
Canal no funciona: TV Rioja

### ISSUE THREAD

**Issue by miguelangelgj** [LaQuay/TDTChannels#739]
En "Emisión Web" la web correcta de TV Rioja es: http://www.tvr.es/directo/
La web está mal puesta. Sale esto:
![Screenshot_20200606-142614_TDTChannels](https://user-images.githubusercontent.com/62312532/83944213-fd84e480-a801-11ea-858b-fe7bbe4beb54.jpg)

Y "Emisión 1" no funciona

**Comment by LaQuay** [comment]
Hola, fijate en el botón WEB de aquí https://github.com/LaQuay/TDTChannels/blob/master/TELEVISION.md y verás que es la misma web. Deben tener algún problema, pero la web que tenemos indicada es la que tu mismo has indicado arriba.

Saludos!
