### ISSUE TITLE
Canal no funciona: Mega

### ISSUE THREAD

**Issue by juanef** [LaQuay/TDTChannels#741]
SERVICE 4097:0:1:31:0:0:0:0:0:0:https%3a//livestartover-i.akamaized.net/geomega/master.m3u8:Mega
#DESCRIPTION Mega GEO
#SERVICE 4097:0:1:33:0:0:0:0:0:0:https%3a//livestartover-i.akamaized.net/mega/master.m3u8:Mega
#DESCRIPTION Mega

**Comment by LaQuay** [comment]
Si no está en la lista ya, es normal que no funcione. Saludos.
