### ISSUE TITLE
Canal no funciona: Antena 3

### ISSUE THREAD

**Issue by albmarsan** [LaQuay/TDTChannels#748]
Parece que continúan poniendo token y ahora le toca a antena 3

**Comment by edurubio** [comment]
Mal asunto, ahora te crea archivos temporales, ya se ve en el propio enlace esos números tan largos, espero que logremos dar con la clave yo seguiré intentando, por si a alguno os urge tenerlos os paso enlaces privados pero durarán un par de días, saludos:

#EXTINF:-1,ES | ANTENA 3
http://plus-tv.us:8080/live/1899/1899/16352.m3u8

#EXTINF:-1,ES | La Sexta
http://plus-tv.us:8080/live/1899/1899/16355.m3u8

**Comment by Adveo2020** [comment]
Hola, ya que me han etiquetado algunos. Yo de momento tampoco tengo solución alguna. 😣

Lo único que puedo aportar son los dash/mpd. 
Usándolo con el VLC y en la misma Red.
(He de comentar que estos links no son míos, me los paso un compañero)

Antena 3:
http://a3m-a3-vod-dash.secure.footprint.net/live/nas_live/a3/dash/a3.mpd?begin=&end=&nvb=1527155886&nva=1958691886&hash=07aec97e3ce1401d19d4b80f7e5be5e7e948fa60a

La Sexta:
http://a3m-la6-vod-dash.secure.footprint.net/live/nas_live/la6/dash/la6.mpd?begin=&end=&nvb=1527155886&nva=1958691886&hash=0310763bce5c7f5644d60221f2621cd810db2ad29

**Comment by corrido** [comment]
@edurubio muchas gracias por los enlaces. Los he probado y, lamentablemente, sólo funcionan unos segundos y se paralizan después

**Comment by Rafaesp** [comment]
La gente de telegorda .com aún son capaces de servir a3 y la6. No sé cómo habrán conseguido esos links 🤔

**Comment by edurubio** [comment]
no hay de qué @corrido para eso estamos pero es raro que dé saltos, en VLC debe ir perfecto

**Comment by edurubio** [comment]
@Rafaesp los de telegorda.com transmiten enlaces privados como los que yo he puesto y lo actualizarán cada 2 por 3.....

**Comment by LaQuay** [comment]
@edurubio La próxima vez que subas enlaces ilegales serás baneado del proyecto. Gracias.

Estamos mirando la situación.

**Comment by edurubio** [comment]
no fue mi intención, @LaQuay  lo siento mucho pido disculpas

**Comment by albmarsan** [comment]
Bueno... Cierro porque ya está cambiado
