### ISSUE TITLE
Canal no funciona: La Sexta

### ISSUE THREAD

**Issue by neinh** [LaQuay/TDTChannels#750]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
Lasexta.com

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

https://livestartover.atresmedia.com/geolasexta/master.m3u8
https://livestartover.atresmedia.com/lasexta/master.m3u8

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by raulprietofdez** [comment]
El nuevo link de a Sexta es: https://directo.atresmedia.com/1592085509_a8f1a54ebf6e719df333427beebf99386154cb73/lasexta/master.m3u8

**Comment by neinh** [comment]
No, ese no funciona:

Error 492 Unknown Error
Unknown Error

Guru Mediation:

Details: cache-dub4344-DUB 1592057924 2103610010

Varnish cache server

**Comment by raulprietofdez** [comment]
Acabo de probarlo, estoy viendo la pelicula de la Sexta... llevo todo el día con ese Link

Ver captura: https://ibb.co/nRQN1m4

**Comment by LaQuay** [comment]
Estás poniendo un enlace con token. En él va tu IP. Por eso solo te va a ti. Cierro.
