### ISSUE TITLE
Canal no funciona: antena 3 la sexta

### ISSUE THREAD

**Issue by Carlosotos1** [LaQuay/TDTChannels#751]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by LaQuay** [comment]
https://github.com/LaQuay/TDTChannels/issues/750
