### ISSUE TITLE
Añadir Urban Revolution TV

### ISSUE THREAD

**Issue by ea5iva** [LaQuay/TDTChannels#757]
El canal también aparece en algunas otras listas de España como uRV TV, su página web es www.urbanrevolution.es y la URL de la emisión en directo es https://www.urbanrevolution.es:444/live/5e6d8470a3832/index.m3u8

![logourbanrevolution](https://user-images.githubusercontent.com/66835149/84511909-864ec500-acc7-11ea-9121-22b9f6f74121.png)

**Comment by albmarsan** [comment]
No funciona el enlace

**Comment by ea5iva** [comment]
Ya funciona, gracias!!-- Enviado desde mi teléfono Android con GMX Mail. Por favor, disculpe mi brevedad.El 9/7/20, 15:32 albmarsan <notifications@github.com> escribió:

   
  No funciona el enlace

**Comment by ea5iva** [comment]
Hola, podriais incluirlo?? gracias

**Comment by albmarsan** [comment]
No pertenezco al proyecto pero las peticiones de canales se tienen que hacer a través de tdtchannels.com/peticion se cambió la forma de presentar canales. Saludos

**Comment by ea5iva** [comment]
Ah vale gracias!-- Enviado desde mi teléfono Android con GMX Mail. Por favor, disculpe mi brevedad.El 18/7/20, 23:42 albmarsan <notifications@github.com> escribió:

   
  No pertenezco al proyecto pero las peticiones de canales se tienen que hacer a través de tdtchannels.com/peticion se cambió la forma de presentar canales. Saludos

**Comment by LaQuay** [comment]
Hablé con Enrique, el presidente. Añadido!
