### ISSUE TITLE
Canal no funciona: La Sexta

### ISSUE THREAD

**Issue by Gonchitaro** [LaQuay/TDTChannels#758]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
Creo que es: https://directo.atresmedia.com/1592106374_459bc6daff790c6010556aff7fbdaf6d99f29b10/lasexta/bitrate_3.m3u8

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
Ha desaparecido de la lista en los últimos días. Hace una semana estaba y funcionaba correctamente.

**Comment by albmarsan** [comment]
Hola yo no pertenezco al proyecto pero ese link ya no vale porque tiene token

**Comment by LaQuay** [comment]
Si revisas las últimas 3 issues del proyecto verás que tu enlace tiene token y solo te funciona a tí.
