### ISSUE TITLE
Canal no funciona: Antena 3 media

### ISSUE THREAD

**Issue by tcorral** [LaQuay/TDTChannels#759]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
Algunos de los cananles Antena 3 media han dejado de funcionar:
- Antena 3 - Antena 3 HD
- La Sexta - La Sexta HD
- Mega - Mega HD
- Antena 3 series

**Comment by LaQuay** [comment]
Hola Tomás, Atresmedia ha decidido cortar emisiones a través de m3u8 simples. Ahora sus emisiones llevan token con la IP personal y poco se puede hacer, por ahora.

https://github.com/LaQuay/TDTChannels/issues/748
https://github.com/LaQuay/TDTChannels/issues/750
https://github.com/LaQuay/TDTChannels/issues/758
