### ISSUE TITLE
Canal no funciona: NOMBRE

### ISSUE THREAD

**Issue by stani2103** [LaQuay/TDTChannels#760]
Hola
Es que no aparece ningún canal de TV o radio
Solo veo radios favoritos.....

**Comment by LaQuay** [comment]
Si no das más información, dificil. 
Si supongo que estás hablando de la de Android, bájate la última, tienes una versión desactualizada.
Si estás en la de iPhone, has de seguir unos pasos.
Toda la info la tienes en www.tdtchannels.com

**Comment by stani2103** [comment]
> Si no das más información, dificil.
> Si supongo que estás hablando de la de Android, bájate la última, tienes una versión desactualizada.
> Si estás en la de iPhone, has de seguir unos pasos.
> Toda la info la tienes en [www.tdtchannels.com](http://www.tdtchannels.com)

Hola
Estoy en Android 10 con la versión 1.3.0
Hasta ahora funcionaba muy bien
Simplemente no aparecen ni canales de TV ni de radio,solo veo los favoritos que tenía(radio) y funcionan
