### ISSUE TITLE
Canal no funciona: Mediaset canales m3u8

### ISSUE THREAD

**Issue by miami24** [LaQuay/TDTChannels#763]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
https://linear02-i.akamaihd.net/hls/live/837811/cuatro/master.m3u8

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
El caso continúa de https://github.com/LaQuay/TDTChannels/issues/738, reabro (si se puede) puesto que el 738 ya está cerrado.

**Comment by edurubio** [comment]
no se ve ninguno ni de mediaset ni de atresmedia

**Comment by albmarsan** [comment]
Yo encontré estos dos pero no sé si serán oficiales
Telecinco: https://live.mitele.es/hls/live/2004101/telecinco/master.m3u8
Cuatro: https://live.mitele.es/hls/live/2004102/cuatro/master.m3u8

**Comment by albmarsan** [comment]
Yo encontré estos dos pero no sé si serán oficiales
Telecinco: https://live.mitele.es/hls/live/2004101/telecinco/master.m3u8
Cuatro: https://live.mitele.es/hls/live/2004102/cuatro/master.m3u8

**Comment by malvinas2** [comment]
Pues, seamos honestos: Puede ser que de vez en cuando haga unos links que funcionan por unos dias, pero en general todos los enlaces de atresmedia y mediaset son muertos.

**Comment by jesusrb89** [comment]
Yo también tengo el mismo problema, no se ve apenas canales. Alguna solución rápida ? :(

**Comment by albmarsan** [comment]
Los enlaces de Telecinco y Cuatro que he puesto siguen funcionando. Aunque arrancan cuando quieren

**Comment by jesusrb89** [comment]
> Los enlaces de Telecinco y Cuatro que he puesto siguen funcionando. Aunque arrancan cuando quieren

Access Denied
You don't have permission to access "http://live.mitele.es/hls/live/2004101/telecinco/master.m3u8" on this server.
Reference #18.9d2991d4.1592319611.573a6257

**Comment by miami24** [comment]
> 
> 
> > Los enlaces de Telecinco y Cuatro que he puesto siguen funcionando. Aunque arrancan cuando quieren

Pues a mí no me iban... y encontré otro que me iba solo a trompicones y de repente, durante la emisión cambiaba de ser Cuatro pasaba a ser Telecinco, luego una vez pasó a ser La Sexta... pero casi todo el rato el cambio era de Cuatro a Telecinco. Eso los pocos ratos que funcionó...

**Comment by albmarsan** [comment]
A mi ya no me funcionan tampoco

**Comment by fmelet** [comment]
No hay solución?

**Comment by edurubio** [comment]
no la hay, usan códigos temporales, funcionan como privados

**Comment by corrido** [comment]
Nos han jodido pero bien. Yo era la unica manera que tenía de ver la TV española desde Alemania

**Comment by edurubio** [comment]
Una pena sí, yo tenía terminado de programar una APP impresionante y compatible con todo y ya ves......

**Comment by miami24** [comment]
> 
> 
> Nos han jodido pero bien. Yo era la unica manera que tenía de ver la TV española desde Alemania

Yo igual, también estoy fuera de España... :-(

**Comment by malvinas2** [comment]
> Nos han jodido pero bien. Yo era la unica manera que tenía de ver la TV española desde Alemania
Atresmedia y Mediaset ofrecen una subscripcion internacional para acceder al contenido fuera de España. 
Me imagino que debe ser posible programar un plugin para [streamlink](https://github.com/streamlink/streamlink), ese plugin debe llevar a cabo el proceso de login y averiguar los links. Aparentemente tendrias que pagar el servicio y necesitaríamos alguien quien sabe programar dicho plugin....

**Comment by salva84** [comment]
> Nos han jodido pero bien. Yo era la unica manera que tenía de ver la TV española desde Alemania

Si accedeis a atresplayer.com con cualquier vpn apuntando a españa lo veis sin problema...

> > Nos han jodido pero bien. Yo era la unica manera que tenía de ver la TV española desde Alemania
> 
> Yo igual, también estoy fuera de España... :-(

**Comment by corrido** [comment]
> > Nos han jodido pero bien. Yo era la unica manera que tenía de ver la TV española desde Alemania
> 
> Si accedeis a atresplayer.com con cualquier vpn apuntando a españa lo veis sin problema...
> 
> > > Nos han jodido pero bien. Yo era la unica manera que tenía de ver la TV española desde Alemania
> > 
> > 
> > Yo igual, también estoy fuera de España... :-(

Lo de la VPN no funciona, ya ha probado y detecta que estás accediendo con VPN

![image](https://user-images.githubusercontent.com/66443140/85899109-e2543600-b7fd-11ea-876c-cd33fcf8bad2.png)

**Comment by corrido** [comment]
Detectan que accedes a través de VPN, no funciona

[image: image.png]

**Comment by miami24** [comment]
> 
> 
> > Nos han jodido pero bien. Yo era la unica manera que tenía de ver la TV española desde Alemania
> 
> Atresmedia y Mediaset ofrecen una subscripcion internacional para acceder al contenido fuera de España.
> Me imagino que debe ser posible programar un plugin para [streamlink](https://github.com/streamlink/streamlink), ese plugin debe llevar a cabo el proceso de login y averiguar los links. Aparentemente tendrias que pagar el servicio y necesitaríamos alguien quien sabe programar dicho plugin....

Mediaset no ofrece ninguna opción si se está fuera de España. Atresmedia puede ser, yo no lo uso...

**Comment by miami24** [comment]
> 
> 
> > > Nos han jodido pero bien. Yo era la unica manera que tenía de ver la TV española desde Alemania
> > 
> > 
> > Si accedeis a atresplayer.com con cualquier vpn apuntando a españa lo veis sin problema...
> > > > Nos han jodido pero bien. Yo era la unica manera que tenía de ver la TV española desde Alemania
> > > 
> > > 
> > > Yo igual, también estoy fuera de España... :-(
> 
> Lo de la VPN no funciona, ya ha probado y detecta que estás accediendo con VPN
> 
> ![image](https://user-images.githubusercontent.com/66443140/85899109-e2543600-b7fd-11ea-876c-cd33fcf8bad2.png)

Mediaset (con la app mitele) sí que te deja.

**Comment by miami24** [comment]
> 
> 
> > Nos han jodido pero bien. Yo era la unica manera que tenía de ver la TV española desde Alemania
> 
> Si accedeis a atresplayer.com con cualquier vpn apuntando a españa lo veis sin problema...
> 


El problema es que los VPNs gratuitos no te dejan escoger país. Algunos te ofrecen 3 puntos de acceso gratis, pero ninguno en España. Yo al final estoy pagando VPNExpress, pero es carísimo, teniendo en cuenta que yo ya pago por la tele por cable una barbaridad cada mes...

**Comment by miami24** [comment]
> 
> 
> > Nos han jodido pero bien. Yo era la unica manera que tenía de ver la TV española desde Alemania
> 
> Atresmedia y Mediaset ofrecen una subscripcion internacional para acceder al contenido fuera de España.
> Me imagino que debe ser posible programar un plugin para [streamlink](https://github.com/streamlink/streamlink), ese plugin debe llevar a cabo el proceso de login y averiguar los links. Aparentemente tendrias que pagar el servicio y necesitaríamos alguien quien sabe programar dicho plugin....

No tengo ni idea de lo que es streamlink, ni de programar plugins. Yo me bajaba las listas m3u8 y lo veía en VLC...
