### ISSUE TITLE
Canal no funciona:Atresplayer 1,2,3

### ISSUE THREAD

**Issue by Gabriel44200** [LaQuay/TDTChannels#769]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>
La url va cambiando dependiendo del evento,pero el m3u8 no.
https://www.atresplayer.com/directos/evento-veneno-capitulo-2/
<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>
Atresplayer 1:https://livestartover.atresmedia.com/eventos15/bitrate_4.m3u8
Atresplayer 2:https://livestartover.atresmedia.com/eventos26/bitrate_4.m3u8
Atresplayer 3:https://livestartover.atresmedia.com/eventos37/bitrate_4.m3u8
<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by LaQuay** [comment]
Gracias por el dato. Lo actualizo!
