### ISSUE TITLE
Propuesta:Añadir EPG a TV Ferrol

### ISSUE THREAD

**Issue by Gabriel44200** [LaQuay/TDTChannels#795]
En el twitter del canal ponen una tabla con lo que van a emitir y propongo añadirlo al EPG del proyecto.
URL twitter: https://twitter.com/Tvferrol/status/1234537117923119107

![TV Ferol](https://user-images.githubusercontent.com/64473570/86051786-42451980-ba56-11ea-8b85-d0815e9dff88.jpg)

**Comment by LaQuay** [comment]
Hola, la forma de trabajar propuesta es muy rudimentaria y carece de sentido. Si lo indican de forma programática podremos darle un vistazo.
