### ISSUE TITLE
Canales

### ISSUE THREAD

**Issue by paurg15** [LaQuay/TDTChannels#8]
Falta À Punt (la nueva RTV valenciana) y 'laSexta' no se escribe 'La Sexta' sino 'laSexta'

**Comment by LaQuay** [comment]
Hecho, gracias!

**Comment by paurg15** [comment]
Gracias a ti! Una ultima pregunta, están todos los canales en el archivo .m3u8?

**Comment by LaQuay** [comment]
@paurg15 Actualizado, ahora, que de momento no lo tengo automatizado. 😄

**Comment by paurg15** [comment]
¡Muchas gracias por este trabajo que estás haciendo! Y para acabar solo decirte que estaría muy bien que pudieses contactar con desarrollador de esta app: https://play.google.com/store/apps/details?id=es.garisoft.tdtspain&hl=es o que creases una para ver toda la TV con el móvil.

També li vaig deixar una nova imatge corporativa que no sé si la va rebre, https://drive.google.com/drive/folders/1lgIkaHkqwjKMonxmzmPPy51IfOkdinjm?usp=sharing , espero la teva opinió!

**Comment by LaQuay** [comment]
@paurg15 Gracias a vosotros por colaborar! 
Tengo en mente realizar una aplicación de TV gratuita con esta misma información que publico aquí. Lo único, tengo poco tiempo... Pero en mente la tengo!

Sobre la imagen corporativa... Bastante bien! En el momento dado de realizar la aplicación, si necesito ayuda te contactaré 💻 😄

**Comment by paurg15** [comment]
¡Muchas gracias por la opinión! Seguiré practicando para mejorar y no dudes en contactarme para tu futura app.

¡Encantadísim d'ajudar-te!
