### ISSUE TITLE
Propuesta de canal: añadir fox sports

### ISSUE THREAD

**Issue by moldahutal** [LaQuay/TDTChannels#803]
Añadir el canal fox sports

**Comment by NicoGamer2020** [comment]
Hola, yo no pertenezco a este proyecto, pero tu eres que el que tiene que ponernos el enlace "m3u8" de los Canales FOX Sports, pero debes darte cuenta que la emisión "m3u8" provenga de la web oficial de FOX Sports, en caso de que no sea de la web oficial, no se podrá añadir en el Proyecto

**Comment by LaQuay** [comment]
Lo dicho por @NicoGamer2020 es lo correcto. No ha habido otra respuesta así que cierro. Gracias!
