### ISSUE TITLE
Problemas con los streams de YouTube en Android Tv

### ISSUE THREAD

**Issue by simandry** [LaQuay/TDTChannels#805]
Hola. He descargado la versión 2.0 de la app para Android Tv. Me he dado cuenta que hay problemas con unos canales que transmiten por YouTube. En cambio de abrirse la app de YouTube se abre el sitio de YouTube y no se puede seguir la transmisión (aparece el botón stream 1 y no stream YouTube). Por ejemplo no funcionan correctamente: CNN en español, NBC News USA, Milenio México, C5N Argentina, La Nación Argentina, Globovisión  Venezuela, 24 Chile, AfricaNews. En cambio France Info, Euronews, Channels Tv Nigeria, Todo Noticias Argentina, Ámerica Tv Argentina, Tv Publica Argentina funcionan en la app de YouTube sin problemas. Podéis solucionarlo? Felicitaciones por el proyecto.

**Comment by LaQuay** [comment]
Hola! En la v2.1 debería estar corregido, hay ajustes para "configurar" esto.
Saludos!
