### ISSUE TITLE
[MEJORA]: Crear las listas en formato XSPF

### ISSUE THREAD

**Issue by RafaelLinux** [LaQuay/TDTChannels#818]
Me ha parecido muy buena la idea de agrupar las listas de canales de TV y emisoras disponbiles por flujo de datos. Sin embargo, dado que el formato M3U(8) no tiene una estructura clara y es más que mejorable ¿por qué no publicas la lista en XSPF? Muchos reproductores leen el formato, que es más rico  en metadatos y [bien documentado](https://www.xspf.org/xspf-v1.html). 

Se agradecería.

**Comment by LaQuay** [comment]
Hola! No tengo experiencias con las listas XSPF y hasta el momento, en todos los reproductores se han podido añadir las M3U8.

Qué ganaríamos si se pusiera la XSPF?

**Comment by wuniversales** [comment]
Supongo que mas variedad en las listas...
Igualmente ¿No se generan las listas "al vuelo" con php?
¿Porque no se sube el código de fuente de la web a github?
Alomejor podriamos aportar algo de código...
Tampoco molestaria añadirlo, ya que se generan todos los tipos de lista automáticamente desde php.

**Comment by LaQuay** [comment]
Gracias @wuniversales 
Hacer por hacer no lo hago. El código generador está cerrado por que no tiene mucho misterio, se recorre la tabla que véis aquí y se crean las listas correspondientes. 
Y no, el proyecto internamente no funciona con php, ni se generan al vuelo. Las listas se generan automáticamnete, si, pero con Python.

Voy a cerrar la Issue. En los 2 años que llevamos sólo ha salido una vez el tema XSPF y el autor de la Issue no responde. Gracias!

**Comment by RafaelLinux** [comment]
Aunque hace ya cuatro años que se cerró este hilo, puesto que no se consideró relevante implementarlo y yo por circunstancias personales no pude contestar en su momento y el tiempo pasó, sí quería dejar al menos mi opinión (como programador, no como usuario) al respecto de implementar XSPF.
Quiero dejar claro que yo, personalmente, en los proyectos privados que me encargan, sí uso XSPF y como he tenido que retomarlos por actualizaciones, he vuelto a darme cuenta de lo que me facilitó la vida y he recordado este hilo que no contesté en su momento.

- XSPF es un ESTÁNDAR LIBRE (https://es.wikipedia.org/wiki/XML_Shareable_Playlist_Format) y yo en cualquier proyecto priorizo los estańdares libres sobre los privados (M3U ni tan siquiera es un estándar normalizado)
- Es XML con TODO lo que ello implica, como es estar normalizado y ser extensible
- Es parseable de una manera muy sencilla, porque todos los lenguajes tienen alguna librería de parseo de XML.
- Es legible por cualquiera, sin necesidad de recurrir a especificaciones del autor

Con todo ello, una vez tengo creado mi fichero XSPF puedo generar todos y cada uno de los otros tipo de formatos no estándares con facilidad, desde PLS hasta M3U8 (e incluso a JSON), a sabiendas de que complicaré su parseo a aquellos que en lugar de usar el estándar XSPF sólo permiten importar de ficheros M3Ux o similares.

Pero en fin, cada cual tiene sus prioridades, y la mía es promover y usar estándares abiertos, como lo hago también con los canales Atom en lugar de usar RSS.

Un saludo
