### ISSUE TITLE
Fight Time

### ISSUE THREAD

**Issue by albmarsan** [LaQuay/TDTChannels#821]
¡Hola! El M3U8 de Fight Time que teníais antes en el proyecto https://directo.fibwi.com/stream/stream_Fight_Time/fighttime.m3u8 vuelve a funcionar para que lo añadáis de nuevo. 
Saludos Cordiales.

**Comment by albmarsan** [comment]
Cierro, lo que se reproduce es un bucle continuo

**Comment by LaQuay** [comment]
Gracias por el dato y por el intento!
