### ISSUE TITLE
Canal no funciona: varios

### ISSUE THREAD

**Issue by JavierFelip** [LaQuay/TDTChannels#833]
Hola!

Tengo varios canales como Telemadrid que dicen que la fuente no está disponible o bien, no comienzan a reproducir y unos segundos después se para y dice lo mismo, que la fuente no está disponible. 

Veo los canales con el navegador web integrado con Android 10.

Muchas gracias y un saludo.

**Comment by LaQuay** [comment]
Hola, 
Sobre Telemadrid, dejan de emitir a veces, puedes comprobar que cuando no funciona es por que en su web no funciona.
Sobre los otros, no tengo información sobre cuales te refieres pero supongo que te refieres a esto: 
https://t.me/tdtchannels_avisos/415
https://t.me/tdtchannels_avisos/416
