### ISSUE TITLE
Canales Mediaset m3u8 funcionan

### ISSUE THREAD

**Issue by Adveo2020** [LaQuay/TDTChannels#841]
Cogiendo los links m3u8 de Mediaset que ya estaban coraborados que eran legales aquí ahora la actualización de estos. 
Hay que borrar el /master.m3u8 y sustituirlo por /01.m3u8 también puede ser /02.m3u8 o /03.m3u8 la diferencia es la resolución.

Telecinco: (Antiguo)
https://linear01-i.akamaihd.net/hls/live/837810/telecinco/master.m3u8

Nuevo: 
https://linear01-i.akamaihd.net/hls/live/837810/telecinco/01.m3u8

Cuatro: (Antiguo)
https://linear02-i.akamaihd.net/hls/live/837811/cuatro/master.m3u8

Nuevo: https://linear02-i.akamaihd.net/hls/live/837811/cuatro/01.m3u8

FDF: (Antiguo)
https://linear02-i.akamaihd.net/hls/live/837813/fdf/master.m3u8

Nuevo:
https://linear02-i.akamaihd.net/hls/live/837813/fdf/01.m3u8

Energy: (Antiguo)
https://linear02-i.akamaihd.net/hls/live/837816/energy/master.m3u8

Nuevo:
https://linear02-i.akamaihd.net/hls/live/837816/energy/01.m3u8

Divinity: (Antiguo)
https://linear01-i.akamaihd.net/hls/live/837812/divinity/master.m3u8

Nuevo:
https://linear01-i.akamaihd.net/hls/live/837812/divinity/01.m3u8

Bemad: (Antiguo)
https://linear02-i.akamaihd.net/hls/live/837815/bemad/master.m3u8

Nuevo:
https://linear02-i.akamaihd.net/hls/live/837815/bemad/01.m3u8

Boing: (Antiguo)
https://linear01-i.akamaihd.net/hls/live/837814/boing/master.m3u8

Nuevo:
https://linear01-i.akamaihd.net/hls/live/837814/boing/01.m3u8

**Comment by LaQuay** [comment]
Los acabo de añadir, gracias por la información!!!
