### ISSUE TITLE
Euronews SPAIN

### ISSUE THREAD

**Issue by Abel-1020** [LaQuay/TDTChannels#846]
https://euronews-es-p12-cdn.hexaglobe.net/5781a2e0e2bd82260c280c09af08c4c8/5f210665/euronews/euronews-euronews-website-web-responsive-2/ewnsabres_spa.smil/ewnsabres_spa_720p33.m3u8

**Comment by NicoGamer2020** [comment]
Hola, yo no pertenezco al proyecto, pero por lo que yo se esos links m3u8 de Euronews tienen token y normalmente dirán entre 12 y 24 horas y por eso no se van a añadir en el proyecto
