### ISSUE TITLE
Univision Deportes

### ISSUE THREAD

**Issue by Abel-1020** [LaQuay/TDTChannels#848]
https://unidfpclnlds121.akamaized.net/linear/hls/pa/event/3WfvFwf9RWKeJ4pRTQa5Vw/stream/e116f2e3-ecd8-4dd2-a37c-ebd7be822470:BRU/variant/7fe26e25b8308dccb4fc5652a673e1d0/bandwidth/800000.m3u8

**Comment by NicoGamer2020** [comment]
Hola, yo no pertenezco a este proyecto, pero los m3u8 tienen que salir de la web oficial, y por lo que yo se este canal es de pago y por lo tanto es ilegal y en la actualidad el m3u8 no funciona pero por lo tanto no puede entrar en el proyecto

**Comment by LaQuay** [comment]
Hola, esa URL lleva token. No es compatible, gracias.
