### ISSUE TITLE
Canales presentes en los archivos md pero no presentes en las listas

### ISSUE THREAD

**Issue by malomehi** [LaQuay/TDTChannels#850]
Hola,

Desde hace algun tiempo hay varios canales que funcionan y estan publicados en los archivos md pero que han desaparecido de las listas.
Algunos ejemplos son canales nacionales como Cuatro, La Sexta, Telecinco, etc.

Por ejemplo, estan presentes en https://github.com/LaQuay/TDTChannels/blob/master/TELEVISION.md pero no en https://www.tdtchannels.com/lists/combo_channels.m3u8

He comprobado algunos de ellos y funcionan perfectamente, pero por alguna razon han desaparecido de las listas.

Gracias.

**Comment by malomehi** [comment]
Parece que Cuatro y Telecinco han vuelto, aun asi faltan muchos como La Sexta, Mega, Neox, etc.

**Comment by LaQuay** [comment]
Hola,
Los canales MPDs incluidos en el proyecto son especialitos, y el correcto funcionamiento depende mucho de las conexiones y de la aplicación que los utilice.

Además, fuera de un ecosistema muy trabajado como TDTCHANNELS para Android o Wiseplay, son una fuente de errores normalmente.

Sin ir más lejos, aquí ya están reportando que en VLC no funcionan correctamente. Y es a lo que me refiero, dependen de muchos factores. https://github.com/LaQuay/TDTChannels/issues/851

Dichos canales, mpd, jamás han estado en las listas m3u/m3u8. Pues son un formato diferente al estándar que utilizan los contenedores m3u/m3u8.

Igualmente lo tenemos en mente. Pero esto no es una issue ni un canal que no funciona. Es una implementación diferente en MPD que hasta ahora no estaba en la plataforma.
