### ISSUE TITLE
Issues with MPD streams

### ISSUE THREAD

**Issue by pelowj** [LaQuay/TDTChannels#851]
Does anyone else have issues with the A3M mpd streams? They start ok, but the audio drops out or stream freezes for me after a while. The same issue seems also to present itself on https://www.tdtchannels.com/television/Antena3

VLC shows the following error when the audio drops:
_main debug: no demux modules matched
adaptive error: Failed to create demuxer 0x0 MP4_

Cheers,
jp

**Comment by LaQuay** [comment]
Hi! These channels are wrong formated in origin. And the correct work of them depends in a lot of variables.

Let's check this. Turn your system clock back one minute. The issue is still there?

**Comment by pelowj** [comment]
Ahora es perfecto. Muy interesante. A3M lo hace a drede? Lamentablemente no se puede establecer la hora manualmente en el Apple TV.

**Comment by LaQuay** [comment]
La plataforma que utilizan para emitir es la culpable... Pero más no sé. Saludos!
