### ISSUE TITLE
Milenio Televisión

### ISSUE THREAD

**Issue by GerardoHD** [LaQuay/TDTChannels#876]
El canal Milenio TV de mexico, es de noticias y lo he visto aparecer en otras listas, creo que sería una buena adición.
#EXTINF:-1 group-title="MEXICO",Milenio TV
http://bcoveliveios-i.akamaihd.net/hls/live/201661/57828478001/milenio_center_512k@51752.m3u8

Logo:
https://vignette.wikia.nocookie.net/logopedia/images/8/8a/MilenioTelevisi%C3%B3n2020.svg

**Comment by LaQuay** [comment]
Hola Gerardo, ese m3u8 procede de la web oficial?

**Comment by GerardoHD** [comment]
No, es de una lista, en la pagina oficial pone el Stream de Youtube, pero como lo he visto aparecer en varias listas con la misma URL pensé que se podía agregar sin problema.

**Comment by LaQuay** [comment]
Sin fuente oficial no se puede añadir, gracias!
