### ISSUE TITLE
La TDT por internet es de pago

### ISSUE THREAD

**Issue by Albert456** [LaQuay/TDTChannels#891]
Lo encuentro muy injusto que la televisión por internet, se vea desde casa sólo por antena y que por internet sea de pago. ¿Qué no represtena cuota de pantalla igualmente?

Una respuesta por favor y ¿por qué no se ve, Antena 3, la Sexta, etc...?

**Comment by MarcoBravoG** [comment]
si no se vé xq el enlace se cayó y hay que probar otro link

**Comment by LaQuay** [comment]
Hola, nosotros no somos ningún ente oficial que realice emisiones. Como se observa en este repositorio y en la web, somos una fuente de enlaces oficiales. Así que no entiendo que ocurre con la primera frase, pero nos desmarcamos.

Sobre la duda segunda:
https://github.com/LaQuay/TDTChannels/issues/850
https://github.com/LaQuay/TDTChannels/blob/master/info_television.md
