### ISSUE TITLE
Los canales de Atresmedia no aparecen

### ISSUE THREAD

**Issue by rodrigoescunha** [LaQuay/TDTChannels#893]
Estoy usando la aplicación SS IPTV en mi televisor LG. Sin embargo, los canales de Atresmedia (Antena 3, Neox, Nova) no aparecen en la lista. ¿Necesita alguna configuración?

![15983673806538048673749730450906](https://user-images.githubusercontent.com/44747941/91190536-0e8b1680-e6ca-11ea-9a87-55549aa14ac2.jpg)

**Comment by GerardoHD** [comment]
Por lo que he visto en otros issues de este repo; ( https://github.com/LaQuay/TDTChannels/issues/850 )
esos canales están codificados en .mpd, una implementación incompatible y diferente del estándar .m3u, por lo tanto solo están disponibles en la aplicación oficial. Saludos!

**Comment by LaQuay** [comment]
https://github.com/LaQuay/TDTChannels/issues/850

https://github.com/LaQuay/TDTChannels/blob/master/info_television.md
