### ISSUE TITLE
Canal no funciona: antena 3 en formato m3u8

### ISSUE THREAD

**Issue by drytroll5** [LaQuay/TDTChannels#894]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>

**Comment by LaQuay** [comment]
https://github.com/LaQuay/TDTChannels/issues/850

https://github.com/LaQuay/TDTChannels/blob/master/info_television.md
