### ISSUE TITLE
Antena 3 Eventos

### ISSUE THREAD

**Issue by paurg15** [LaQuay/TDTChannels#9]
Hoy con la renovación de Atresplayer, el canal 'Antena 3 Eventos' a pasado a llamarse 'Atresplayer Exclusivo'. ¡Este es su logo por si alguien lo quiere!
![atresplayer exclusivo](https://user-images.githubusercontent.com/38435718/39375425-94fb33d2-4a4e-11e8-805d-75b6d5a9877e.png)

**Comment by LaQuay** [comment]
Hola Pau!
Sabes donde está la información sobre el cambio de nombre? Que quiero aprovechar y "recoger" algo más el apartado de Antena 3.
Gracias!

**Comment by LaQuay** [comment]
@paurg15 OK! Hago el cambio 👍 
Sabes cuantos canales hay entonces?
Antena 3 + Atresplayer Exclusivo + Antena 3 Champions?
Gracias!

**Comment by paurg15** [comment]
Entonces de Atresmedia hay: Antena 3, laSexta, Neox, Nova, Mega, Atreseries y después está Atresplayer Exclusivo, Antena 3 Internacional, Atreseries Internacional, Atrescine Intercional, Hola TV (éste no hace mucho falta 😂) y normalmente para la final de Champions suelen abrir otro directo más para retransmitirla en 4K

**Comment by LaQuay** [comment]
Ay ay ay... jaja. 😨 
De los que has nombrado, solo estos emiten por internet, verdad?
Antena 3, laSexta, Neox, Nova, Mega, Atreseries y después está Atresplayer Exclusivo, Antena 3 Champions.

Por que el Antena 3 Internacional hace días que no lo veo por la web en directo. Y el Atrescine y Hola no emiten jeje.

**Comment by paurg15** [comment]
Si!
Supongo que estos Internacionales solo se verán por Atresplayer con la suscripción internacional, con una VPN diferente o algo así

**Comment by LaQuay** [comment]
Perfecto, pues lo dejo como está ahora (He aplicado tu cambio). Cierro la issue, gracias @paurg15 !

**Comment by paurg15** [comment]
¡De nada, para eso estamos!
