### ISSUE TITLE
Añadir TB Madrid a la Comunidad de Madrid

### ISSUE THREAD

**Issue by kioon** [LaQuay/TDTChannels#910]
Hola

Esta semana han arrancando sus emisiones en la TDT Madrid. Paso el enlace para añadirlo

https://5f4cab04444c6.streamlock.net/gcm2/gcm2_480p/chunklist_w685599251.m3u8

Gracias

**Comment by Nomenteros** [comment]
Gracias por tu informacion, ya he creado el PR para su inclusion en lista.
Pedirte por favor, que para las peticiones utilices: https://tdtchannels.com/peticion , y no Issues
facilita nuestro trabajo y canalizamos asi mejor el tema.
Saludos.
