### ISSUE TITLE
(Android TV) El selector vuelve al inicio del grupo tras terminar items.

### ISSUE THREAD

**Issue by Manuel5cc** [LaQuay/TDTChannels#931]
Dejo referencia de un pequeño fallo que he encontrado en la app para Android, por si puede servir para mejorarla.

Al ir recorriendo el listado de canales, justo cuando el selector debería pasar del final de un grupo al inicio del siguiente, no lo hace sino que salta de nuevo al inicio del grupo, o a veces a la barra superior (filtro, búsqueda, etc.). Ocurre sobre todo si el selector está situado en la zona derecha pero no necesariamente.

**Comment by LaQuay** [comment]
Hola Manue, es algo que tengo pendiente. Hacer que la lista funcione a la perfección en todo tipo de Android se me hace una tarea compleja...

**Comment by Manuel5cc** [comment]
Lo entiendo, y no es algo que afecte al funcionamiento general, pero sí es algo "molesto" sobre todo al buscar canales que están muy abajo. Quizá una solución podría ser que a partir de ciertos tamaños la lista solo tenga una fila.

**Comment by LaQuay** [comment]
Hola, hace unos meses arreglamos esto ya. Cierro, si sigue ocurriendo avisa por favor. Gracias!
