### ISSUE TITLE
Canal no funciona: Clan, Telemadrid, Teledeporte

### ISSUE THREAD

**Issue by eckgemmell** [LaQuay/TDTChannels#944]
<En caso de saberlo indica debajo de esta linea la URL de la web de origen del canal><REQUERIDO>

https://www.tdtchannels.com/lists/tv.m3u

<En caso de saberlo indica debajo de esta linea la URL de la emision><REQUERIDO>

<Indica debajo de esta linea cualquier otra informacion relativa a esta propuesta>
Hola. A mi, nunca me han funcionado estas cadenas. La1 y La2 si funcionan.

**Comment by eckgemmell** [comment]
Perdón. Tengo SSIPTV instalado en un Smart TV (LG). Uso la lista de cadenas m3u o m3u8. 
Cuando intento ver estas cadenas puedo ver la lista de programación pero no aparece nada en la pantalla. Estoy en el reino unido.

**Comment by corrido** [comment]
Yo tengo el mismo problema y estoy en Alemania. Supongo que será un tema de Geolocalización

**Comment by eckgemmell** [comment]
Vale, gracias.

**Comment by LaQuay** [comment]
Efectivamente, he realizado pruebas desde Alemania y no funcionan. Añado el aviso de Geolocalización. Si detectáis alguna que tampoco funcione y no esté reflejado en el fichero, avisad por favor.

https://github.com/LaQuay/TDTChannels/commit/6b9a7b49c6e8d35b8195dd7b4e4d3fea0bc4827b

Gracias!

**Comment by GiovanniSebastian** [comment]
Podrían usar los mpd para Clan y Teledeporte
