### ISSUE TITLE
No funciona Mega España

### ISSUE THREAD

**Issue by fiego14** [LaQuay/TDTChannels#96]
Gracias por tu gran labor

**Comment by LaQuay** [comment]
Gracias! Añadido!

**Comment by adamo331** [comment]
¿hay un enlace para no geo porque el enlace lo agrega solo para la ubicación geográfica?

**Comment by adamo331** [comment]
He probado este https://livestartover.atresmedia.com/mega/bitrate_3.m3u8 pero no funciona parada después de 40 segundos

**Comment by fiego14** [comment]
@adamo331  prueba a utilizar el vpn por kodi, lo añades a España y no deberías tener problemas
