### ISSUE TITLE
Añadir canales oficiales

### ISSUE THREAD

**Issue by wuniversales** [LaQuay/TDTChannels#984]
Paso por aqui una pequeña lista de canales..

- Todos los canales de la lista han sido probados en españa.
- Todos los enlaces han sido obtenidos de las webs oficiales.

### Alacantí TV
**Web oficial**
https://www.alacantitv.com/en-directo/
**Enlace oficial**
`https://ns3063900.ip-5-39-65.eu/hls/alacantixa.m3u8`

### Antofagasta
**Web oficial**
https://www.antofagasta.tv/
**Enlace oficial**
`https://unlimited6-cl.dps.live/atv/atv.smil/atv/livestream2/chunks.m3u8`

### Ues TV
**Web oficial**
https://www.uestv.cl/
**Enlace oficial**
`https://tls.cdnz.cl/uestv/live/playlist.m3u8`

### 13 Max
**Web oficial**
http://13maxtv.com/new/
**Enlace oficial**
`http://coninfo.net:1935/13maxhd/live_720p/playlist.m3u8`

### Canal 9 Multivisión
**Web oficial**
https://multivision.tv/
**Enlace oficial**
`https://panel.dattalive.com/8250/8250/chunklist.m3u8`

### Argentinisima TV Satelital Noticias
**Web oficial**
http://argentinisimatv.com.ar/
**Enlace oficial**
`http://186.0.233.76:1935/Argentinisima/smil:argentinisima.smil/playlist.m3u8`

### 15 TV
**Oficial**
https://15tv.com.mx/
**Enlace oficial**
`http://play.gvstream.net/e-tv-video/play.stream/chunklist.m3u8`

**Comment by LaQuay** [comment]
Gracias por los aportes. Sin embargo deben realizarse a través de tdtchannels.com/peticion, igualmente para esta vez ya no lo hagas. Para la próxima.

Dejo esto abierto, cuando se revise contestamos. Gracias

**Comment by wuniversales** [comment]
Vale, lo tendré en cuenta.
De nada, Saludos

**Comment by LaQuay** [comment]
Canales de España
Alacantí TV -> Ya estaba en el proyecto.

Canales de Chile
Antofagasta -> No me funciona el stream, ni en su web. Es una emisión local, de poco seguimiento, no entra en el concepto TDTChannels.

Ues TV -> Es una emisión local, de poco seguimiento, no entra en el concepto TDTChannels.

Canales argentinos
13 Max -> Es una emisión local, de poco seguimiento, no entra en el concepto TDTChannels.

Canal 9 Multivisión -> No me funciona el stream, ni en su web. Igualmente es una emisión local, no entra en el concepto TDTChannels.

Argentinisima TV Satelital Noticias -> Es una emisión local, de poco seguimiento, no entra en el concepto TDTChannels.

Canales mexicanos -> Es una emisión local, de poco seguimiento, no entra en el concepto TDTChannels.

Gracias igualmente!
