### ISSUE TITLE
Error en EPG de "RT"

### ISSUE THREAD

**Issue by Berto9050** [LaQuay/TDTChannels#995]
Hola.

La guía de RT (RTESP.TV) no se corresponde con la programación real. (Por si sirve de algo, dice mucho "Adelanto promocional de la película 'Animales fantásticos y dónde encontrarlos'")
La programación debería de ser esta http://www.movistarplus.es/canal/la-2?id=RTESP

Si os está dando problemas la página de Movistar podéis probar con estos datos: site="gatotv.com" site_id="rt_en_espanol"

Un saludo.

**Comment by LaQuay** [comment]
Hola @Berto9050, me comenta @HelmerLuzo que ya lo ha solucionado. Puedes confirmar?
Gracias!

**Comment by Berto9050** [comment]
Hola.

Acabo de entrar en https://raw.githubusercontent.com/HelmerLuzo/TDTChannels_EPG/master/TDTChannels_EPG.xml y no hay datos para "RTESP.TV".

**Comment by HelmerLuzo** [comment]
Lo miro ahora mismo

**Comment by HelmerLuzo** [comment]
Cambiado por el ini de gatotv.com

Por lo que veo Movistar lo ha quitado de la parrilla.
